Repository h2oai/datatable, pull requests merged in 2018-05, with the labels that each got.

#991 Anonymize column names in fread's error messages as well
  c/csv/fread.cc
  c/csv/reader.cc
  c/csv/reader.h
  c/csv/reader_fread.cc
  c/csv/reader_fread.h
  c/csv/reader_utils.cc
  tests/fread/test_fread_api.py
Labels: fread

#1038 adding a Contributing topic along with an Issue Template
  CONTRIBUTING.md
  ISSUE_TEMPLATE.md
Labels: documentation :books:

#1044 Move github-related templates into the .github folder
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/Feature_request.md
Labels: ITA

#1063 Initial checkin of data-table help system
  docs/build-instructions.rst
  docs/frame.rst
  docs/index.rst
  docs/install.rst
  docs/using-datatable.rst
Labels: documentation

#1068 Fread fixes
  CHANGELOG.md
  c/csv/reader.cc
  c/csv/reader_fread.cc
  datatable/fread.py
  tests/fread/test_fread_small.py
Labels: bug, fread
