Repository h2oai/datatable, pull requests merged in 2018-03, with the labels that each got.

#883 [BUILD] Bugfix Jenkins Pipeline
  Jenkinsfile2
Labels: ITA :it:, bug :ant:, improve :+1:

#897 Better code logging
  Makefile
  c/column.h
  c/csv/py_csv.cc
  c/csv/py_csv.h
  c/datatablemodule.c
  c/py_buffers.cc
  c/py_column.cc
  c/py_column.h
  c/py_columnset.cc
  c/py_columnset.h
  c/py_datatable.cc
  c/py_datatable.h
  c/py_datawindow.c
  c/py_datawindow.cc
  c/py_datawindow.h
  c/py_rowindex.cc
  c/py_rowindex.h
  c/py_utils.h
  c/utils/exceptions.h
Labels: refactor :recycle:

#902 Sort cleanup
  c/sort.cc
Labels: refactor :recycle:, sort :vertical_traffic_light:
