Repository h2oai/datatable, pull requests merged in 2018-08, with the labels that each got.

#1214 [BUILD] Add option to pass git revision via variable.
  Makefile
  ci/Jenkinsfile2
  setup.py
Labels: ITA, bug

#1217 [BUILD] Specify CI_VERSION_SUFFIX as global env var.
  ci/Jenkinsfile.groovy
Labels: High, ITA, bug

#1221 [BUILD] Clean libs after calculating version.
  ci/Jenkinsfile.groovy
Labels: High, ITA

#1219 [BUILD] Update shared jenkins lib to v1.6.
  ci/Jenkinsfile.groovy
Labels: ITA, improve, low

#1222 Py framework
  Makefile
  c/datatablemodule.cc
  c/frame/py_frame.cc
  c/frame/py_frame.h
  c/py_datatable.cc
  c/python/arg.h
  c/python/args.cc
  c/python/args.h
  c/python/ext_type.h
  c/utils/pyobj.cc
  c/utils/pyobj.h
Labels: refactor

#1224 Move auto-generated parts out of the main makefile
  .gitignore
  Makefile
  ci/fastcheck.py
  ci/make_fast.py
Labels: ITA, refactor

#1228 [BUILD] Allow push to S3 from custom branches.
  ci/Jenkinsfile.groovy
Labels: ITA, improve

#1245 Add documentation for Jay format
  c/jay/README.md
  c/jay/open_jay.cc
  c/jay/save_jay.cc
Labels: documentation

#1251 [BUILD] Fix s3up from custom branches.
  ci/Jenkinsfile.groovy
Labels: ITA, low

#1252 Perform name deduplication in C++
  CHANGELOG.md
  c/options.cc
  c/options.h
  c/py_datatable.cc
  c/py_datatable.h
  c/python/list.cc
  c/python/list.h
  c/python/obj.cc
  c/python/obj.h
  datatable/dt_append.py
  datatable/extras/aggregate.py
  datatable/frame.py
  datatable/graph/cols_node.py
  tests/fread/test_fread_api.py
  tests/test_dt_create.py
Labels: performance, refactor

#1255 Core Frame class improvements
  CHANGELOG.md
  c/frame/py_frame.cc
  c/frame/py_frame.h
  c/frame/py_frame_init.cc
  c/py_datatable.cc
  c/py_datatable.h
  c/python/arg.cc
  c/python/arg.h
  c/python/args.cc
  c/python/args.h
  c/python/ext_type.h
  c/python/obj.cc
  c/python/obj.h
  c/python/tuple.cc
  c/python/tuple.h
  datatable/frame.py
  datatable/graph/__init__.py
  datatable/graph/rows_node.py
  tests/test_dt.py
  tests/test_dt_create.py
  tests/test_dt_options.py
Labels: improve, refactor

#1256 core.Frame name-related functionality improvements
  CHANGELOG.md
  c/frame/py_frame.cc
  c/frame/py_frame.h
  c/frame/py_frame_init.cc
  c/frame/py_frame_names.cc
  c/py_column.cc
  c/py_datatable.cc
  c/py_datatable.h
  c/py_datawindow.cc
  c/python/arg.cc
  c/python/arg.h
  c/python/dict.cc
  c/python/dict.h
  c/python/list.cc
  c/python/list.h
  c/python/obj.cc
  c/python/obj.h
  c/python/string.cc
  c/python/string.h
  c/python/tuple.cc
  c/python/tuple.h
  c/read/column.cc
  c/types.cc
  c/types.h
  c/utils/exceptions.cc
  c/utils/exceptions.h
  datatable/dt_append.py
  datatable/frame.py
  datatable/graph/cols_node.py
  tests/test_dt.py
  tests/test_dt_create.py
  tests/test_nff.py
Labels: improve, refactor

#1259 Implement fuzzy column name matching
  CHANGELOG.md
  c/frame/py_frame.h
  c/frame/py_frame_names.cc
  c/python/arg.cc
  c/python/arg.h
  c/python/dict.cc
  tests/munging/test_dt_cols.py
  tests/test_dt.py
Labels: improve

#1261 [BUILD] Update shared lib.
  ci/Jenkinsfile.groovy
Labels: ITA

#1262 Frame constructor improvements
  CHANGELOG.md
  c/column.h
  c/column_from_pylist.cc
  c/csv/py_csv.cc
  c/datatable.cc
  c/datatablemodule.cc
  c/extras/aggregator.h
  c/frame/py_frame.cc
  c/frame/py_frame.h
  c/frame/py_frame_init.cc
  c/frame/py_frame_names.cc
  c/py_columnset.cc
  c/py_columnset.h
  c/py_datatable.cc
  c/py_datatable_fromlist.cc
  c/python/arg.cc
  c/python/arg.h
  c/python/args.cc
  c/python/dict.cc
  c/python/dict.h
  c/python/list.cc
  c/python/list.h
  c/python/obj.cc
  c/python/obj.h
  c/python/orange.cc
  c/python/orange.h
  c/types.cc
  c/types.h
  datatable/extras/aggregate.py
  datatable/frame.py
  datatable/fread.py
  datatable/graph/__init__.py
  datatable/graph/groupby_node.py
  tests/__init__.py
  tests/munging/test_dt_append.py
  tests/munging/test_dt_cbind.py
  tests/test_dt.py
  tests/test_dt_create.py
  tests/test_dt_sort.py
  tests/test_dt_stats.py
  tests/test_join.py
Labels: improve, refactor

#1265 Frame initialization improvements
  CHANGELOG.md
  c/datatablemodule.cc
  c/extras/aggregator.cc
  c/frame/py_frame.cc
  c/frame/py_frame.h
  c/frame/py_frame_init.cc
  c/py_datatable.cc
  c/py_datatable.h
  c/python/arg.cc
  c/python/arg.h
  c/python/obj.cc
  c/python/obj.h
  datatable/extras/aggregate.py
  datatable/frame.py
  datatable/fread.py
  datatable/nff.py
  tests/extras/test_aggregate.py
  tests/fread/test_fread_api.py
  tests/test_dt.py
Labels: improve, refactor
