Repository h2oai/datatable, pull requests merged in 2018-11, with the labels that each got.

#1390 Implement FTRL-Proximal online learning algorithm
  c/datatablemodule.cc
  c/datatablemodule.h
  c/extras/aggregator.cc
  c/extras/aggregator.h
  c/extras/ftrl.cc
  c/extras/ftrl.h
  c/extras/murmurhash.cc
  c/extras/murmurhash.h
  c/python/arg.cc
  c/python/arg.h
  datatable/extras/aggregate.py
  datatable/extras/ftrl.py
Labels: improve

#1399 Update shared lib
  ci/Jenkinsfile.groovy
Labels: ITA

#1409 Replace merge-only scenario with just re-testing
  c/extras/aggregator.cc
  tests/extras/test_aggregate.py
Labels: bug

#1418 Fix crash in test_setfns_random
  c/sort.cc
Labels: segfault, sort

#1420 Adjust the styling of Frame's html repr
  c/frame/_repr_html_.cc
Labels: improve

#1421 Multi-threaded multi-column join
  c/frame/join.cc
Labels: improve, join, performance

#1427 Fix Frame rendering style in docs
  c/frame/_repr_html_.cc
  docs/_static/code.css
  docs/conf.py
  docs/frame.rst
  docs/using-datatable.rst
Labels: documentation

#1431 Add column type indicators in Jupyter
  CHANGELOG.md
  c/frame/_repr_html_.cc
  c/types.cc
  c/types.h
  docs/_static/code.css
  docs/using-datatable.rst
Labels: improve

#1417 Convert FTRL code to a core datatable class
  c/datatablemodule.cc
  c/datatablemodule.h
  c/extras/aggregator.cc
  c/extras/ftrl.cc
  c/extras/ftrl.h
  c/extras/py_ftrl.cc
  c/extras/py_ftrl.h
  datatable/extras/__init__.py
  datatable/extras/ftrl.py
Labels: improve

#1436 [BUILD] Fix numbering.
  Makefile
  ci/Jenkinsfile.groovy
Labels: ITA

#1435 Sort exemplars even when aggregation is bypassed
  c/extras/aggregator.cc
  tests/extras/test_aggregate.py
Labels: High, improve

#1439 Add methods to_tuples() and to_dict()
  CHANGELOG.md
  c/frame/py_frame.cc
  c/frame/py_frame.h
  c/frame/to_python.cc
  datatable/frame.py
  tests/test_dt.py
Labels: improve

#1453 Avoid memory leak in Aggregator::adjust_members
  c/extras/aggregator.cc
Labels: bug

#1457 Various code style fixes
  c/csv/reader_fread.cc
  c/csv/reader_parsers.cc
  c/datatablemodule.cc
  c/extras/aggregator.cc
  c/frame/py_frame_init.cc
  c/frame/to_python.cc
  c/sort.cc
  c/types.cc
  ci/asan-env.sh
  datatable/fread.py
  datatable/graph/llvm.py
  datatable/types.py
  datatable/utils/terminal.py
  datatable/xls.py
  tests/extras/test_aggregate.py
  tests/munging/test_replace.py
  tests/test_dt.py
  tests/test_reduce.py
  tests/test_types.py
Labels: refactor

#1458 Clean up some .md files
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  README.md
  c/jay/README.md
Labels: refactor
