Repository h2oai/datatable, pull requests merged in 2018-10, with the labels that each got.

#1328 Improve handling of Excel files
  CHANGELOG.md
  c/frame/py_frame_init.cc
  datatable/fread.py
  datatable/xls.py
  tests/test_dt_create.py
Labels: fread

#1336 Fix segfaults when there are no continuous columns in ND
  c/extras/aggregator.cc
  c/extras/aggregator.h
  tests/extras/test_aggregate.py
Labels: segfault

#1342 Improve appearance of example code / results in documentation
  c/frame/_repr_html_.cc
  docs/Makefile
  docs/_static/code.css
  docs/conf.py
  docs/index.rst
  docs/install.rst
  docs/using-datatable.rst
Labels: documentation

#1338 Do proper N/A handling in 1D and 2D
  c/extras/aggregator.cc
  c/extras/aggregator.h
  datatable/extras/aggregate.py
  tests/extras/test_aggregate.py
Labels: bug

#1344 Make sure that help on dt.options is available from Python
  c/datatablemodule.cc
  c/datatablemodule.h
  c/options.cc
  c/options.h
  datatable/__init__.py
  datatable/frame.py
  datatable/fread.py
  datatable/options.py
  tests/test_dt_options.py
Labels: documentation

#1346 Do random sampling for categorical data sets in aggregator
  c/extras/aggregator.cc
  c/extras/aggregator.h
  datatable/extras/aggregate.py
  tests/extras/test_aggregate.py
Labels: improve

#1351 Set proper value for `nrows` when resolving map function for binary op expressions
  c/expr/binaryop.cc
Labels: bug

#1350 Implementation of exponential expression
  c/expr/unaryop.cc
  datatable/__init__.py
  datatable/expr/__init__.py
  datatable/expr/consts.py
  datatable/expr/exp_expr.py
  tests/test_dt_expr.py
Labels: improve

#1355 Refactor setup.py to not rely on Llvm/Clang during build process
  CHANGELOG.md
  Makefile
  ci/make_fast.py
  ci/setup_utils.py
  setup.py
Labels: ITA

#1362 Allow datatable to be compiled with gcc on linux
  c/csv/reader.cc
  c/csv/reader_fread.cc
  c/expr/binaryop.cc
  c/jay/open_jay.cc
  c/options.cc
  c/python/args.cc
  c/python/args.h
  c/python/ext_module.h
  c/sort.cc
  c/stats.cc
  c/str/py_str.cc
  c/str/split_into_nhot.cc
  c/types.h
  c/utils/parallel.h
  c/utils/shared_mutex.h
  ci/setup_utils.py
  setup.py
  tests/fread/test_fread_large.py
Labels: ITA

#1371 Win32
  c/csv/dtoa.h
  c/csv/writer.h
  c/encodings.cc
  c/encodings.h
  c/expr/unaryop.cc
  c/lib/flatbuffers/flatbuffers.h
  c/memrange.cc
  c/py_column.cc
  c/py_encodings.h
  c/utils/file.h
  ci/setup_utils.py
  setup.py
Labels: ITA

#1373 integer csv parsers
  c/csv/reader_parsers.cc
Labels: fread

#1374 Allow g-columns to be selectable during a join
  CHANGELOG.md
  c/py_datawindow.cc
  c/rowindex_array.cc
  datatable/expr/column_expr.py
  datatable/graph/cols_node.py
  tests/test_join.py
Labels: join

#1375 Add tests for stype .min / .max
  tests/test_types.py
Labels: test
