Repository h2oai/datatable, pull requests merged in 2018-06, with the labels that each got.

#1078 Allow to pass progress_fn=None in fread()
  datatable/fread.py
Labels: fread

#1107 Add some more tests for fread
  datatable/fread.py
  tests/fread/test_fread_api.py
  tests/fread/test_fread_detect.py
  tests/fread/test_fread_small.py
Labels: fread, test

#1108 Fix occasional memory errors caused by a lack of available mmap handles.
  CHANGELOG.md
  c/memrange.cc
Labels: improve

#1062 Moments
  c/column.cc
  c/column.h
  c/column_int.cc
  c/column_real.cc
  c/datatable.cc
  c/datatable.h
  c/py_datatable.cc
  c/py_datatable.h
  c/stats.cc
  c/stats.h
Labels: improve

#1111 Memory handling code cleanup
  Makefile
  c/column_pyobj.cc
  c/columnset.cc
  c/datatable.cc
  c/datatable.h
  c/datatable_cbind.cc
  c/datatable_load.cc
  c/datatable_rbind.cc
  c/datatablemodule.cc
  c/memrange.cc
  c/memrange.h
  c/py_buffers.cc
  c/py_columnset.cc
  c/py_datatable.cc
  c/py_datatable_fromlist.c
  c/py_types.c
  c/py_utils.c
  c/sort.cc
  c/types.c
  c/utils.c
  c/utils.h
  c/utils/alloc.cc
  c/utils/alloc.h
  c/utils/array.h
  c/writebuf.cc
  c/writebuf.h
Labels: refactor

#1124 All remaining .c files renamed into .cc; fastcheck.py moved into ci folder
  Makefile
  c/encodings.cc
  c/py_datatable_fromlist.cc
  c/py_encodings.cc
  c/py_types.cc
  c/py_utils.cc
  c/types.c
  c/types.cc
  c/utils.cc
  ci/fastcheck.py
  tests/test_types.py
Labels: refactor

#1112 [BUILD] Rewrite Jenkinsfile. Remove Ubuntu build, keep Ubuntu tests for now.
  Makefile
  ci/Jenkinsfile2
Labels: ITA
