Repository h2oai/datatable, pull requests merged in 2018-12, with the labels that each got.

#1464 Clean up of the API for py::otuple and py::rtuple
  c/column_from_pylist.cc
  c/datatable.h
  c/frame/getset.cc
  c/frame/key.cc
  c/frame/py_frame_init.cc
  c/python/_all.h
  c/python/dict.cc
  c/python/dict.h
  c/python/float.cc
  c/python/float.h
  c/python/int.cc
  c/python/int.h
  c/python/obj.cc
  c/python/obj.h
  c/python/tuple.cc
  c/python/tuple.h
Labels: refactor

#1465 Minor code fixes recommended by Codacity
  CHANGELOG.md
  c/memrange.cc
  datatable/expr/exp_expr.py
  datatable/expr/isna_expr.py
  datatable/expr/literal_expr.py
  datatable/expr/sd_expr.py
  datatable/expr/unary_expr.py
  datatable/frame.py
  datatable/graph/cols_node.py
  datatable/graph/rows_node.py
  datatable/nff.py
  datatable/xls.py
  setup.py
  tests/fread/test_fread_api.py
  tests/fread/test_fread_issues.py
  tests/fread/test_fread_small.py
  tests/test_dt.py
  tests/test_dt_create.py
  tests/test_nff.py
Labels: refactor

#1470 Namedtuple functionality
  c/python/namedtuple.cc
  c/python/namedtuple.h
  c/python/obj.cc
  c/python/obj.h
Labels: improve

#1460 FTRL column hashers, improved API and tests
  c/extras/aggregator.cc
  c/extras/aggregator.h
  c/extras/dt_ftrl.cc
  c/extras/dt_ftrl.h
  c/extras/ftrl.cc
  c/extras/hash.cc
  c/extras/hash.h
  c/extras/murmurhash.cc
  c/extras/murmurhash.h
  c/extras/py_ftrl.cc
  c/extras/py_ftrl.h
  c/python/arg.cc
  c/python/arg.h
  c/python/obj.cc
  c/python/obj.h
  tests/extras/test_ftrl.py
Labels: improve, test

#1472 WIP on evaluating DT[i,j,...] in C++
  c/expr/base_expr.cc
  c/expr/base_expr.h
  c/expr/i_node.cc
  c/expr/i_node.h
  c/expr/j_node.cc
  c/expr/j_node.h
  c/expr/workframe.cc
  c/expr/workframe.h
  c/frame/__getitem__.cc
  c/python/obj.cc
  c/python/obj.h
  c/python/slice.cc
  c/python/slice.h
  c/rowindex.h
  datatable/expr/consts.py
  datatable/expr/isna_expr.py
  datatable/expr/unary_expr.py
  tests/test_dt.py
Labels: refactor

#1480 Review and refactor validation in `py::Ftrl` class
  c/extras/dt_ftrl.cc
  c/extras/dt_ftrl.h
  c/extras/py_ftrl.cc
  c/extras/py_ftrl.h
  c/extras/py_validator.cc
  c/extras/py_validator.h
  c/python/arg.cc
  c/python/arg.h
  c/python/obj.cc
  c/python/obj.h
  tests/extras/test_ftrl.py
Labels: improve, refactor, test

#1482 Add support for pickling Ftrl objects
  c/extras/dt_ftrl.cc
  c/extras/dt_ftrl.h
  c/extras/py_ftrl.cc
  c/extras/py_ftrl.h
  datatable/models.py
  tests/extras/test_aggregate.py
  tests/extras/test_ftrl.py
Labels: improve

#1485 Estimate feature importance in FTRL model
  c/extras/dt_ftrl.cc
  c/extras/dt_ftrl.h
  c/extras/py_ftrl.cc
  c/extras/py_ftrl.h
  tests/extras/test_ftrl.py
Labels: improve

#1489 Simplify formulas in Ftrl
  c/extras/dt_ftrl.cc
  c/extras/dt_ftrl.h
Labels: performance, refactor

#1495 Adjust feature importance test for FTRL
  tests/extras/test_ftrl.py
Labels: test

#1497 Improve test coverage for i_node.cc
  c/expr/i_node.cc
  c/expr/j_node.cc
  c/expr/j_node.h
  c/rowindex_array.cc
  ci/llvm-gcov.sh
  datatable/expr/mean_expr.py
  datatable/expr/minmax_expr.py
  datatable/expr/sd_expr.py
  tests/munging/test_dt_rows.py
Labels: test

#1501 Do not train FTRL model on rows where target is None
  c/extras/dt_ftrl.cc
  tests/extras/test_ftrl.py
Labels: bug
