Repository h2oai/datatable, pull requests merged in 2018-09, with the labels that each got.

#1269 Improve test coverage for py_frame_init.cc and py_frame_names.cc
  c/datatablemodule.cc
  c/frame/py_frame.h
  c/frame/py_frame_init.cc
  c/frame/py_frame_names.cc
  c/python/int.cc
  c/python/string.cc
  c/ztest.h
  setup.py
  tests/test_dt.py
  tests/test_dt_create.py
Labels: test

#1272 Extra options to generate better coverage report
  Makefile
  c/frame/names.cc
Labels: ITA

#1283 [BUILD] Update Jenkins lib to 1.9
  ci/Jenkinsfile.groovy
Labels: ITA

#1288 Update shared jenkins lib in docker images jenkinsfile.
  ci/Jenkinsfile-build-docker-images.groovy
Labels: ITA

#1289 Cbind improvements
  CHANGELOG.md
  c/datatable.h
  c/datatable_cbind.cc
  c/extras/aggregator.cc
  c/frame/cbind.cc
  c/frame/names.cc
  c/frame/py_frame.cc
  c/frame/py_frame.h
  c/py_datatable.cc
  c/py_datatable.h
  c/python/arg.cc
  c/python/arg.h
  c/python/args.cc
  c/python/ext_type.h
  c/python/oiter.h
  datatable/dt_append.py
  datatable/frame.py
  tests/munging/test_dt_cbind.py
Labels: bug, improve, refactor

#1297 Parallelizing main loop of ND aggregator
  c/extras/aggregator.cc
  c/extras/aggregator.h
  c/read/fread/fread_thread_context.cc
  c/read/parallel_reader.cc
  c/str/split_into_nhot.cc
  c/utils/shared_mutex.h
  c/writebuf.cc
  datatable/extras/aggregate.py
  tests/extras/test_aggregate.py
Labels: improve
