Repository h2oai/datatable, pull requests merged in 2019-08, with the labels that each got.

#1944 Further refactoring of Column / OColumn
  c/column.cc
  c/column.h
  c/column_from_pylist.cc
  c/column_fw.cc
  c/column_pyobj.cc
  c/column_string.cc
  c/csv/reader.cc
  c/datatable.h
  c/expr/expr_binaryop.cc
  c/expr/expr_literal.cc
  c/expr/expr_reduce.cc
  c/expr/expr_str.cc
  c/expr/expr_str.h
  c/expr/expr_unaryop.cc
  c/expr/repl_node.cc
  c/expr/virtual_column.cc
  c/frame/__init__.cc
  c/frame/__sizeof__.cc
  c/frame/cast.cc
  c/frame/names.cc
  c/frame/rbind.cc
  c/frame/repeat.cc
  c/frame/stats.cc
  c/frame/to_numpy.cc
  c/jay/open_jay.cc
  c/models/aggregator.cc
  c/models/dt_ftrl.cc
  c/models/kfold.cc
  c/models/label_encode.cc
  c/models/label_encode.h
  c/py_buffers.cc
  c/set_funcs.cc
  c/str/split_into_nhot.cc
  c/wstringcol.cc
Labels: refactor

#1946 Further transitioning towards OColumn class
  c/column.cc
  c/column.h
  c/column_bool.cc
  c/column_from_pylist.cc
  c/column_fw.cc
  c/column_int.cc
  c/column_pyobj.cc
  c/column_string.cc
  c/expr/expr_cast.cc
  c/expr/expr_unaryop.cc
  c/frame/cast.cc
  c/frame/rbind.cc
  c/frame/stats.cc
  c/jay/open_jay.cc
  c/jay/save_jay.cc
  c/models/dt_ftrl.cc
  c/rowindex_array.cc
  c/rowindex_impl.h
  c/stats.cc
  c/stats.h
Labels: refactor

#1948 Simplify 'value reading' mechanism of CsvWriter
  c/column.cc
  c/column.h
  c/write/column_builder.cc
  c/write/column_builder.h
  c/write/csv_writer.cc
  c/write/value_reader.cc
  c/write/value_reader.h
  c/write/value_writer.cc
  c/write/value_writer.h
  c/write/write_manager.cc
  c/write/write_manager.h
Labels: refactor

#1947 Add progress reporting to Ftrl model
  c/models/aggregator.h
  c/models/column_hasher.cc
  c/models/dt_ftrl.cc
  c/progress/_options.cc
  c/progress/_options.h
  c/progress/progress_bar.cc
  c/progress/work.cc
  tests/models/test_aggregate.py
  tests/test_options.py
Labels: improve

#1951 Improve FTRL progress reporting
  c/models/dt_ftrl.cc
  c/progress/work.cc
  c/progress/work.h
Labels: improve

#1957 zlib.h header file included into c/lib/ folder
  c/datatable.cc
  c/lib/zlib/zconf.h
  c/lib/zlib/zlib.h
  c/utils/assert.h
  c/write/zlib_writer.h
  ci/setup_utils.py
Labels: ITA

#1955 Further work on refactoring Column class
  c/column.cc
  c/column.h
  c/column_fw.cc
  c/column_pyobj.cc
  c/column_string.cc
  c/datatable.h
  c/expr/expr_binaryop.cc
  c/expr/expr_reduce.cc
  c/expr/repl_node.cc
  c/expr/workframe.cc
  c/frame/__init__.cc
  c/frame/cast.cc
  c/frame/integrity_check.cc
  c/frame/rbind.cc
  c/frame/repeat.cc
  c/models/label_encode.h
  c/set_funcs.cc
  c/sort.cc
  c/stats.cc
  c/str/split_into_nhot.cc
  tests/test_dt_stats.py
Labels: refactor

#1956 Adjust the way FTRL handles infinities
  c/models/column_hasher.cc
  c/models/dt_ftrl.cc
  c/models/dt_ftrl.h
  c/models/py_ftrl.cc
  c/models/py_validator.cc
  c/models/py_validator.h
  c/progress/_options.cc
  tests/models/test_ftrl.py
Labels: improve, refactor, test

#1959 Ongoing refactoring of OColumn / virtual columns
  c/api.cc
  c/column.cc
  c/column.h
  c/column_fw.cc
  c/column_string.cc
  c/expr/virtual_column.cc
  c/frame/cast.cc
  c/frame/join.cc
  c/frame/rbind.cc
  c/sort.cc
Labels: refactor

#1967 Improve documentation for f-expressions
  docs/f-expressions.rst
Labels: documentation

#1969 Further refactoring into the new OColumn API
  c/expr/expr_binaryop.cc
  c/expr/expr_str.cc
  c/expr/expr_str.h
  c/models/aggregator.cc
  c/models/aggregator.h
  c/models/column_convertor.h
  c/sort.cc
  c/sort.h
  c/sort_groups.cc
  c/sort_insert.cc
  c/types.h
Labels: refactor

#1971 Remove OColumn.get() method
  c/api.cc
  c/column.cc
  c/column.h
  c/frame/rbind.cc
  c/jay/open_jay.cc
  c/jay/save_jay.cc
  c/python/obj.cc
  c/python/obj.h
  tests/munging/test_rbind.py
Labels: refactor

#1966 Replace stype with ltype check for validation target column
  c/models/dt_ftrl.cc
  c/models/dt_ftrl.h
  c/models/py_ftrl.cc
  c/types.cc
  c/types.h
  c/utils/exceptions.cc
  c/utils/exceptions.h
  tests/models/test_ftrl.py
Labels: improve

#1973 Remove deprecated Frame methods scalar(), append() and save()
  c/frame/py_frame.cc
  datatable/__init__.py
  datatable/frame.py
  tests/test_dt_create.py
  tests/test_groups.py
Labels: API change

#1975 Merge virtual_column into Column
  c/column.cc
  c/column.h
  c/column_fw.cc
  c/column_impl.cc
  c/column_impl.h
  c/column_int.cc
  c/column_pyobj.cc
  c/column_real.cc
  c/column_string.cc
  c/datatable.cc
  c/expr/expr.cc
  c/expr/expr.h
  c/expr/expr_binaryop.cc
  c/expr/expr_binaryop.h
  c/expr/expr_cast.cc
  c/expr/expr_cast.h
  c/expr/expr_column.cc
  c/expr/expr_column.h
  c/expr/expr_columnset.cc
  c/expr/expr_columnset.h
  c/expr/expr_literal.cc
  c/expr/expr_literal.h
  c/expr/expr_reduce.cc
  c/expr/expr_reduce.h
  c/expr/expr_str.cc
  c/expr/expr_str.h
  c/expr/expr_unaryop.cc
  c/expr/expr_unaryop.h
  c/expr/i_node.cc
  c/expr/j_node.cc
  c/expr/repl_node.cc
  c/expr/virtual_column.cc
  c/expr/virtual_column.h
  c/frame/integrity_check.cc
  c/frame/join.cc
  c/frame/rbind.cc
  c/models/column_convertor.h
  c/models/label_encode.h
  c/python/obj.cc
  c/python/obj.h
  c/sort.cc
  c/stats.cc
  c/stats.h
  c/types.h
  c/utils/assert.h
Labels: refactor
