Repository h2oai/datatable, pull requests merged in 2019-05, with the labels that each got.

#1836 Minor improvement of Aggregator tests
  c/models/aggregator.cc
  tests/models/test_aggregate.py
Labels: test

#1841 Fix creation of Frame in fread for str64 columns with NAs
  CHANGELOG.md
  c/csv/reader_fread.cc
  c/csv/reader_fread.h
  c/read/column.cc
  c/read/column.h
  c/read/fread/fread_thread_context.cc
  c/utils/file.cc
  tests/fread/test_fread_large.py
Labels: bug, fread

#1842 kfold_random() function
  CHANGELOG.md
  c/models/kfold.cc
  datatable/models.py
  tests/models/test_kfold.py
Labels: new feature

#1846 Make FTRL model to resume properly after pickling
  CHANGELOG.md
  c/models/py_ftrl.cc
  c/models/py_ftrl.h
  tests/models/test_ftrl.py
Labels: bug, test

#1849 Do not run fallocate() if file size is 0
  c/utils/file.cc
  tests/test_tocsv.py
Labels: bug

#1854 Simplify structure of unaryop_expr.cc, and prepare to merge with math functionality
  CHANGELOG.md
  c/datatablemodule.cc
  c/expr/expr.h
  c/expr/expr_unaryop.cc
  c/expr/expr_unaryop.h
  datatable/expr/expr.py
  tests/munging/test_str.py
  tests/test_dt_expr.py
Labels: refactor

#1852 Re-factor FTRL options handling and Python setters
  c/csv/reader.cc
  c/datatable_load.cc
  c/frame/key.cc
  c/frame/names.cc
  c/frame/py_frame.cc
  c/frame/py_frame.h
  c/models/dt_ftrl.cc
  c/models/dt_ftrl.h
  c/models/dt_ftrl_base.h
  c/models/py_ftrl.cc
  c/models/py_ftrl.h
  c/models/py_validator.h
  c/options.cc
  c/options.h
  c/parallel/thread_pool.cc
  c/progress/_options.cc
  c/python/arg.cc
  c/python/arg.h
  c/python/args.h
  c/sort.cc
  docs/ftrl.rst
  tests/models/test_ftrl.py
Labels: improve, refactor, test

#1859 update link as wiki is outdated
  README.md
Labels: documentation

#1862 Cleanup of unaryop_expr + add comments
  c/expr/expr_unaryop.cc
  c/expr/expr_unaryop.h
Labels: refactor

#1861 Create `.. dtframe` directive for documentation
  .travis.yml
  CHANGELOG.md
  datatable/sphinxext/dtframe_directive.py
  docs/_static/code.css
  docs/api/math.rst
  docs/conf.py
  docs/using-datatable.rst
  requirements_docs.txt
  setup.py
  tests/test_sphinxext_dtframe.py
Labels: documentation, new feature

#1863 Fix split_into_nhot(), so that it encodes NA's into NA's
  c/models/aggregator.cc
  c/models/dt_ftrl.cc
  c/str/py_str.cc
  c/str/split_into_nhot.cc
  tests/models/test_ftrl.py
  tests/munging/test_str.py
Labels: bug, segfault, test
