Repository h2oai/datatable, pull requests merged in 2019-06, with the labels that each got.

#1878 Fix test_html_repr_joined_frame failing with py35
  tests/test_dt.py
Labels: test

#1873 Use semaphores to handle thread sleep cycle
  c/parallel/semaphore.h
  c/parallel/thread_worker.cc
  c/parallel/thread_worker.h
Labels: performance

#1879 Fix segfault in progress reporting
  c/progress/manager.cc
  c/progress/manager.h
  c/utils/exceptions.cc
Labels: segfault

#1883 Skip extra flags when determining setup.py command
  setup.py
Labels: ITA

#1884 Add model_type info to FTRL docs
  docs/ftrl.rst
Labels: documentation

#1885 Improve performance of sorting by using correct chunk size for parallel reordering
  c/sort.cc
Labels: performance, sort

#1886 Fix API reference in docs
  docs/index.rst
Labels: documentation

#1887 Add fast compilation mode with full optimizations
  Makefile
  ci/make_fast.py
  ci/setup_utils.py
Labels: ITA, new feature

#1888 Faster .nunique() for strings
  c/lib/parallel_hashmap/meminfo.h
  c/lib/parallel_hashmap/phmap.h
  c/lib/parallel_hashmap/phmap_base.h
  c/lib/parallel_hashmap/phmap_bits.h
  c/lib/parallel_hashmap/phmap_config.h
  c/lib/parallel_hashmap/phmap_fwd_decl.h
  c/lib/parallel_hashmap/phmap_utils.h
  c/models/label_encode.h
  c/models/murmurhash.cc
  c/stats.cc
  c/stats.h
Labels: performance

#1892 Do binomial check in label_encode functions only when adding new labels
  CHANGELOG.md
  c/models/label_encode.h
Labels: bug
