Repository h2oai/datatable, pull requests merged in 2019-12, with the labels that each got.

#2215 Improve frame rendering in Jupyter and fix the interactive mode
  c/frame/__repr__.cc
  c/frame/repr/html_styles.cc
  c/frame/repr/html_widget.h
Labels: bug

#2224 Fix feature importance normalization
  c/models/dt_ftrl.cc
  tests/models/test_ftrl.py
Labels: bug

#2221 Add humanize_bytes unit tests
  tests/test_utils_misc.py
Labels: test

#2227 Allow .reset() to be called on untrained FTRL model
  c/models/py_ftrl.cc
  docs/changelog/v-0-11-0.rst
  tests/models/test_ftrl.py
Labels: segfault, test

#2228 Replace custom wheel URLs with pip install datatable in README
  README.md
Labels: documentation

#2230 Update copyright message on docs
  docs/conf.py
Labels: documentation

#2233 Fix test_fread_omnibus
  tests/fread/test_fread_random.py
Labels: test

#2234 Adjust monitor thread priority on Windows
  c/parallel/monitor_thread.cc
  c/parallel/semaphore.h
  c/read/constants.cc
  c/utils/alloc.h
Labels: ITA

#2239 Add a workaround for a POSIX write() function on Windows
  c/writebuf.cc
Labels: ITA

#2238 Add a code to detect terminal size on Windows
  c/frame/repr/terminal_widget.cc
  c/utils/terminal/terminal.cc
  c/utils/terminal/terminal.h
Labels: ITA, improve, refactor

#2240 [WIP] add zlib library source
  c/lib/zlib/adler32.cc
  c/lib/zlib/crc32.cc
  c/lib/zlib/crc32.h
  c/lib/zlib/deflate.cc
  c/lib/zlib/deflate.h
  c/lib/zlib/trees.cc
  c/lib/zlib/trees.h
  c/lib/zlib/zconf.h
  c/lib/zlib/zlib.h
  c/lib/zlib/zutil.cc
  c/lib/zlib/zutil.h
  c/write/zlib_writer.h
  ci/setup_utils.py
  ci/xbuild/extension.py
  ci/xbuild/logger.py
Labels: ITA

#2241 Allow reading Jay files without .jay extension
  c/buffer.cc
  c/csv/reader.cc
  c/csv/reader.h
  c/jay/open_jay.cc
  datatable/fread.py
  docs/_static/code.css
  docs/changelog/definitions.rst
  docs/changelog/v-0-11-0.rst
  tests/fread/test_fread_large.py
  tests/test_jay.py
Labels: fread, improve

#2235 [xbuild] Adjustments to compile/link process
  ci/make_fast.py
  ci/xbuild/compiler.py
  ci/xbuild/extension.py
  ci/xbuild/logger.py
  ext.py
  tests/frame/test-repr-text.py
  tests/random_driver.py
  tests/test_dt.py
  tests/test_parallel.py
Labels: ITA

#2244 Fix path in zlib headers
  c/lib/zlib/adler32.cc
  c/lib/zlib/crc32.cc
  c/lib/zlib/deflate.cc
  c/lib/zlib/deflate.h
  c/lib/zlib/trees.cc
  c/lib/zlib/zutil.cc
  c/lib/zlib/zutil.h
Labels: ITA

#2245 Reorganize the way portable _notnan() function is used
  c/column/func_binary.h
  c/column/func_unary.h
  c/expr/fnary/rowsum.cc
  c/models/dt_ftrl.h
  c/models/utils.h
Labels: ITA

#2246 Various fixes and changes to xbuild to make it run on WIndows
  ci/xbuild/__init__.py
  ci/xbuild/compiler.py
  ci/xbuild/extension.py
Labels: ITA

#2248 Fix copysign and other various adjustments for Windows build
  c/datatable.cc
  c/datatablemodule.cc
  c/datatablemodule.h
  c/expr/fbinary/math.cc
  c/models/utils.cc
  c/models/utils.h
  c/utils/misc.cc
Labels: ITA

#2247 Add Wheel-building functionality to xbuild
  ci/xbuild/__init__.py
  ci/xbuild/logger.py
  ci/xbuild/wheel.py
  ext.py
  pyproject.toml
Labels: ITA, improve

#2254 Fix saving to csv a frame with computed boolean column
  c/write/value_writer.cc
  docs/changelog/v-0-11-0.rst
  tests/test_tocsv.py
Labels: bug

#2259 Improve handling of .labels in FTRL
  c/models/dt_ftrl.cc
  c/models/dt_ftrl.h
  c/models/dt_ftrl_base.h
  c/models/label_encode.cc
  c/models/label_encode.h
  c/models/py_ftrl.cc
  docs/changelog/v-0-11-0.rst
  tests/models/test_ftrl.py
Labels: improve, test

#2260 [xbuild] Implement building sdists
  ci/xbuild/logger.py
  ci/xbuild/wheel.py
  ext.py
  pyproject.toml
Labels: ITA, improve

#2252 Add Windows implementation of mmap functions
  Makefile
  c/buffer.cc
  c/lib/mman/mman.cc
  c/lib/mman/mman.h
  c/read/constants.cc
  c/read/constants.h
  c/writebuf.cc
Labels: ITA, improve

#2264 Allow FTRL training for a fractional number of epochs
  .idea/inspectionProfiles/Project_Default.xml
  c/models/dt_ftrl.cc
  c/models/dt_ftrl.h
  c/models/dt_ftrl_base.h
  c/models/py_ftrl.cc
  c/models/py_ftrl.h
  docs/changelog/v-0-11-0.rst
  tests/models/test_ftrl.py
Labels: improve, test

#2270 Implement --audit parameter for ext.py
  ci/xbuild/logger.py
  ci/xbuild/wheel.py
  ext.py
Labels: ITA, improve

#2275 Implement Sphinx extension for writing changelogs
  datatable/sphinxext/dt_changelog.py
  datatable/sphinxext/dtframe_directive.py
  docs/_static/changelog.css
  docs/_static/code.css
  docs/_static/new.svg
  docs/changelog.rst
  docs/changelog/definitions.rst
  docs/changelog/v-0-10-0.rst
  docs/changelog/v-0-11-0.rst
  docs/conf.py
  docs/ftrl.rst
Labels: documentation, new feature
