Repository h2oai/datatable, pull requests merged in 2019-07, with the labels that each got.

#1896 Fix tests so that they work with pytest 5.0
  tests/conftest.py
  tests/fread/test_fread_api.py
  tests/fread/test_fread_issues.py
  tests/fread/test_fread_small.py
Labels: test

#1895 Emit delayed messages in fread under the protection of a mutex
  c/csv/reader.cc
Labels: fread

#1894 Improve efficiency of sorting
  c/parallel/parallel_for_dynamic.cc
  c/parallel/parallel_for_static.cc
  c/sort_insert.cc
Labels: performance, sort

#1897 Undoing recent changes to binary insert-sort, possibly unstable
  c/sort_insert.cc
Labels: sort

#1899 Parallel for static improvements
  c/frame/join.cc
  c/models/dt_ftrl.cc
  c/parallel/api.h
  c/parallel/api_primitives.h
  c/parallel/parallel_for_static.cc
  c/parallel/parallel_for_static.h
  c/parallel/ztest_parallel_for.cc
  c/progress/manager.cc
  c/rowindex_array.cc
  c/sort.cc
  c/stats.cc
  c/str/split_into_nhot.cc
  c/utils/assert.h
  tests/models/test_ftrl.py
Labels: performance, refactor

#1900 Fix failing FTRL tests
  c/models/dt_ftrl.cc
  c/models/dt_ftrl_base.cc
  c/models/dt_ftrl_base.h
  c/models/label_encode.h
  tests/models/test_ftrl.py
Labels: test

#1901 Improvements to sort
  c/parallel/semaphore.h
  c/sort.cc
Labels: performance, sort

#1904 Refactor & simplify the C++/Python conversion layer
  c/api.cc
  c/datatablemodule.cc
  c/expr/by_node.cc
  c/expr/by_node.h
  c/expr/expr.h
  c/expr/i_node.cc
  c/expr/join_node.cc
  c/expr/join_node.h
  c/expr/sort_node.cc
  c/expr/sort_node.h
  c/frame/__init__.cc
  c/frame/__repr__.cc
  c/frame/__sizeof__.cc
  c/frame/cbind.cc
  c/frame/key.cc
  c/frame/names.cc
  c/frame/py_frame.cc
  c/frame/py_frame.h
  c/frame/rbind.cc
  c/frame/replace.cc
  c/frame/stats.cc
  c/frame/to_csv.cc
  c/frame/to_numpy.cc
  c/frame/to_python.cc
  c/jay/save_jay.cc
  c/models/py_ftrl.cc
  c/models/py_ftrl.h
  c/options.cc
  c/py_buffers.cc
  c/py_rowindex.cc
  c/py_rowindex.h
  c/python/args.h
  c/python/ext_type.h
  c/python/obj.cc
  c/python/xobject.h
  c/sort.cc
Labels: refactor

#1913 Single-column selector DT[col]
  CHANGELOG.md
  c/csv/py_csv.cc
  c/datatable.cc
  c/datatable.h
  c/datatable_load.cc
  c/expr/workframe.cc
  c/frame/__getitem__.cc
  c/frame/__init__.cc
  c/frame/__iter__.cc
  c/frame/__repr__.cc
  c/frame/names.cc
  c/frame/py_frame.cc
  c/frame/py_frame.h
  c/frame/repeat.cc
  c/frame/stats.cc
  c/frame/to_numpy.cc
  c/jay/open_jay.cc
  c/models/aggregator.cc
  c/models/kfold.cc
  c/models/py_ftrl.cc
  c/py_buffers.cc
  c/python/xobject.h
  c/set_funcs.cc
  c/str/py_str.cc
  tests/munging/test_assign.py
  tests/munging/test_delete.py
  tests/test_dt.py
  tests/test_dt_create.py
Labels: API change

#1916 Ensure python messages are sent under the protection of a mutex
  c/csv/reader.cc
  c/csv/writer.cc
  c/read/parallel_reader.cc
  tests/fread/test_fread_small.py
Labels: bug

#1926 `quoting` parameter in to_csv()
  CHANGELOG.md
  c/frame/to_csv.cc
  c/write/column_builder.cc
  c/write/column_builder.h
  c/write/csv_writer.cc
  c/write/output_options.h
  c/write/value_writer.cc
  c/write/write_manager.cc
  c/write/write_manager.h
  tests/test_tocsv.py
Labels: improve

#1929 Use zero seed in Murmur hash functions
  c/models/column_hasher.cc
  c/models/dt_ftrl.cc
  c/models/murmurhash.cc
  c/models/murmurhash.h
  c/stats.cc
Labels: performance, refactor

#1932 Unstash missing wheel for CI
  ci/Jenkinsfile.groovy
Labels: ITA

#1938 Cast to floats on-the-fly in Aggregator
  c/models/column_convertor.h
  c/progress/progress_bar.cc
Labels: bug, performance

#1939 Ocolumn2
  c/column.cc
  c/column.h
  c/column_bool.cc
  c/column_int.cc
  c/column_pyobj.cc
  c/column_real.cc
  c/column_string.cc
  c/datatable.h
  c/datatablemodule.cc
  c/expr/j_node.cc
  c/expr/repl_node.cc
  c/frame/__getitem__.cc
  c/frame/replace.cc
  c/jay/save_jay.cc
  c/memrange.cc
  c/memrange.h
  c/models/aggregator.cc
  c/models/dt_ftrl.cc
  c/models/py_ftrl.cc
  c/models/py_validator.h
  c/py_buffers.cc
  c/python/string.cc
  c/python/string.h
  c/str/py_str.cc
  c/str/py_str.h
  c/str/split_into_nhot.cc
Labels: refactor

#1940 Removed support for old NFF format
  CHANGELOG.md
  c/column.cc
  c/column.h
  c/column_fw.cc
  c/column_int.cc
  c/column_pyobj.cc
  c/column_string.cc
  c/datatable.h
  c/datatable_load.cc
  c/datatablemodule.cc
  c/datatablemodule.h
  c/expr/expr_reduce.cc
  c/frame/repeat.cc
  c/memrange.cc
  c/memrange.h
  datatable/frame.py
  datatable/nff.py
  tests/test_jay.py
Labels: refactor

#1941 Further OColumn refactoring
  c/column.cc
  c/column.h
  c/column_bool.cc
  c/column_from_pylist.cc
  c/column_fw.cc
  c/column_int.cc
  c/column_pyobj.cc
  c/column_real.cc
  c/column_string.cc
  c/expr/expr_binaryop.cc
  c/expr/expr_column.cc
  c/expr/expr_literal.cc
  c/expr/expr_reduce.cc
  c/expr/expr_str.cc
  c/expr/i_node.cc
  c/expr/j_node.cc
  c/expr/repl_node.cc
  c/expr/virtual_column.cc
  c/frame/__init__.cc
  c/frame/cast.cc
  c/frame/rbind.cc
  c/frame/repeat.cc
  c/frame/replace.cc
  c/models/dt_ftrl.cc
  c/parallel/string_utils.cc
  c/parallel/string_utils.h
  c/py_buffers.cc
  c/rowindex_array.cc
  c/set_funcs.cc
  c/sort.cc
Labels: refactor

#1927 Gzip compression when writing csvs
  CHANGELOG.md
  c/frame/to_csv.cc
  c/write/csv_writer.cc
  c/write/output_options.h
  c/write/write_manager.cc
  c/write/write_manager.h
  c/write/writing_context.cc
  c/write/writing_context.h
  c/write/zlib_writer.h
  ci/setup_utils.py
  setup.py
  tests/test_tocsv.py
Labels: new feature
