Repository h2oai/datatable, pull requests merged in 2019-11, with the labels that each got.

#2141 Make aggregator to work correctly on sparse data
  c/models/aggregator.cc
  tests/models/test_aggregate.py
Labels: bug, test

#2143 Added parameters append= and header= to .to_csv()
  c/frame/to_csv.cc
  c/utils/file.cc
  c/utils/file.h
  c/write/csv_writer.cc
  c/write/write_manager.cc
  c/write/write_manager.h
  c/writebuf.cc
  c/writebuf.h
  docs/changelog/v-0-10-0.rst
  tests/conftest.py
  tests/test_tocsv.py
Labels: improve

#2145 Improvements to DT[i,j]=R functionality
  c/column/const.cc
  c/expr/eval_context.cc
  c/expr/expr.cc
  c/expr/expr.h
  c/expr/head.h
  c/expr/head_frame.cc
  c/expr/head_frame.h
  c/expr/head_func.cc
  c/expr/head_func.h
  c/expr/head_list.cc
  c/expr/head_list.h
  c/expr/head_literal.cc
  c/expr/head_literal.h
  c/expr/head_literal_bool.cc
  c/expr/head_literal_float.cc
  c/expr/head_literal_int.cc
  c/expr/head_literal_none.cc
  c/expr/head_literal_string.cc
  c/expr/j_node.cc
  c/expr/j_node.h
  c/frame/__getitem__.cc
  c/types.cc
  tests/ijby/test-assign-scalar.py
  tests/models/test_ftrl.py
  tests/munging/test_assign.py
Labels: refactor

#2148 Refactoring of UPDATE functionality
  c/column.cc
  c/expr/eval_context.cc
  c/expr/eval_context.h
  c/expr/j_node.cc
  c/expr/j_node.h
  c/expr/repl_node.cc
  c/expr/repl_node.h
  c/frame/__getitem__.cc
  tests/munging/test_assign.py
Labels: DT[i，j，...], refactor

#2149 Restore a support for the negative_class FTRL parameter
  c/models/dt_ftrl.cc
  c/models/dt_ftrl.h
  c/models/dt_ftrl_base.h
  c/models/label_encode.cc
  c/models/label_encode.h
  tests/models/test_ftrl.py
Labels: improve, test

#2150 Add many more tests for assign functionality
  c/expr/eval_context.cc
  c/expr/eval_context.h
  tests/ijby/test-assign-expr.py
  tests/ijby/test-assign-frame.py
  tests/ijby/test-assign-scalar.py
  tests/ijby/test-assign.py
  tests/munging/test_assign.py
  tests/random_attack.py
Labels: test

#2152 Fix invalid stype downcast when assigning to a subframe
  c/expr/eval_context.cc
  tests/ijby/test-assign-frame.py
Labels: DT[i，j，...]

#2156 update() function
  c/datatablemodule.cc
  c/expr/eval_context.cc
  c/expr/expr.h
  c/expr/py_update.cc
  c/expr/py_update.h
  c/frame/__init__.cc
  c/python/args.cc
  c/python/args.h
  c/python/obj.cc
  c/python/obj.h
  datatable/__init__.py
  docs/changelog/v-0-10-0.rst
  tests/ijby/test-update.py
Labels: DT[i，j，...], new feature

#2159 Allow mixing grouped and non-grouped expressions in DT[i,j]
  c/column.cc
  c/column.h
  c/column/const.cc
  c/expr/eval_context.cc
  c/expr/eval_context.h
  c/expr/head_frame.cc
  c/expr/workframe.cc
  c/groupby.h
  tests/ijby/test-assign-expr.py
  tests/ijby/test-assign-scalar.py
  tests/ijby/test-assign.py
  tests/ijby/test-update.py
Labels: DT[i，j，...]

#2162 Improve FTRL interactions handling
  c/frame/names.cc
  c/models/dt_ftrl.cc
  c/models/py_ftrl.cc
  c/models/py_ftrl.h
  c/python/tuple.cc
  c/python/tuple.h
  tests/models/test_ftrl.py
Labels: bug, improve, test

#2175 Expr cleanup
  c/datatablemodule.cc
  c/expr/by_node.cc
  c/expr/by_node.h
  c/expr/collist.cc
  c/expr/collist.h
  c/expr/declarations.h
  c/expr/eval_context.cc
  c/expr/eval_context.h
  c/expr/expr.cc
  c/expr/expr.h
  c/expr/expr_binaryop.cc
  c/expr/expr_binaryop.h
  c/expr/expr_cast.cc
  c/expr/expr_column.cc
  c/expr/expr_column.h
  c/expr/expr_columnset.cc
  c/expr/expr_columnset.h
  c/expr/expr_literal.cc
  c/expr/expr_literal.h
  c/expr/expr_reduce.cc
  c/expr/expr_reduce.h
  c/expr/expr_str.cc
  c/expr/expr_str.h
  c/expr/expr_unaryop.cc
  c/expr/expr_unaryop.h
  c/expr/j_node.cc
  c/expr/j_node.h
  c/expr/join_node.h
  c/expr/py_join.cc
  c/expr/py_join.h
  c/frame/__getitem__.cc
  c/frame/cast.cc
  c/python/obj.cc
  c/python/obj.h
  tests/test_dt_create.py
Labels: DT[i，j，...], refactor

#2176 Added ability to select a specific row in each group
  c/expr/head_literal_int.cc
  docs/changelog/v-0-10-0.rst
  tests/test-groups.py
Labels: DT[i，j，...], new feature

#2168 Improve Aggregator performance and progress reporting, minor progress bar fix
  c/models/aggregator.cc
  c/models/aggregator.h
  c/progress/progress_bar.cc
Labels: bug, improve

#2177 Expand use of range objects in DT[i,j]
  c/expr/head_literal_range.cc
  docs/changelog/v-0-10-0.rst
  tests/ijby/test-assign-scalar.py
Labels: new feature

#2180 Make the difference between .model_type and .model_type_trained more clear on FTRL docs
  c/models/py_ftrl.cc
Labels: documentation, improve

#2178 Assign type in DT[i,j]
  c/expr/declarations.h
  c/expr/eval_context.cc
  c/expr/expr.cc
  c/expr/expr.h
  c/expr/head.h
  c/expr/head_frame.cc
  c/expr/head_frame.h
  c/expr/head_func.cc
  c/expr/head_func.h
  c/expr/head_list.cc
  c/expr/head_list.h
  c/expr/head_literal.cc
  c/expr/head_literal.h
  c/expr/head_literal_bool.cc
  c/expr/head_literal_float.cc
  c/expr/head_literal_int.cc
  c/expr/head_literal_none.cc
  c/expr/head_literal_string.cc
  c/expr/head_literal_type.cc
  c/frame/__getitem__.cc
  docs/changelog/v-0-10-0.rst
  tests/ijby/test-assign-scalar.py
Labels: DT[i，j，...], new feature

#2181 Implement deep-copy functionality
  c/column.cc
  c/column.h
  c/column/sentinel_str.cc
  c/datatable.cc
  c/datatable.h
  c/frame/integrity_check.cc
  c/frame/py_frame.cc
  c/frame/py_frame.h
  c/jay/open_jay.cc
  c/jay/save_jay.cc
  c/stats.cc
  c/stats.h
  datatable/__init__.py
  docs/changelog/v-0-10-0.rst
  tests/random_attack.py
  tests/test_dt.py
Labels: new feature

#2185 export_names() now returns column exprs
  c/frame/py_frame.cc
  c/frame/py_frame.h
  docs/changelog/v-0-10-0.rst
  docs/f-expressions.rst
  tests/test_dt.py
Labels: API change, improve

#2186 Implement functions cov() and corr()
  c/expr/eval_context.cc
  c/expr/head_func.cc
  c/expr/head_reduce.h
  c/expr/head_reduce_binary.cc
  c/expr/op.h
  datatable/__init__.py
  datatable/expr/__init__.py
  datatable/expr/expr.py
  datatable/expr/reduce.py
  docs/changelog/v-0-10-0.rst
  tests/test_reduce.py
Labels: new feature

#2171 [CI] Update PPC64 build image
  Makefile
Labels: ITA

#2189 Minor cleanup of EvalContext object
  c/expr/eval_context.cc
  c/expr/eval_context.h
  c/frame/__getitem__.cc
  c/sort.cc
Labels: refactor

#2190 Make use of NThreads class in parallel_region
  c/frame/join.cc
  c/models/aggregator.cc
  c/models/dt_ftrl.cc
  c/parallel/api.h
  c/parallel/parallel_for_static.h
  c/parallel/parallel_region.cc
  c/progress/ztest_progress.cc
  c/sort.cc
  c/str/split_into_nhot.cc
Labels: improve

#2191 Binary operators implemented using virtual columns
  c/column.cc
  c/column.h
  c/column/column_impl.cc
  c/column/column_impl.h
  c/column/func_binary.h
  c/column/func_unary.h
  c/column/latent.cc
  c/column/latent.h
  c/column/nafilled.h
  c/column/repeated.cc
  c/column/repeated.h
  c/column/view.cc
  c/column/view.h
  c/datatablemodule.cc
  c/expr/expr_binaryop.cc
  c/expr/expr_binaryop.h
  c/expr/fbinary/arithmetic.cc
  c/expr/fbinary/bimaker.cc
  c/expr/fbinary/bimaker.h
  c/expr/fbinary/bimaker_impl.h
  c/expr/fbinary/bitwise.cc
  c/expr/fbinary/relational.cc
  c/expr/head_func_binary.cc
  c/rowindex_array.cc
  c/stats.cc
  c/types.h
  tests/munging/test_dt_cols.py
  tests/test_dt_expr.py
  tests/test_types.py
Labels: API change, improve, refactor

#2193 Simplify the way Aggregator and FTRL calculate number of threads for parallelization
  c/models/aggregator.cc
  c/models/aggregator.h
  c/models/dt_ftrl.cc
  c/models/dt_ftrl_base.cc
  c/models/dt_ftrl_base.h
  c/models/label_encode.h
  c/models/utils.h
  c/parallel/api_primitives.cc
  c/parallel/api_primitives.h
  c/parallel/string_utils.cc
  c/parallel/string_utils.h
Labels: documentation, improve, refactor

#2194 Unary functions refactor
  c/column.cc
  c/column/func_unary.h
  c/datatablemodule.cc
  c/datatablemodule.h
  c/expr/expr_unaryop.cc
  c/expr/expr_unaryop.h
  c/expr/fbinary/arithmetic.cc
  c/expr/fbinary/bimaker.cc
  c/expr/fbinary/math.cc
  c/expr/funary/basic.cc
  c/expr/funary/exponential.cc
  c/expr/funary/floating.cc
  c/expr/funary/hyperbolic.cc
  c/expr/funary/pyfn.cc
  c/expr/funary/pyfn.h
  c/expr/funary/special.cc
  c/expr/funary/trigonometric.cc
  c/expr/funary/umaker.cc
  c/expr/funary/umaker.h
  c/expr/funary/umaker_impl.h
  c/expr/head_func.cc
  c/expr/head_func_unary.cc
  c/expr/op.h
  datatable/expr/expr.py
  datatable/math.py
  docs/api/math.rst
  tests/ijby/test-func-unary.py
Labels: refactor

#2195 Row-functions
  c/column/func_nary.h
  c/datatablemodule.cc
  c/datatablemodule.h
  c/expr/fnary/fnary.cc
  c/expr/fnary/fnary.h
  c/expr/fnary/pyfn.cc
  c/expr/fnary/rowall.cc
  c/expr/fnary/rowany.cc
  c/expr/fnary/rowcount.cc
  c/expr/fnary/rowfirstlast.cc
  c/expr/fnary/rowmean.cc
  c/expr/fnary/rowminmax.cc
  c/expr/fnary/rowsd.cc
  c/expr/fnary/rowsum.cc
  c/expr/head_func.cc
  c/expr/head_func.h
  c/expr/head_func_nary.cc
  c/expr/op.h
  c/py_buffers.cc
  c/types.cc
  c/types.h
  datatable/__init__.py
  docs/changelog/v-0-10-0.rst
  tests/ijby/test-rowwise.py
Labels: new feature

#2196 Prevent fread emitting message about BufferedIO file not closed
  datatable/fread.py
Labels: fread, test

#2198 Fix test_horizontal_elision on Travis
  .travis.yml
  tests/frame/test-repr-text.py
Labels: test

#2200 Add <algorithm> includes
  c/frame/repr/text_column.cc
  c/models/dt_ftrl.cc
  c/progress/progress_bar.cc
  c/python/args.cc
  c/writebuf.cc
Labels: ITA

#2199 Make module name be compatible with PyInit__datatable
  Makefile
  c/column/sentinel_fw.cc
  setup.py
Labels: ITA

#2197 Fix segfault when C++ tests were called with missing arguments
  c/python/args.cc
  c/python/args.h
  c/ztest.cc
  c/ztest.h
  tests/test_parallel.py
Labels: segfault, test

#2204 Use portable implementation of std::isfinite in FTRL
  c/column/func_unary.h
  c/models/dt_ftrl.cc
  c/models/utils.h
  c/stats.cc
Labels: ITA

#2201 Add structure tag definitions
  c/datatable.cc
  c/frame/repr/widget.cc
  c/python/xobject.cc
  c/python/xobject.h
Labels: ITA

#2203 Move monitor thread from idle_job to thread_pool
  c/parallel/monitor_thread.cc
  c/parallel/parallel_for_static.h
  c/parallel/thread_pool.cc
  c/parallel/thread_pool.h
  c/parallel/thread_worker.cc
  c/parallel/thread_worker.h
Labels: ITA, refactor

#2206 New function: shift()
  c/column/shift.h
  c/datatablemodule.cc
  c/datatablemodule.h
  c/expr/head_func.cc
  c/expr/head_func.h
  c/expr/head_func_shift.cc
  c/expr/op.h
  c/expr/workframe.cc
  c/expr/workframe.h
  datatable/__init__.py
  datatable/expr/expr.py
  datatable/math.py
  docs/changelog/v-0-10-0.rst
  tests/ijby/test-shift.py
Labels: new feature

#2205 Do not use designated struct initializers
  c/csv/reader_fread.cc
  c/python/obj.cc
Labels: ITA

#2207 Do not use stdin and stdout as variable or function names
  c/progress/_options.cc
  c/progress/progress_bar.cc
  c/python/arg.cc
  c/python/obj.cc
  c/python/obj.h
  c/utils/terminal/terminal.cc
Labels: ITA

#2211 Fix an internal bug in umaker/bimaker
  c/expr/fbinary/bimaker.cc
  c/expr/funary/umaker.cc
Labels: segfault

#2212 Add Windows specific function implementations and do not use incompatible pragmas
  c/csv/reader.cc
  c/frame/replace.cc
  c/lib/flatbuffers/flatbuffers.h
  c/python/xobject.h
  c/read/constants.cc
  c/utils/file.cc
  c/utils/macros.h
  c/utils/misc.cc
Labels: ITA

#2214 Update FTRL and Installation docs
  docs/ftrl.rst
  docs/install.rst
Labels: documentation
