Repository h2oai/datatable, pull requests merged in 2019-03, with the labels that each got.

#1707 Frame.materialize() method moved to C++
  c/column.cc
  c/column.h
  c/column_fw.cc
  c/column_pyobj.cc
  c/column_string.cc
  c/datatable.cc
  c/datatable.h
  c/expr/binaryop.cc
  c/expr/reduceop.cc
  c/expr/unaryop.cc
  c/frame/join.cc
  c/frame/key.cc
  c/frame/py_frame.cc
  c/frame/py_frame.h
  c/frame/rbind.cc
  c/jay/save_jay.cc
  c/py_buffers.cc
  c/py_datatable.cc
  c/py_datatable.h
  c/rowindex_array.cc
  c/set_funcs.cc
  c/sort.cc
  datatable/frame.py
  tests/test_dt.py
Labels: refactor

#1708 Eliminate property Frame.internal.isview
  c/py_datatable.cc
  c/py_datatable.h
  tests/__init__.py
  tests/munging/test_dt_cols.py
  tests/munging/test_dt_rows.py
  tests/test_dt.py
  tests/test_dt_sort.py
  tests/test_groups.py
  tests/test_keys.py
  tests/test_nff.py
Labels: refactor

#1709 Replace Frame.internal.check() with a function
  c/column.cc
  c/column_bool.cc
  c/column_string.cc
  c/datatable.cc
  c/datatablemodule.cc
  c/frame/integrity_check.cc
  c/frame/py_frame.h
  c/py_datatable.cc
  c/py_datatable.h
  datatable/internal.py
  tests/__init__.py
  tests/fread/test_fread_api.py
  tests/fread/test_fread_detect.py
  tests/fread/test_fread_issues.py
  tests/fread/test_fread_large.py
  tests/fread/test_fread_random.py
  tests/fread/test_fread_small.py
  tests/models/test_aggregate.py
  tests/models/test_ftrl.py
  tests/munging/test_assign.py
  tests/munging/test_cast.py
  tests/munging/test_delete.py
  tests/munging/test_dt_cbind.py
  tests/munging/test_dt_cols.py
  tests/munging/test_dt_combo.py
  tests/munging/test_dt_rows.py
  tests/munging/test_rbind.py
  tests/munging/test_replace.py
  tests/munging/test_str.py
  tests/random_attack.py
  tests/test_dt.py
  tests/test_dt_create.py
  tests/test_dt_expr.py
  tests/test_dt_options.py
  tests/test_dt_sort.py
  tests/test_dt_stats.py
  tests/test_groups.py
  tests/test_join.py
  tests/test_keys.py
  tests/test_nff.py
  tests/test_reduce.py
  tests/test_sets.py
  tests/test_tocsv.py
Labels: refactor

#1710 Moved Frame.sort() into C++
  c/expr/sort_node.cc
  c/expr/sort_node.h
  c/frame/py_frame.cc
  c/frame/py_frame.h
  c/sort.cc
  datatable/frame.py
Labels: refactor

#1712 Make aggregator working on views
  c/models/column_convertor.h
  tests/models/test_aggregate.py
Labels: bug, test

#1711 FTRL model re-factoring and new capabilities
  CHANGELOG.md
  c/models/aggregator.cc
  c/models/aggregator.h
  c/models/column_convertor.h
  c/models/column_hasher.cc
  c/models/column_hasher.h
  c/models/dt_ftrl.cc
  c/models/dt_ftrl.h
  c/models/dt_ftrl_real.cc
  c/models/dt_ftrl_real.h
  c/models/py_ftrl.cc
  c/models/py_ftrl.h
  c/models/py_validator.h
  c/models/utils.cc
  c/models/utils.h
  c/python/args.cc
  tests/models/test_ftrl.py
Labels: improve, new feature, refactor, test

#1718 Code cleanup in fread
  c/csv/fread.cc
  c/csv/reader.cc
  c/csv/reader_fread.cc
  c/csv/reader_fread.h
  c/csv/reader_parsers.cc
  c/csv/reader_parsers.h
  c/csv/writer.cc
  c/encodings.cc
  c/read/chunk_coordinates.cc
  c/read/chunk_coordinates.h
  c/read/constants.cc
  c/read/constants.h
  c/read/fread/fread_parallel_reader.cc
  c/read/fread/fread_parallel_reader.h
  c/read/fread/fread_thread_context.cc
  c/read/fread/fread_thread_context.h
  c/read/fread/fread_tokenizer.cc
  c/read/fread/fread_tokenizer.h
  c/read/parallel_reader.cc
  c/read/parallel_reader.h
  c/read/thread_context.h
Labels: refactor

#1719 Upgrade the wheel URL in requirements_docs.txt
  requirements_docs.txt
Labels: ITA, documentation

#1721 Upgrade the wheel URL in requirements_docs.txt
  requirements_docs.txt
Labels: bug, documentation

#1724 updating llvm4 to version 7 for travis
  .travis.yml
Labels: ITA

#1722 FTRL algo improvements
  c/models/dt_ftrl.h
  c/models/dt_ftrl_real.cc
  c/models/dt_ftrl_real.h
  c/models/py_ftrl.cc
  c/models/utils.h
  c/str/split_into_nhot.cc
  tests/models/test_ftrl.py
Labels: bug, improve, new feature, refactor

#1723 Allow for arbitrary feature interactions in FTRL algo
  c/models/dt_ftrl.h
  c/models/dt_ftrl_real.cc
  c/models/dt_ftrl_real.h
  c/models/py_ftrl.cc
  c/models/py_ftrl.h
  c/models/utils.h
  docs/ftrl.rst
  tests/models/test_ftrl.py
Labels: improve, new feature, test

#1735 Gcc compilation fixes
  c/models/dt_ftrl_real.cc
  c/models/dt_ftrl_real.h
  c/models/utils.h
Labels: ITA

#1745 Add tests for automatic type detection from python list
  tests/test_dt_create.py
Labels: test

#1725 Minor Aggregator re-factoring and fix
  README.md
  c/models/aggregator.cc
  c/models/aggregator.h
Labels: bug, refactor

#1747 Use static schedule in dt::run_parallel()
  c/utils/parallel.cc
Labels: performance

#1749 Use static schedule for ND aggregation
  README.md
  c/models/aggregator.cc
Labels: performance

#1752 FTRL algo and docs improvements
  c/models/dt_ftrl.h
  c/models/dt_ftrl_real.cc
  c/models/dt_ftrl_real.h
  c/models/py_ftrl.cc
  c/models/py_ftrl.h
  c/models/utils.cc
  c/models/utils.h
  c/str/py_str.cc
  c/str/py_str.h
  c/str/split_into_nhot.cc
  c/utils/parallel.cc
  docs/ftrl.rst
  tests/models/test_ftrl.py
  tests/munging/test_str.py
Labels: bug, documentation, improve, test

#1753 Reimplement dt::run_parallel using the new thread pool
  c/datatablemodule.cc
  c/frame/cast.cc
  c/frame/replace.cc
  c/models/dt_ftrl_real.cc
  c/parallel/api.h
  c/parallel/thread_pool.cc
  c/rowindex.cc
  c/utils/parallel.cc
  c/utils/parallel.h
Labels: refactor
