Repository h2oai/datatable, pull requests merged in 2019-01, with the labels that each got.

#1512 del DT[i, j] operator is now evaluated in C++
  c/column.h
  c/column_fw.cc
  c/column_string.cc
  c/datatable.cc
  c/datatable.h
  c/expr/base_expr.cc
  c/expr/base_expr.h
  c/expr/j_node.cc
  c/expr/j_node.h
  c/expr/join_node.cc
  c/expr/join_node.h
  c/expr/workframe.cc
  c/expr/workframe.h
  c/frame/__getitem__.cc
  c/py_rowindex.cc
  c/rowindex.cc
  c/rowindex.h
  c/rowindex_array.cc
  c/rowindex_impl.h
  c/rowindex_slice.cc
  datatable/graph/__init__.py
  tests/__init__.py
  tests/munging/test_delete.py
  tests/test_dt.py
Labels: refactor

#1514 Add more FTRL tests, some minor adjustments
  AUTHORS.md
  c/extras/hash.h
  tests/extras/test_ftrl.py
Labels: improve, test

#1521 Changelog URLs
  CHANGELOG.md
  ci/README.md
Labels: documentation

#1522 Add support for multinomial regression and linear regression for numerical columns
  c/extras/dt_ftrl.cc
  c/extras/dt_ftrl.h
  c/extras/py_ftrl.cc
  c/extras/py_ftrl.h
  c/python/list.h
  tests/extras/test_ftrl.py
Labels: improve

#1532 Do not allow `None` to be assigned to float FTRL parameters
  c/extras/py_validator.cc
  c/extras/py_validator.h
  tests/extras/test_ftrl.py
Labels: bug

#1553 Traverse exemplars in a quasi-random order in ND aggregator
  c/extras/aggregator.cc
  c/extras/aggregator.h
Labels: improve

#1560 Implement `m__dealloc__` to delete models and labels
  c/extras/py_ftrl.cc
  c/extras/py_ftrl.h
Labels: bug

#1571 Added many tests for DT[i,j]=... assignment
  c/column.cc
  c/expr/repl_node.cc
  c/frame/repeat.cc
  tests/munging/test_assign.py
Labels: bug, improve

#1583 FTRL API adjustments
  c/extras/dt_ftrl.cc
  c/extras/dt_ftrl.h
  c/extras/py_ftrl.cc
  c/extras/py_ftrl.h
  docs/ftrl.rst
  tests/extras/test_ftrl.py
Labels: improve

#1589 Adjust FTRL feature importance tests
  c/extras/py_ftrl.cc
  tests/extras/test_ftrl.py
Labels: test

#1598 Do not segfault when pickling an empty FTRL model
  c/extras/py_ftrl.cc
  tests/extras/test_ftrl.py
Labels: bug, segfault

#1609 Added new random attack methods
  tests/munging/test_rbind.py
  tests/random_attack.py
Labels: test

#1612 Fix an issue when feature_names goes out of sync with the iterations parameter
  c/extras/py_ftrl.cc
  c/extras/py_ftrl.h
  docs/ftrl.rst
  tests/extras/test_ftrl.py
Labels: bug

#1617 Refactor sorting/grouping and RowIndex usage in Aggregator
  c/extras/aggregator.cc
  c/extras/aggregator.h
  docs/ftrl.rst
  tests/extras/test_aggregate.py
Labels: documentation, refactor
