Repository h2oai/datatable, pull requests merged in 2019-04, with the labels that each got.

#1754 Do not use #pragma omp critical in TRACK/UNTRACK functions
  c/datatablemodule.cc
Labels: refactor

#1756 Clean up #pragma omp uses in column_*.cc
  c/column_fw.cc
  c/column_string.cc
Labels: refactor

#1760 Return loss, when validation dataset is provided to FTRL algo
  c/models/dt_ftrl.h
  c/models/dt_ftrl_real.cc
  c/models/dt_ftrl_real.h
  c/models/py_ftrl.cc
  docs/ftrl.rst
  tests/models/test_ftrl.py
Labels: improve

#1761 Remove unused constructors in ArrayRowIndexImpl
  c/rowindex.cc
  c/rowindex.h
  c/rowindex_array.cc
  c/rowindex_impl.h
Labels: refactor

#1768 Replace openmp with dt::parallel in split_into_nhot.cc
  c/str/split_into_nhot.cc
Labels: refactor

#1771 Changes to dt::parallel_* functions
  c/column_fw.cc
  c/column_string.cc
  c/datatablemodule.cc
  c/frame/cast.cc
  c/frame/replace.cc
  c/frame/to_numpy.cc
  c/models/dt_ftrl_real.cc
  c/parallel/api.h
  c/parallel/atomic_test.cc
  c/parallel/thread_scheduler.cc
  c/parallel/thread_task.cc
  c/parallel/thread_task.h
  c/rowindex.cc
  c/rowindex_array.cc
  c/stats.cc
  c/str/split_into_nhot.cc
  c/utils/parallel.cc
  c/utils/parallel.h
Labels: refactor

#1774 Clean up few more cases of `#pragma omp` uses
  c/expr/reduce.cc
  c/expr/string_expr.cc
  c/frame/join.cc
  c/parallel/parallel_for_test.cc
Labels: refactor

#1770 Add mantissa_nbits parameter to FTRL algo
  c/models/aggregator.cc
  c/models/aggregator.h
  c/models/column_convertor.h
  c/models/column_hasher.cc
  c/models/column_hasher.h
  c/models/dt_ftrl.cc
  c/models/dt_ftrl.h
  c/models/dt_ftrl_real.cc
  c/models/dt_ftrl_real.h
  c/models/murmurhash.cc
  c/models/py_ftrl.cc
  c/models/py_ftrl.h
  c/models/py_validator.cc
  c/models/py_validator.h
  c/models/utils.cc
  c/models/utils.h
  docs/ftrl.rst
  tests/models/test_ftrl.py
Labels: new feature

#1784 Implement a spin_mutex class
  c/parallel/parallel_for_ordered.cc
  c/parallel/spin_mutex.h
Labels: improve, performance

#1788 Add Frame.__str__() method
  CHANGELOG.md
  c/frame/__repr__.cc
  c/frame/py_frame.h
  c/py_rowindex.cc
  c/python/ext_type.h
  datatable/utils/terminal.py
  datatable/widget.py
  tests/test_dt.py
Labels: new feature

#1791 Fix dt::barrier(), add tests
  Makefile
  c/parallel/thread_team.cc
  c/parallel/ztest_atomic.cc
  c/parallel/ztest_barrier.cc
  c/ztest.cc
  c/ztest.h
  tests/test_dt.py
Labels: ITA, bug, test

#1794 Adjust FTRL usage of thread pool, improve performance and re-factoring
  c/models/dt_ftrl.cc
  c/models/dt_ftrl.h
  c/models/dt_ftrl_base.cc
  c/models/dt_ftrl_base.h
  c/models/dt_ftrl_real.cc
  c/models/dt_ftrl_real.h
  c/models/py_ftrl.cc
  c/models/py_ftrl.h
Labels: performance, refactor

#1796 Fix segfault in onamedtuple, add test, minor cosmetics in FTRL
  c/models/py_ftrl.cc
  c/python/namedtuple.cc
  tests/models/test_ftrl.py
Labels: segfault, test

#1797 Add nthreads parameter to dt::parallel_for_static and dt::parallel_for_dynamic
  c/models/dt_ftrl.cc
  c/parallel/api.h
  c/parallel/parallel_for_dynamic.cc
  c/parallel/parallel_for_static.cc
  c/parallel/thread_pool.cc
Labels: improve

#1809 Include debugging information in produced binaries
  ci/setup_utils.py
Labels: ITA

#1812 Fix nthreads usage in parallel_for_dynamic, add C++ tests
  c/parallel/parallel_for_dynamic.cc
  c/parallel/parallel_for_static.cc
  c/parallel/ztest_parallel_for.cc
  c/ztest.cc
  c/ztest.h
  tests/test_dt.py
Labels: bug, test

#1814 Upgrade of progress bar functionality
  c/csv/fread.cc
  c/csv/reader.cc
  c/csv/reader.h
  c/csv/reader_fread.cc
  c/csv/reader_fread.h
  c/csv/writer.cc
  c/datatablemodule.cc
  c/options.cc
  c/options.h
  c/parallel/parallel_for_ordered.cc
  c/parallel/progress.cc
  c/parallel/thread_team.h
  c/parallel/thread_worker.cc
  c/parallel/thread_worker.h
  c/progress/_options.cc
  c/progress/_options.h
  c/progress/manager.cc
  c/progress/manager.h
  c/progress/progress_bar.cc
  c/progress/progress_bar.h
  c/progress/work.cc
  c/progress/work.h
  c/python/arg.cc
  c/python/obj.cc
  c/python/obj.h
  c/read/fread/fread_thread_context.cc
  c/read/parallel_reader.cc
  c/utils/assert.h
  c/utils/exceptions.cc
  c/utils/exceptions.h
  tests/conftest.py
Labels: improve

#1815 Fix attempt for parallel dynamic loop
  c/parallel/api.h
  c/parallel/parallel_for_dynamic.cc
  c/parallel/parallel_for_static.cc
  c/parallel/thread_scheduler.h
  c/parallel/thread_team.cc
  c/parallel/thread_team.h
  c/utils/function.h
  c/utils/macros.h
Labels: bug

#1828 Update installation instructions
  docs/install.rst
Labels: ITA, documentation

#1833 Add loss averaging parameter to FTRL algo
  c/models/dt_ftrl.cc
  c/models/dt_ftrl.h
  c/models/dt_ftrl_base.h
  c/models/py_ftrl.cc
  docs/ftrl.rst
  tests/models/test_ftrl.py
Labels: improve, test
