Repository h2oai/datatable, pull requests merged in 2019-02, with the labels that each got.

#1629 #952 latest stable artifacts generation
  ci/Jenkinsfile.groovy
Labels: ITA

#1632 Fix multiple warnings reported by Codacy
  .github/CONTRIBUTING.md
  AUTHORS.md
  README.md
  c/column_from_pylist.cc
  c/column_string.cc
  c/csv/fread.cc
  c/csv/py_csv.cc
  c/csv/reader.cc
  c/csv/reader.h
  c/csv/reader_arff.cc
  c/csv/reader_arff.h
  c/csv/reader_fread.cc
  c/csv/reader_fread.h
  c/csv/reader_parsers.cc
  c/csv/writer.cc
  c/encodings.cc
  c/expr/base_expr.cc
  c/expr/collist.cc
  c/expr/i_node.cc
  c/expr/j_node.cc
  c/expr/repl_node.cc
  c/extras/dt_ftrl.cc
  c/frame/_repr_html_.cc
  c/frame/join.cc
  c/frame/names.cc
  c/frame/replace.cc
  c/memrange.cc
  c/rowindex.cc
  c/rowindex_impl.h
  c/sort.cc
  c/stats.cc
  c/types.cc
  c/utils/parallel.cc
  datatable/__init__.py
  datatable/fread.py
  datatable/internal.py
  datatable/xls.py
  tests/__init__.py
  tests/conftest.py
  tests/extras/test_aggregate.py
  tests/fread/test_fread_api.py
  tests/fread/test_fread_large.py
  tests/fread/test_fread_random.py
  tests/fread/test_xls.py
  tests/random_attack.py
  tests/test_dt.py
  tests/test_dt_expr.py
  tests/test_dt_options.py
  tests/test_dt_sort.py
  tests/test_groups.py
  tests/test_tocsv.py
Labels: refactor

#1630 Move hashing functionality from header to source file, fix `nbins` setter bug, add a test
  c/extras/hash.cc
  c/extras/hash.h
  c/extras/py_ftrl.cc
  c/sort_insert.cc
  docs/ftrl.rst
  tests/extras/test_ftrl.py
Labels: bug, documentation, refactor

#1638 Remove core pyColumnSet class
  c/columnset.cc
  c/columnset.h
  c/datatablemodule.cc
  c/py_columnset.cc
  c/py_columnset.h
  c/py_datatable.cc
Labels: refactor

#1642 Add a test case from issue #h2oai/7014
  tests/test_dt_sort.py
Labels: test

#1647 Fix feature importance FTRL tests
  tests/extras/test_ftrl.py
Labels: bug, test

#1648 Cleanup of the internal py_DataTable class
  CHANGELOG.md
  c/datatable.h
  c/datatablemodule.cc
  c/py_datatable.cc
  c/py_datatable.h
  c/py_groupby.cc
  c/py_groupby.h
  c/python/obj.cc
  c/python/obj.h
  c/sort.cc
  datatable/frame.py
  tests/fread/test_fread_small.py
  tests/test_dt.py
  tests/test_dt_create.py
  tests/test_dt_stats.py
  tests/test_groups.py
Labels: refactor

#1650 Convert pyRowindex class into new-style (based on ExtType)
  c/api.cc
  c/datatablemodule.cc
  c/frame/join.cc
  c/py_column.cc
  c/py_column.h
  c/py_rowindex.cc
  c/py_rowindex.h
  c/python/obj.cc
  c/python/obj.h
  tests/extras/test_aggregate.py
  tests/test_dt.py
Labels: refactor

#1651 Disable parallelization `Aggregator::generate_pmatrix`
  c/extras/aggregator.cc
Labels: bug, test

#1652 Multiple cleanups of obsolete code in datatable
  c/datatablemodule.cc
  c/py_rowindex.cc
  c/py_rowindex.h
  datatable/expr/__init__.py
  datatable/expr/base_expr.py
  datatable/expr/binary_expr.py
  datatable/expr/cast_expr.py
  datatable/expr/column_expr.py
  datatable/expr/isna_expr.py
  datatable/expr/literal_expr.py
  datatable/expr/mean_expr.py
  datatable/expr/minmax_expr.py
  datatable/expr/reduce_expr.py
  datatable/expr/relop_expr.py
  datatable/expr/sd_expr.py
  datatable/expr/unary_expr.py
  datatable/frame.py
  datatable/internal.py
  tests/extras/test_aggregate.py
  tests/munging/test_dt_combo.py
  tests/munging/test_dt_rows.py
  tests/test_dt.py
Labels: refactor

#1655 Create mechanism for defining python interface methods more robustly
  c/frame/py_frame.cc
  c/frame/py_frame.h
  c/python/arg.cc
  c/python/arg.h
  c/python/args.cc
  c/python/args.h
  c/python/ext_type.h
Labels: refactor

#1656 Update functions in `py::Frame`
  c/frame/__init__.cc
  c/frame/_repr_html_.cc
  c/frame/cbind.cc
  c/frame/names.cc
  c/frame/py_frame.cc
  c/frame/py_frame.h
  c/frame/replace.cc
  c/frame/to_numpy.cc
  c/frame/to_python.cc
  c/python/args.h
Labels: refactor

#1657 Simplify ExtType<T>::Methods class
  c/extras/py_ftrl.cc
  c/extras/py_ftrl.h
  c/py_rowindex.cc
  c/py_rowindex.h
  c/python/ext_type.h
Labels: refactor

#1658 Getters / setters revamp
  c/expr/by_node.cc
  c/expr/join_node.cc
  c/expr/sort_node.cc
  c/extras/py_ftrl.cc
  c/frame/key.cc
  c/frame/names.cc
  c/frame/py_frame.cc
  c/frame/py_frame.h
  c/py_rowindex.cc
  c/python/args.h
  c/python/ext_type.h
Labels: refactor

#1660 Update internal class PKArgs and ExtModule
  c/datatablemodule.cc
  c/extras/aggregator.cc
  c/extras/kfold.cc
  c/frame/repeat.cc
  c/options.cc
  c/py_column.cc
  c/py_column.h
  c/python/args.cc
  c/python/args.h
  c/python/ext_module.h
  c/python/ext_type.h
  c/set_funcs.cc
  c/str/py_str.cc
  c/ztest.cc
Labels: refactor

#1661 Clean up of class DatatableModule
  c/datatablemodule.cc
  c/datatablemodule.h
  c/py_column.cc
  c/py_column.h
  c/python/arg.cc
  c/python/args.cc
  c/python/args.h
  datatable/frame.py
  datatable/fread.py
  datatable/internal.py
  datatable/types.py
  datatable/utils/typechecks.py
Labels: refactor

#1664 Refactor
  c/csv/py_csv.cc
  c/csv/py_csv.h
  c/csv/reader_fread.h
  c/datatable_load.cc
  c/datatablemodule.cc
  c/datatablemodule.h
  c/jay/open_jay.cc
  c/py_buffers.cc
  c/py_column.cc
  c/py_column.h
  c/py_datatable.cc
  c/py_datatable.h
  c/python/arg.cc
  c/python/arg.h
  c/python/obj.h
  datatable/frame.py
  datatable/nff.py
  tests/test_dt.py
Labels: refactor

#1666 Aggregator re-factoring, bug fixes and tests
  c/column.h
  c/datatable.h
  c/datatablemodule.cc
  c/datatablemodule.h
  c/expr/repl_node.cc
  c/extras/aggregator.h
  c/models/aggregator.cc
  c/models/aggregator.h
  c/models/column_convertor.h
  c/models/dt_ftrl.cc
  c/models/dt_ftrl.h
  c/models/hash.cc
  c/models/hash.h
  c/models/kfold.cc
  c/models/murmurhash.cc
  c/models/murmurhash.h
  c/models/py_ftrl.cc
  c/models/py_ftrl.h
  c/models/py_validator.cc
  c/models/py_validator.h
  c/models/utils.cc
  c/models/utils.h
  datatable/extras/__init__.py
  datatable/extras/aggregate.py
  datatable/models.py
  tests/extras/test_aggregate.py
  tests/models/test_aggregate.py
  tests/models/test_ftrl.py
Labels: bug, refactor, test

#1671 Convert Frame.to_pandas() into C++
  c/datatablemodule.cc
  c/datatablemodule.h
  c/frame/py_frame.cc
  c/frame/py_frame.h
  c/frame/to_numpy.cc
  c/py_buffers.cc
  c/py_datatable.cc
  c/py_datatable.h
  c/python/arg.cc
  c/python/arg.h
  c/python/args.h
  datatable/frame.py
Labels: refactor

#1670 Fix `aggregate(...)` signature in help
  c/models/aggregator.cc
Labels: documentation

#1679 All Frame.repr functions moved to C++
  c/frame/__repr__.cc
  c/frame/py_frame.cc
  c/frame/py_frame.h
  datatable/__init__.py
  datatable/frame.py
  datatable/utils/terminal.py
Labels: refactor

#1681 Frame stats functions were moved to C++
  c/column.cc
  c/column.h
  c/column_bool.cc
  c/column_int.cc
  c/column_real.cc
  c/column_string.cc
  c/datatable.cc
  c/datatable.h
  c/frame/py_frame.cc
  c/frame/py_frame.h
  c/frame/stats.cc
  c/jay/open_jay.cc
  c/jay/save_jay.cc
  c/memrange.h
  c/py_datatable.cc
  c/py_datatable.h
  c/py_types.cc
  c/py_types.h
  c/python/args.h
  c/stats.cc
  c/stats.h
  datatable/frame.py
  tests/test_dt_stats.py
Labels: refactor

#1682 Simplify the way how otuple constructor can be used
  c/datatablemodule.cc
  c/expr/by_node.cc
  c/expr/i_node.cc
  c/frame/__init__.cc
  c/frame/__repr__.cc
  c/frame/py_frame.cc
  c/frame/py_frame.h
  c/frame/to_numpy.cc
  c/models/aggregator.h
  c/models/kfold.cc
  c/models/py_ftrl.cc
  c/python/namedtuple.cc
  c/python/obj.cc
  c/python/range.cc
  c/python/tuple.cc
  c/python/tuple.h
Labels: refactor

#1683 Convert csv writing code to C++
  c/csv/py_csv.cc
  c/csv/writer.cc
  c/csv/writer.h
  c/datatablemodule.cc
  c/frame/py_frame.cc
  c/frame/py_frame.h
  c/frame/to_csv.cc
  c/python/arg.h
  c/python/obj.cc
  c/python/obj.h
  c/utils/logger.h
  datatable/__init__.py
  datatable/csv.py
  datatable/frame.py
Labels: refactor

#1685 Rbind refactoring
  CHANGELOG.md
  c/datatable.h
  c/datatable_rbind.cc
  c/datatablemodule.cc
  c/datatablemodule.h
  c/frame/cbind.cc
  c/frame/py_frame.cc
  c/frame/py_frame.h
  c/frame/rbind.cc
  c/frame/to_python.cc
  c/py_datatable.cc
  c/py_datatable.h
  datatable/__init__.py
  datatable/dt_append.py
  datatable/frame.py
  tests/munging/test_rbind.py
Labels: refactor

#1686 to_jay()
  CHANGELOG.md
  c/datatablemodule.cc
  c/datatablemodule.h
  c/frame/py_frame.cc
  c/frame/py_frame.h
  c/jay/save_jay.cc
  c/py_datatable.cc
  c/py_datatable.h
  c/writebuf.h
  datatable/__init__.py
  datatable/expr/isna_expr.py
  datatable/frame.py
  datatable/nff.py
  datatable/utils/typechecks.py
  docs/quick-start.rst
  docs/using-datatable.rst
  tests/munging/test_dt_rows.py
  tests/munging/test_rbind.py
  tests/test_dt_sort.py
  tests/test_keys.py
  tests/test_nff.py
Labels: refactor

#1690 Rbind move
  c/column.cc
  c/column_fw.cc
  c/column_pyobj.cc
  c/column_string.cc
  c/csv/py_csv.cc
  c/datatable_load.cc
  c/datatablemodule.cc
  c/datatablemodule.h
  c/frame/cbind.cc
  c/frame/join.cc
  c/frame/rbind.cc
  c/frame/repeat.cc
  c/jay/open_jay.cc
  c/models/aggregator.cc
  c/models/kfold.cc
  c/options.cc
  c/py_buffers.cc
  c/set_funcs.cc
  c/str/py_str.cc
  c/ztest.cc
Labels: refactor
