Repository h2oai/datatable, pull requests merged in 2020-09, with the labels that each got.

#2594 Convert FTRL docs to xfunction/xclass format
  docs/api/models/Ftrl/__init__.rst
  docs/api/models/Ftrl/alpha.rst
  docs/api/models/Ftrl/beta.rst
  docs/api/models/Ftrl/colname_hashes.rst
  docs/api/models/Ftrl/colnames.rst
  docs/api/models/Ftrl/double_precision.rst
  docs/api/models/Ftrl/feature_importances.rst
  docs/api/models/Ftrl/fit.rst
  docs/api/models/Ftrl/interactions.rst
  docs/api/models/Ftrl/labels.rst
  docs/api/models/Ftrl/lambda1.rst
  docs/api/models/Ftrl/lambda2.rst
  docs/api/models/Ftrl/mantissa_nbits.rst
  docs/api/models/Ftrl/model.rst
  docs/api/models/Ftrl/model_type.rst
  docs/api/models/Ftrl/model_type_trained.rst
  docs/api/models/Ftrl/nbins.rst
  docs/api/models/Ftrl/negative_class.rst
  docs/api/models/Ftrl/nepochs.rst
  docs/api/models/Ftrl/params.rst
  docs/api/models/Ftrl/predict.rst
  docs/api/models/Ftrl/reset.rst
  docs/api/models/ftrl.rst
  src/core/models/py_ftrl.cc
  tests/expr/fbinary/test-pow.py
  tests/models/test-ftrl.py
Labels: documentation, test

#2595 Documenting Frame
  docs/_static/xfunction.css
  docs/api/dt/by.rst
  docs/api/dt/cbind.rst
  docs/api/dt/cut.rst
  docs/api/dt/fread.rst
  docs/api/dt/ifelse.rst
  docs/api/dt/iread.rst
  docs/api/dt/qcut.rst
  docs/api/dt/rbind.rst
  docs/api/dt/repeat.rst
  docs/api/dt/shift.rst
  docs/api/dt/sort.rst
  docs/api/dt/update.rst
  docs/api/fexpr/__add__.rst
  docs/api/frame.rst
  docs/api/frame/__delitem__.rst
  docs/api/frame/__getitem__.rst
  docs/api/frame/__iter__.rst
  docs/api/frame/__len__.rst
  docs/api/frame/__repr__.rst
  docs/api/frame/__reversed__.rst
  docs/api/frame/__setitem__.rst
  docs/api/frame/__str__.rst
  docs/api/frame/countna.rst
  docs/api/frame/countna1.rst
  docs/api/frame/key.rst
  docs/api/frame/keys.rst
  docs/api/frame/ltypes.rst
  docs/api/frame/names.rst
  docs/api/frame/ncols.rst
  docs/api/frame/nrows.rst
  docs/api/frame/rbind.rst
  docs/api/frame/shape.rst
  docs/api/frame/sort.rst
  docs/api/frame/source.rst
  docs/api/frame/stype.rst
  docs/api/frame/stypes.rst
  docs/api/math/round.rst
  docs/conf.py
  docs/develop/create-fexpr.rst
  docs/develop/documentation.rst
  src/core/expr/fexpr_cut.cc
  src/core/expr/fexpr_list.cc
  src/core/expr/fexpr_qcut.cc
  src/core/expr/fexpr_round.cc
  src/core/frame/names.cc
  src/core/frame/py_frame.cc
  src/core/frame/rbind.cc
  src/core/frame/stats.cc
  src/core/frame/to_python.cc
  src/core/sort.cc
  src/datatable/sphinxext/ref_context.py
  src/datatable/sphinxext/xfunction.py
Labels: documentation

#2596 Updates to FTRL docs
  docs/api/math.rst
  docs/api/models.rst
  docs/api/models/Ftrl/alpha.rst
  docs/api/models/Ftrl/beta.rst
  docs/api/models/Ftrl/colname_hashes.rst
  docs/api/models/Ftrl/colnames.rst
  docs/api/models/Ftrl/double_precision.rst
  docs/api/models/Ftrl/feature_importances.rst
  docs/api/models/Ftrl/interactions.rst
  docs/api/models/Ftrl/labels.rst
  docs/api/models/Ftrl/lambda1.rst
  docs/api/models/Ftrl/lambda2.rst
  docs/api/models/Ftrl/mantissa_nbits.rst
  docs/api/models/Ftrl/model.rst
  docs/api/models/Ftrl/model_type.rst
  docs/api/models/Ftrl/model_type_trained.rst
  docs/api/models/Ftrl/nbins.rst
  docs/api/models/Ftrl/negative_class.rst
  docs/api/models/Ftrl/nepochs.rst
  docs/api/models/Ftrl/params.rst
  docs/api/models/ftrl.rst
  docs/releases/v0.10.0.rst
  src/core/models/py_ftrl.cc
Labels: documentation

#2597 Change np.array to np.asfortranarray in to_numpy for performance
  src/core/frame/to_numpy.cc
Labels: performance

#2602 Documentation for FExpr class
  docs/_static/code.css
  docs/api/fexpr.rst
  docs/api/fexpr/__add__.rst
  docs/api/fexpr/__and__.rst
  docs/api/fexpr/__bool__.rst
  docs/api/fexpr/__eq__.rst
  docs/api/fexpr/__floordiv__.rst
  docs/api/fexpr/__ge__.rst
  docs/api/fexpr/__gt__.rst
  docs/api/fexpr/__init__.rst
  docs/api/fexpr/__invert__.rst
  docs/api/fexpr/__le__.rst
  docs/api/fexpr/__lshift__.rst
  docs/api/fexpr/__lt__.rst
  docs/api/fexpr/__mod__.rst
  docs/api/fexpr/__mul__.rst
  docs/api/fexpr/__ne__.rst
  docs/api/fexpr/__neg__.rst
  docs/api/fexpr/__or__.rst
  docs/api/fexpr/__pos__.rst
  docs/api/fexpr/__pow__.rst
  docs/api/fexpr/__repr__.rst
  docs/api/fexpr/__rshift__.rst
  docs/api/fexpr/__sub__.rst
  docs/api/fexpr/__truediv__.rst
  docs/api/fexpr/__xor__.rst
  docs/api/fexpr/extend.rst
  docs/api/fexpr/len.rst
  docs/api/fexpr/re_match.rst
  docs/api/fexpr/remove.rst
  docs/api/frame/__str__.rst
  docs/conf.py
  src/core/expr/fbinary/fexpr__add__.cc
  src/core/expr/fexpr.cc
  src/core/frame/py_frame.cc
  src/datatable/sphinxext/xfunction.py
Labels: documentation

#2600 Promote result to float for the power operator
  src/core/expr/fbinary/fexpr__pow__.cc
  tests/expr/fbinary/test-pow.py
Labels: bug

#2608 Document few more functions
  docs/_static/xfunction.css
  docs/api/dt/build_info.rst
  docs/api/dt/dt.rst
  docs/api/dt/f.rst
  docs/api/dt/g.rst
  docs/api/index-api.rst
  docs/api/namespace.rst
  docs/api/namespace/__getattribute__.rst
  docs/api/namespace/__getitem__.rst
  src/core/expr/namespace.cc
  src/datatable/__init__.py
  src/datatable/sphinxext/xfunction.py
Labels: documentation

#2606 Document most of the functions
  docs/api/dt/corr.rst
  docs/api/dt/count.rst
  docs/api/dt/cov.rst
  docs/api/dt/first.rst
  docs/api/dt/init_styles.rst
  docs/api/dt/intersect.rst
  docs/api/dt/join.rst
  docs/api/dt/last.rst
  docs/api/dt/max.rst
  docs/api/dt/mean.rst
  docs/api/dt/median.rst
  docs/api/dt/min.rst
  docs/api/dt/rowall.rst
  docs/api/dt/rowany.rst
  docs/api/dt/rowcount.rst
  docs/api/dt/rowfirst.rst
  docs/api/dt/rowlast.rst
  docs/api/dt/rowmax.rst
  docs/api/dt/rowmean.rst
  docs/api/dt/rowmin.rst
  docs/api/dt/rowsd.rst
  docs/api/dt/rowsum.rst
  docs/api/dt/sd.rst
  docs/api/dt/setdiff.rst
  docs/api/dt/split_into_nhot.rst
  docs/api/dt/sum.rst
  docs/api/dt/symdiff.rst
  docs/api/dt/union.rst
  docs/api/dt/unique.rst
  docs/api/index-api.rst
  src/core/expr/fexpr_cut.cc
  src/core/expr/fexpr_qcut.cc
  src/core/expr/fnary/rowall.cc
  src/core/expr/fnary/rowany.cc
  src/core/expr/fnary/rowcount.cc
  src/core/expr/fnary/rowfirstlast.cc
  src/core/expr/fnary/rowmean.cc
  src/core/expr/fnary/rowminmax.cc
  src/core/expr/fnary/rowsd.cc
  src/core/expr/fnary/rowsum.cc
  src/core/expr/funary/pyfn.cc
  src/core/expr/head_reduce_binary.cc
  src/core/expr/head_reduce_unary.cc
  src/core/expr/py_join.cc
  src/core/frame/repr/html_styles.cc
  src/core/set_funcs.cc
  src/core/str/py_str.cc
Labels: documentation

#2612 Make empty sort API consistent
  docs/releases/v0.11.0.rst
  src/core/sort.cc
  tests/ijby/test-sort.py
Labels: API change, sort

#2614 Improve documentation on models
  docs/api/frame.rst
  docs/api/models.rst
  docs/api/models/Ftrl/__init__.rst
  docs/api/models/Ftrl/double_precision.rst
  docs/api/models/Ftrl/fit.rst
  docs/api/models/Ftrl/ftrl_algorithm.png
  docs/api/models/Ftrl/predict.rst
  docs/api/models/Ftrl/reset.rst
  docs/api/models/aggregate.rst
  docs/api/models/ftrl.rst
  docs/api/models/kfold.rst
  docs/api/models/kfold_random.rst
  docs/models/index-models.rst
  docs/releases/v0.11.0.rst
  src/core/datatablemodule.cc
  src/core/expr/py_join.cc
  src/core/models/aggregate.cc
  src/core/models/aggregate.h
  src/core/models/kfold.cc
  src/core/models/py_ftrl.cc
  tests/models/test-ftrl.py
Labels: API change, documentation, improve, test

#2610 Fix reverse flag in sort
  src/core/expr/eval_context.cc
  src/core/expr/eval_context.h
  src/core/expr/fexpr_list.cc
  tests/ijby/test-sort.py
Labels: bug, sort

#2618 Fix regexp to parse parameter in xfunction signature
  src/datatable/sphinxext/xfunction.py
Labels: documentation

#2617 Fix styling of Frames in Jupyter
  src/core/frame/repr/html_styles.cc
Labels: bug

#2611 Add tutorial on API comparison of R's data.table vs datatable
  docs/conf.py
  docs/manual/comparison_with_rdatatable.rst
  docs/manual/index-manual.rst
Labels: documentation, new feature

#2620 Handle multi-params in function 'Parameters' section
  docs/_static/xfunction.css
  src/datatable/sphinxext/xfunction.py
  src/datatable/sphinxext/xnodes.py
Labels: bug, documentation

#2623 Adjust styles for bullet lists in generated docs
  docs/_static/code.css
Labels: documentation

#2624 Fix style of multi-params in documentation
  docs/_static/xfunction.css
  src/datatable/sphinxext/xfunction.py
Labels: documentation, low priority

#2634 Documentation for stype/ltype
  docs/api/dt/build_info.rst
  docs/api/index-api.rst
  docs/api/ltype.rst
  docs/api/ltype/__new__.rst
  docs/api/ltype/stypes.rst
  docs/api/stype.rst
  docs/api/stype/__call__.rst
  docs/api/stype/__new__.rst
  docs/api/stype/ctype.rst
  docs/api/stype/dtype.rst
  docs/api/stype/ltype.rst
  docs/api/stype/max.rst
  docs/api/stype/min.rst
  docs/api/stype/struct.rst
  src/datatable/sphinxext/xfunction.py
  src/datatable/types.py
  tests/test-docs.py
Labels: documentation

#2637 Documentation for internal. submodule
  docs/api/index-api.rst
  docs/api/internal.rst
  docs/api/internal/compiler_version.rst
  docs/api/internal/frame_column_data_r.rst
  docs/api/internal/frame_columns_virtual.rst
  docs/api/internal/frame_integrity_check.rst
  docs/api/internal/get_thread_ids.rst
  docs/api/internal/in_debug_mode.rst
  docs/api/internal/regex_supported.rst
  docs/conf.py
  src/core/datatablemodule.cc
  tests/munging/test-cbind.py
  tests/munging/test-dt-combo.py
  tests/test-dt.py
Labels: documentation

#2635 Add documentation on datatable options
  docs/api/frame/__getitem__.rst
  docs/api/index-api.rst
  docs/api/options.rst
  docs/api/options/debug.rst
  docs/api/options/debug/arg_max_size.rst
  docs/api/options/debug/enabled.rst
  docs/api/options/debug/logger.rst
  docs/api/options/debug/report_args.rst
  docs/api/options/display.rst
  docs/api/options/display/allow_unicode.rst
  docs/api/options/display/head_nrows.rst
  docs/api/options/display/interactive.rst
  docs/api/options/display/max_column_width.rst
  docs/api/options/display/max_nrows.rst
  docs/api/options/display/tail_nrows.rst
  docs/api/options/display/use_colors.rst
  docs/api/options/frame.rst
  docs/api/options/frame/names_auto_index.rst
  docs/api/options/frame/names_auto_prefix.rst
  docs/api/options/fread.rst
  docs/api/options/fread/log.rst
  docs/api/options/fread/log/anonymize.rst
  docs/api/options/fread/log/escape_unicode.rst
  docs/api/options/nthreads.rst
  docs/api/options/progress.rst
  docs/api/options/progress/allow_interruption.rst
  docs/api/options/progress/callback.rst
  docs/api/options/progress/clear_on_success.rst
  docs/api/options/progress/enabled.rst
  docs/api/options/progress/min_duration.rst
  docs/api/options/progress/updates_per_second.rst
  docs/index.rst
  docs/manual/ftrl.rst
  docs/manual/groupby_examples.rst
  docs/manual/index-manual.rst
  docs/models/index-models.rst
  src/core/call_logger.cc
  src/core/csv/reader.cc
  src/core/frame/names.cc
  src/core/frame/py_frame.cc
  src/core/frame/repr/repr_options.cc
  src/core/models/aggregate.cc
  src/core/parallel/thread_pool.cc
  src/core/progress/_options.cc
  src/core/sort.cc
Labels: documentation

#2630 added more examples simulating for groupby docs
  docs/manual/groupby_examples.rst
Labels: documentation

#2638 Fix FTRL algo image on readthedocs
  docs/_static/ftrl_algorithm.png
  docs/api/models/Ftrl/ftrl_algorithm.png
  src/core/models/py_ftrl.cc
Labels: documentation

#2641 Release 0.11.0
  README.md
  VERSION.txt
  appveyor.yml
  ci/Jenkinsfile.groovy
  ci/ext.py
  docs/api/dt/build_info.rst
  docs/manual/comparison_with_rdatatable.rst
  docs/releases/index-releases.rst
  docs/releases/v0.11.0.rst
  docs/start/quick-start.rst
Labels: ITA

#2643 Update version number after the release
  VERSION.txt
  ci/Jenkinsfile.groovy
Labels: ITA

#2644 Update documentation after the release
  docs/releases/index-releases.rst
  docs/releases/v0.11.0.rst
  docs/releases/v1.0.0.rst
  docs/start/install.rst
  src/datatable/sphinxext/dt_changelog.py
Labels: documentation

#2646 Code cleanup in fread
  src/core/csv/reader.cc
  src/core/csv/reader.h
  src/core/read/multisource.cc
  src/core/read/multisource.h
  src/core/read/py_fread.cc
  src/core/read/py_read_iterator.cc
  src/core/read/py_read_iterator.h
Labels: fread, refactor

#2648 Do not test API docs if API path doesn't exist
  tests/test-docs.py
Labels: documentation, test

#2652 Rename master -> main
  README.md
  appveyor.yml
  ci/Jenkinsfile.groovy
  ci/README.md
  ci/ext.py
  docs/conf.py
  docs/develop/contrib.rst
  docs/index.rst
  docs/releases/v0.5.0.rst
  docs/start/install.rst
  src/core/csv/reader.h
  src/core/jay/README.md
  src/core/models/aggregate.cc
  src/core/parallel/api.h
  src/core/parallel/parallel_for_dynamic.cc
  src/core/progress/progress_manager.h
Labels: ITA

#2651 On AppVeyor use PowerShell for ifelse
  appveyor.yml
Labels: ITA

#2654 Update style of the documentation front page
  docs/_static/code.css
  docs/index.rst
Labels: documentation

#2657 Convert appveyor.yml to the PowerShell format
  appveyor.yml
Labels: ITA

#2660 Minor fixes to the 0.11.0 release notes
  docs/releases/v0.11.0.rst
Labels: documentation

#2658 Expanded ifelse() function to allow multiple conditions
  docs/manual/comparison_with_rdatatable.rst
  docs/releases/v1.0.0.rst
  src/core/column/ifelsen.cc
  src/core/column/ifelsen.h
  src/core/expr/fexpr_ifelse.cc
  src/core/expr/workframe.cc
  src/core/expr/workframe.h
  src/core/python/xargs.cc
  src/core/python/xargs.h
  src/datatable/sphinxext/xfunction.py
  tests/expr/test-ifelse.py
Labels: improve

#2661 Remove builds/tests for python3.5
  .travis.yml
  README.md
  appveyor.yml
  ci/Jenkinsfile.groovy
  ci/README.md
  ci/ext.py
  docs/releases/v1.0.0.rst
  docs/start/install.rst
  src/core/python/dict.cc
  src/datatable/utils/fread.py
  tests/__init__.py
  tests/conftest.py
  tests/frame/test-copy.py
  tests/frame/test-create.py
  tests/fread/test-fread-api.py
  tests/fread/test-fread-issues.py
  tests/ijby/test-assign-scalar.py
  tests/ijby/test-rowwise.py
  tests/munging/test-dt-cols.py
  tests/munging/test-dt-rows.py
  tests/test-dt.py
  tests/test-groups.py
  tests/test-tocsv.py
  tests_random/utils.py
Labels: API change

#2662 Fix git_revision/git_branch during a release
  appveyor.yml
  ci/Jenkinsfile.groovy
  ci/ext.py
Labels: ITA

#2664 Create directory /tmp/cores on macOS before running tests
  ci/Jenkinsfile.groovy
Labels: ITA
