Repository h2oai/datatable, pull requests merged in 2020-07, with the labels that each got.

#2509 [DOC] Fread usage examples
  .gitignore
  docs/manual/fread_examples.rst
  docs/manual/index-manual.rst
Labels: documentation, fread

#2515 Make sure debug wheels are stashed on S3
  ci/Jenkinsfile.groovy
Labels: ITA

#2516 Temporarily disable monitor thread
  src/core/parallel/api.h
  src/core/parallel/monitor_thread.cc
  src/core/parallel/monitor_thread.h
  src/core/parallel/parallel_for_ordered.cc
  src/core/parallel/parallel_for_static.h
  src/core/parallel/thread_pool.cc
  src/core/parallel/thread_pool.h
  src/core/parallel/thread_worker.cc
  src/core/progress/progress_bar.cc
  src/core/progress/progress_manager.cc
  src/core/progress/progress_manager.h
  src/core/utils/logger.cc
  src/core/utils/temporary_file.cc
Labels: improve

#2520 Fix predict progress in FTRL, adjust nested_for_static
  src/core/models/dt_ftrl.cc
  src/core/parallel/parallel_for_static.h
Labels: bug

#2521 Fix deadlock in barrier when an exception occurs
  src/core/parallel/thread_team.cc
  src/core/parallel/thread_worker.cc
  src/core/progress/progress_manager.cc
Labels: High priority, bug

#2524 Add ppc64 debug wheel building+testing to Jenkins
  ci/Jenkinsfile.groovy
Labels: ITA

#2527 Exception initialization is now done at datatable import
  docs/releases/v0.11.0.rst
  src/core/datatablemodule.cc
  src/core/options.cc
  src/core/utils/exceptions.cc
  src/core/utils/exceptions.h
  src/datatable/__init__.py
  src/datatable/options.py
Labels: bug

#2531 Created ..xcode::shell Sphinx directive
  docs/_static/xcode.css
  docs/conf.py
  docs/develop/contrib.rst
  docs/develop/documentation.rst
  docs/start/install.rst
  docs/start/quick-start.rst
  requirements_docs.txt
  src/datatable/sphinxext/xcode.py
Labels: documentation

#2530 [DOC]Groupby examples documentation
  docs/manual/groupby_examples.rst
  docs/manual/index-manual.rst
Labels: documentation

#2536 Auto-generate links to artifacts published on S3
  ci/Jenkinsfile.groovy
Labels: ITA

#2538 Update installation instructions
  docs/_static/code.css
  docs/_static/xcode.css
  docs/conf.py
  docs/start/install.rst
  src/datatable/sphinxext/xcode.py
Labels: documentation

#2535 Implement cut() function
  docs/api/dt/cut.rst
  docs/api/index-api.rst
  docs/releases/v0.11.0.rst
  src/core/_dt.h
  src/core/column/cut.h
  src/core/datatablemodule.cc
  src/core/datatablemodule.h
  src/core/expr/!readme.md
  src/core/expr/head_func.cc
  src/core/expr/head_func.h
  src/core/expr/head_func_cut.cc
  src/core/expr/head_func_isclose.cc
  src/core/expr/op.h
  src/core/models/aggregator.h
  src/core/stats.cc
  src/datatable/__init__.py
  src/datatable/expr/expr.py
  src/datatable/models.py
  src/datatable/sphinxext/xfunction.py
  tests/ijby/test-cut.py
Labels: documentation, new feature, test

#2548 Fix loading a Frame from a temporary bytes Jay object
  docs/releases/v0.11.0.rst
  src/core/buffer.cc
  src/core/buffer.h
  src/core/read/source.cc
  tests/test_jay.py
Labels: High priority, bug

#2552 Expand documentation of the Frame class
  docs/_static/code.css
  docs/api/frame.rst
  docs/api/frame/ltypes.rst
  docs/api/frame/materialize.rst
  docs/api/frame/ncols.rst
  docs/api/frame/nrows.rst
  docs/api/frame/shape.rst
  docs/api/frame/stype.rst
  docs/api/frame/stypes.rst
  docs/api/frame/to_dict.rst
  docs/api/frame/to_jay.rst
  docs/api/frame/to_list.rst
  docs/api/frame/to_numpy.rst
  docs/api/frame/to_pandas.rst
  docs/api/frame/to_tuples.rst
  src/core/frame/py_frame.cc
  src/core/frame/to_numpy.cc
  src/core/frame/to_python.cc
  src/core/jay/save_jay.cc
  tests/test_dt.py
Labels: documentation

#2553 Make ..xfunction compatible with Sphinx 3
  docs/api/frame.rst
  docs/conf.py
  requirements_docs.txt
  src/datatable/sphinxext/xfunction.py
Labels: documentation

#2554 Documentation for Frame.__init__()
  docs/api/frame.rst
  docs/api/frame/__init__.rst
  docs/api/math.rst
  docs/develop/contrib.rst
  docs/docutils.conf
  docs/manual/f-expressions.rst
  docs/manual/name_mangling.rst
  docs/start/install.rst
  src/core/frame/py_frame.cc
  src/datatable/sphinxext/xfunction.py
Labels: documentation

#2555 Refactor parallel ordered for loop
  src/core/column/sentinel_str.cc
  src/core/cstring.cc
  src/core/cstring.h
  src/core/parallel/api.h
  src/core/parallel/parallel_for_dynamic.cc
  src/core/parallel/parallel_for_ordered.cc
  src/core/parallel/parallel_region.cc
  src/core/parallel/string_utils.cc
  src/core/parallel/string_utils.h
  src/core/parallel/thread_pool.cc
  src/core/parallel/thread_pool.h
  src/core/parallel/thread_team.cc
  src/core/parallel/thread_team.h
  src/core/parallel/thread_worker.cc
  src/core/parallel/ztest_parallel_for.cc
  src/core/progress/ztest_progress.cc
  src/core/read/parallel_reader.cc
  src/core/read/parallel_reader.h
  src/core/read/preframe.cc
  src/core/read/preframe.h
  src/core/read/thread_context.cc
  src/core/read/thread_context.h
  src/core/write/write_manager.cc
  src/core/wstringcol.h
Labels: refactor

#2556 Upgrade pygments and sphinx_rtd_theme versions
  requirements_docs.txt
  src/datatable/sphinxext/xcode.py
Labels: documentation

#2557 New framework for writing C++ tests
  ci/headers.py
  src/core/datatable.h
  src/core/datatablemodule.cc
  src/core/frame/__init__.cc
  src/core/frame/integrity_check.cc
  src/core/frame/names.cc
  src/core/jay/save_jay.cc
  src/core/parallel/ztest_parallel_for.cc
  src/core/read/multisource.cc
  src/core/tests/test_atomic.cc
  src/core/tests/test_barrier.cc
  src/core/tests/test_parallel_for.cc
  src/core/tests/test_progress.cc
  src/core/tests/test_shared_mutex.cc
  src/core/utils/exceptions.cc
  src/core/utils/exceptions.h
  src/core/utils/logger.cc
  src/core/utils/tests.cc
  src/core/utils/tests.h
  src/core/ztest.cc
  src/core/ztest.h
  tests/__init__.py
  tests/conftest.py
  tests/test_dt.py
  tests/test_parallel.py
Labels: new feature, test
