Repository h2oai/datatable, pull requests merged in 2020-11, with the labels that each got.

#2726 Fix positioning of nav menu on the right
  docs/_static/wren.css
Labels: documentation

#2730 Fread tests
  tests/fread/test-fread-detect.py
  tests/fread/test-fread-issues.py
Labels: fread, test

#2735 Added indicators of external links
  docs/_static/wren.css
Labels: documentation

#2736 Fix a link to join tutorial in docs
  src/core/expr/py_join.cc
Labels: documentation

#2738 Adjust ppc builds
  ci/Jenkinsfile.groovy
Labels: ITA

#2734 Allow frame to carry meta information
  docs/api/frame.rst
  docs/releases/v1.0.0.rst
  src/core/frame/py_frame.cc
  src/core/frame/py_frame.h
  tests/test-dt.py
Labels: new feature

#2741 Fix numerous warnings in documentation build
  docs/_static/wren.css
  docs/api/exceptions.rst
  docs/api/exceptions/dtexception.rst
  docs/api/exceptions/dtwarning.rst
  docs/api/exceptions/importerror.rst
  docs/api/exceptions/indexerror.rst
  docs/api/exceptions/invalidoperationerror.rst
  docs/api/exceptions/ioerror.rst
  docs/api/exceptions/iowarning.rst
  docs/api/exceptions/keyerror.rst
  docs/api/exceptions/memoryerror.rst
  docs/api/exceptions/notimplementederror.rst
  docs/api/exceptions/overflowerror.rst
  docs/api/exceptions/typeerror.rst
  docs/api/exceptions/valueerror.rst
  docs/api/fexpr/__init__.rst
  docs/api/frame/__getitem__.rst
  docs/api/index-api.rst
  docs/api/options.rst
  docs/api/options/debug.rst
  docs/api/options/display.rst
  docs/api/options/frame.rst
  docs/api/options/fread.rst
  docs/api/options/fread/log.rst
  docs/api/options/progress.rst
  docs/conf.py
  docs/manual/comparison_with_pandas.rst
  docs/manual/groupby_examples.rst
  docs/releases/v0.11.0.rst
  docs/start/quick-start.rst
  src/core/expr/py_join.cc
  src/core/frame/names.cc
  src/core/set_funcs.cc
  src/core/str/py_str.cc
  src/datatable/sphinxext/dtframe_directive.py
  src/datatable/sphinxext/xfunction.py
  src/datatable/sphinxext/xpython.py
Labels: documentation

#2742 Add missing meta.rst file
  docs/api/frame/meta.rst
Labels: bug

#2740 Improve ppc builds and a minor fix to docs
  ci/Jenkinsfile.groovy
  docs/api/frame.rst
Labels: bug, documentation, improve

#2737 Convert an Arrow Table into a Frame
  docs/releases/v1.0.0.rst
  requirements_extra.txt
  src/core/_dt.h
  src/core/buffer.cc
  src/core/buffer.h
  src/core/column.h
  src/core/column/arrow_bool.cc
  src/core/column/arrow_bool.h
  src/core/column/arrow_fw.cc
  src/core/column/arrow_fw.h
  src/core/column/arrow_str.cc
  src/core/column/arrow_str.h
  src/core/column_from_arrow.cc
  src/core/csv/reader.cc
  src/core/expr/head_reduce_binary.cc
  src/core/expr/head_reduce_unary.cc
  src/core/frame/__init__.cc
  src/core/frame/py_frame.cc
  src/core/frame/stats.cc
  src/core/python/arg.cc
  src/core/python/arg.h
  src/core/python/obj.cc
  src/core/python/obj.h
  src/core/python/pybuffer.cc
  src/core/python/pybuffer.h
  src/core/read/source.cc
  src/core/sort.cc
  src/core/utils/arrow_structs.h
  tests/conftest.py
  tests/frame/test-create.py
  tests/test-docs.py
Labels: new feature

#2749 Ensure doc website looks good on mobile devices
  .gitignore
  docs/Makefile
  docs/_static/code.css
  docs/_static/wren.css
  docs/conf.py
  docs/index.rst
Labels: documentation

#2756 Allow reading and writing files larger than 4Gb on Windows
  docs/releases/v0.11.1.rst
  src/core/buffer.cc
  src/core/frame/to_csv.cc
  src/core/lib/mman/mman.cc
  src/core/lib/mman/mman.h
  src/core/utils/file.cc
  src/core/utils/file.h
  src/core/utils/macros.h
  src/core/write/write_manager.cc
  src/core/writebuf.cc
Labels: bug, fread, segfault

#2724 [DOC] if else examples
  docs/api/dt/ifelse.rst
  src/core/expr/fexpr_ifelse.cc
Labels: documentation

#2722 [DOC] Examples for update() method
  docs/api/dt/update.rst
  src/core/expr/py_update.cc
Labels: documentation

#2760 [DOC] Examples for median()
  src/core/expr/head_reduce_unary.cc
Labels: documentation

#2752 [DOC] max() examples
  src/core/expr/head_reduce_unary.cc
Labels: documentation

#2759 [DOC] Examples for mean()
  src/core/expr/head_reduce_unary.cc
Labels: documentation

#2750 [DOC] last() examples
  src/core/expr/head_reduce_unary.cc
Labels: documentation
