Repository h2oai/datatable, pull requests merged in 2020-06, with the labels that each got.

#2466 LType refactoring
  src/core/_dt.h
  src/core/api.cc
  src/core/column.cc
  src/core/column.h
  src/core/column/range.cc
  src/core/datatablemodule.cc
  src/core/expr/eval_context.cc
  src/core/expr/fbinary/arithmetic.cc
  src/core/expr/fbinary/bitwise.cc
  src/core/expr/fbinary/math.cc
  src/core/expr/funary/exponential.cc
  src/core/expr/funary/hyperbolic.cc
  src/core/expr/funary/special.cc
  src/core/expr/funary/trigonometric.cc
  src/core/expr/head_frame.cc
  src/core/expr/head_func_isclose.cc
  src/core/expr/head_func_other.cc
  src/core/expr/head_literal_float.cc
  src/core/expr/head_literal_int.cc
  src/core/expr/head_literal_string.cc
  src/core/expr/head_literal_type.cc
  src/core/frame/integrity_check.cc
  src/core/frame/py_frame.cc
  src/core/frame/rbind.cc
  src/core/frame/repr/html_widget.h
  src/core/frame/repr/text_column.cc
  src/core/ltype.cc
  src/core/ltype.h
  src/core/models/aggregator.cc
  src/core/models/py_ftrl.cc
  src/core/python/obj.cc
  src/core/stats.cc
  src/core/str/split_into_nhot.cc
  src/core/stype.cc
  src/core/stype.h
  src/core/types.cc
  src/core/types.h
  src/core/utils/exceptions.cc
  src/core/utils/exceptions.h
Labels: refactor

#2468 Debug logger feature
  docs/releases/v0.11.0.rst
  src/core/_dt.h
  src/core/call_logger.cc
  src/core/call_logger.h
  src/core/datatablemodule.cc
  src/core/frame/__repr__.cc
  src/core/options.cc
  src/core/options.h
  src/core/parallel/thread_pool.cc
  src/core/python/arg.cc
  src/core/python/args.cc
  src/core/python/args.h
  src/core/python/obj.cc
  src/core/python/obj.h
  src/core/python/xobject.cc
  src/core/python/xobject.h
  src/core/utils/exceptions.cc
  src/core/utils/exceptions.h
  src/core/utils/logger.cc
  src/core/utils/logger.h
  src/datatable/expr/expr.py
  src/datatable/options.py
  tests/ijby/test-rowwise.py
  tests/test_options.py
Labels: new feature

#2472 f[:] within a groupby
  docs/releases/v0.11.0.rst
  src/core/expr/head_literal_sliceall.cc
  tests/test-groups.py
Labels: API change

#2475 Fix documentation of Frame.colindex()
  src/core/frame/names.cc
Labels: documentation

#2477 Enable building debug-mode wheels
  ci/ext.py
Labels: ITA

#2478 Remove macros TRACK/UNTRACK
  src/core/buffer.cc
  src/core/datatablemodule.cc
  src/core/datatablemodule.h
  src/core/py_buffers.cc
  src/core/sort.cc
  src/core/utils/alloc.cc
  src/core/wstringcol.cc
Labels: refactor

#2476 Finish fread-to-file functionality; added documentation
  docs/api/api-index.rst
  docs/api/dt/fread.rst
  docs/api/dt/iread.rst
  docs/index.rst
  docs/releases/v0.11.0.rst
  src/core/csv/reader_fread.cc
  src/core/read/output_column.cc
  src/core/read/py_fread.cc
  src/datatable/sphinxext/xfunction.py
  src/datatable/utils/fread.py
  tests/fread/test_fread_api.py
  tests/fread/test_fread_large.py
  tests/fread/test_fread_small.py
Labels: documentation

#2479 Macros for compiler warnings handling
  src/core/column/sentinel_fw.cc
  src/core/frame/replace.cc
  src/core/parallel/monitor_thread.cc
  src/core/parallel/monitor_thread.h
  src/core/parallel/semaphore.h
  src/core/python/xobject.h
  src/core/utils/assert.h
  src/core/utils/macros.h
  src/core/utils/misc.cc
  src/core/utils/misc.h
  src/core/writebuf.cc
Labels: refactor

#2482 Fix some compiler warnings produced by Clang-10
  src/core/python/args.cc
  src/core/stype.h
  src/core/utils/assert.h
Labels: refactor

#2481 Implement ifelse() function
  docs/api/api-index.rst
  docs/api/dt/ifelse.rst
  docs/releases/v0.11.0.rst
  src/core/column/ifelse.cc
  src/core/column/ifelse.h
  src/core/datatablemodule.cc
  src/core/datatablemodule.h
  src/core/expr/!readme.md
  src/core/expr/head_func.cc
  src/core/expr/head_func.h
  src/core/expr/head_func_ifelse.cc
  src/core/expr/op.h
  src/datatable/__init__.py
  src/datatable/expr/expr.py
  tests/ijby/test-ifelse.py
Labels: new feature

#2484 Documentation improvements
  README.md
  docs/_static/code.css
  docs/_static/xfunction.css
  docs/api/api-index.rst
  docs/api/dt/by.rst
  docs/api/dt/cbind.rst
  docs/api/dt/fread.rst
  docs/api/dt/ifelse.rst
  docs/api/dt/iread.rst
  docs/api/dt/rbind.rst
  docs/api/dt/repeat.rst
  docs/api/dt/shift.rst
  docs/api/dt/sort.rst
  docs/api/dt/update.rst
  docs/api/math.rst
  src/core/expr/py_by.cc
  src/core/expr/py_sort.cc
  src/core/expr/py_update.cc
  src/core/frame/cbind.cc
  src/core/frame/rbind.cc
  src/core/frame/repeat.cc
Labels: documentation

#2486 Fix some lint issues reported by Codacity
  docs/_static/code.css
  docs/conf.py
  src/core/expr/!readme.md
  src/datatable/exceptions.py
  src/datatable/sphinxext/xcontributors.py
  src/datatable/utils/fread.py
  tests/frame/test-repr-text.py
  tests/fread/test_fread_api.py
  tests/ijby/test-assign-expr.py
  tests/ijby/test-func-unary.py
  tests/ijby/test-rowwise.py
  tests/ijby/test-update.py
  tests/test_dt_expr.py
  tests/test_f.py
  tests_random/attacker.py
  tests_random/metaframe.py
Labels: low priority, refactor

#2487 Reorganize documentation files
  docs/api/index-api.rst
  docs/contrib.rst
  docs/develop/contrib.rst
  docs/develop/index-develop.rst
  docs/index.rst
  docs/manual/f-expressions.rst
  docs/manual/index-manual.rst
  docs/models/ftrl.rst
  docs/models/index-models.rst
  docs/release-history.rst
  docs/releases/index-releases.rst
  docs/start/index-start.rst
  docs/start/install.rst
  docs/start/quick-start.rst
  docs/start/using-datatable.rst
Labels: documentation, refactor

#2489 Expanded documentation on contributing
  docs/_static/code.css
  docs/develop/contrib.rst
Labels: documentation

#2491 Fix broken links on documentation site
  docs/_static/code.css
  docs/index.rst
Labels: bug, documentation

#2492 Documentation about documentation
  ci/gh.py
  docs/_static/code.css
  docs/api/dt/rbind.rst
  docs/develop/contrib.rst
  docs/develop/documentation.rst
  docs/develop/index-develop.rst
  docs/manual/f-expressions.rst
  docs/releases/v0.10.0.rst
  docs/releases/v0.11.0.rst
  docs/start/install.rst
Labels: documentation

#2493 Add Clang Travis builds
  .travis.yml
  ci/xbuild/compiler.py
Labels: ITA, bug

#2495 Shut down threads during forking
  docs/releases/v0.11.0.rst
  src/core/parallel/thread_pool.cc
  src/core/parallel/thread_worker.cc
  tests/test_parallel.py
Labels: improve

#2500 Minor adjustment to the docs format
  docs/develop/documentation.rst
  docs/releases/v0.10.0.rst
  docs/releases/v0.11.0.rst
  docs/releases/v0.2.1.rst
  docs/releases/v0.2.2.rst
  docs/releases/v0.3.1.rst
  docs/releases/v0.4.0.rst
  docs/start/quick-start.rst
  docs/start/using-datatable.rst
Labels: documentation

#2511 Update regex to catch Attribute-To message in github PR text
  ci/gh.py
Labels: low priority

#2512 Fortify Jenkins and Travis build scripts
  .travis.yml
  ci/Jenkinsfile.groovy
Labels: ITA

#2513 Debug build
  .travis.yml
  appveyor.yml
  ci/Jenkinsfile.groovy
  ci/ext.py
  tests/__init__.py
  tests/test_dt.py
  tests/test_parallel.py
Labels: ITA
