Repository h2oai/datatable, pull requests merged in 2020-12, with the labels that each got.

#2731 [DOC] first() examples
  src/core/expr/head_reduce_unary.cc
Labels: documentation

#2728 Join examples
  .gitignore
  docs/api/dt/join.rst
  src/core/expr/py_join.cc
Labels: documentation

#2770 [DOC] update() examples
  src/core/expr/py_update.cc
Labels: documentation

#2772 [DOC] mean() examples fix
  src/core/expr/head_reduce_unary.cc
Labels: documentation

#2771 [DOC] ifelse() examples
  src/core/expr/fexpr_ifelse.cc
Labels: documentation

#2776 [DOC] sum() examples
  src/core/expr/head_reduce_unary.cc
Labels: documentation

#2774 [DOC] min() function examples
  src/core/expr/head_reduce_unary.cc
Labels: documentation

#2777 [DOC] examples for union() func
  src/core/set_funcs.cc
Labels: documentation

#2778 [DOC] examples for unique()
  src/core/set_funcs.cc
Labels: documentation

#2763 Add large fread tests for Windows, adjust build scripts
  appveyor.yml
  ci/Jenkinsfile.groovy
  tests/conftest.py
  tests/expr/test-qcut.py
  tests/fread/test-fread-large.py
Labels: ITA, test

#2779 Add a note in Install doc / Troubleshooting section
  docs/start/install.rst
Labels: documentation

#2788 Fix release branch builds on AppVeyor
  appveyor.yml
Labels: ITA

#2789 Move doc extensions into docs/_ext folder
  docs/_ext/changelog.py
  docs/_ext/dtframe_directive.py
  docs/_ext/xcode.py
  docs/_ext/xcontributors.py
  docs/_ext/xfunction.py
  docs/_ext/xnodes.py
  docs/_ext/xpython.py
  docs/conf.py
  tests/test-sphinxext-dtframe.py
Labels: documentation, refactor

#2784 [DOC] Examples for stype
  docs/api/stype/__call__.rst
Labels: documentation

#2801 [DOC] Examples for dt.cov
  src/core/expr/head_reduce_binary.cc
Labels: documentation

#2800 [DOC] Examples for dt.corr()
  src/core/expr/head_reduce_binary.cc
Labels: documentation

#2799 [DOC] examples for dt.cbind()
  src/core/frame/cbind.cc
Labels: documentation

#2798 [DOC] Examples for count()
  src/core/expr/head_reduce_unary.cc
Labels: documentation

#2773 [DOC] median() examples
  src/core/expr/head_reduce_unary.cc
Labels: documentation

#2805 On PPC64 machines avoid installing pyarrow
  ci/Jenkinsfile.groovy
Labels: ITA

#2783 Create new column type: VOID
  src/core/column.cc
  src/core/column.h
  src/core/column/column_impl.cc
  src/core/column/const.cc
  src/core/column/const.h
  src/core/column/const_na.cc
  src/core/column/cut.h
  src/core/column/range.cc
  src/core/column/range.h
  src/core/column/sentinel_str.cc
  src/core/column_from_python.cc
  src/core/expr/eval_context.cc
  src/core/expr/fbinary/bitwise.cc
  src/core/expr/fbinary/math.cc
  src/core/expr/fexpr_literal_float.cc
  src/core/expr/fexpr_literal_type.cc
  src/core/expr/funary/basic.cc
  src/core/expr/funary/exponential.cc
  src/core/expr/funary/floating.cc
  src/core/expr/funary/hyperbolic.cc
  src/core/expr/funary/special.cc
  src/core/expr/funary/trigonometric.cc
  src/core/expr/funary/umaker_impl.h
  src/core/frame/__init__.cc
  src/core/frame/repr/text_column.cc
  src/core/frame/to_numpy.cc
  src/core/jay/open_jay.cc
  src/core/ltype.cc
  src/core/models/aggregate.cc
  src/core/models/dt_ftrl.cc
  src/core/models/label_encode.cc
  src/core/py_buffers.cc
  src/core/python/pybuffer.cc
  src/core/stats.cc
  src/core/stats.h
  src/core/stype.cc
  src/core/stype.h
  src/datatable/types.py
  tests/expr/test-qcut.py
  tests/frame/test-create.py
  tests/fread/test-fread-detect.py
  tests/fread/test-fread-small.py
  tests/models/test-aggregate.py
  tests/test-dt-stats.py
  tests/test-dt.py
  tests/test-jay.py
  tests/test-keys.py
  tests/test-sets.py
  tests/test-types.py
Labels: new feature

#2807 Improve rendering of code samples in the documentation
  docs/_ext/xcode.py
  docs/_ext/xfunction.py
  docs/_static/code.css
  docs/_static/wren.css
  docs/_static/xcode.css
  docs/conf.py
  docs/develop/contrib.rst
  docs/develop/documentation.rst
  docs/develop/test.rst
  docs/manual/fread_examples.rst
  docs/start/install.rst
  docs/start/quick-start.rst
  docs/start/using-datatable.rst
  src/core/expr/head_reduce_unary.cc
Labels: documentation, improve

#2785 [DOC] Examples for as_type
  src/core/expr/fexpr_astype.cc
Labels: documentation

#2786 [DOC] Examples for by()
  src/core/expr/py_by.cc
Labels: documentation

#2812 wallclock() function now uses c++ <chrono> library
  src/core/utils/misc.cc
Labels: refactor

#2815 Documentation cleanup
  docs/_ext/xcode.py
  docs/_static/wren.css
  docs/_static/xcode.css
  docs/develop/test.rst
  docs/manual/comparison_with_pandas.rst
  docs/manual/comparison_with_rdatatable.rst
  docs/manual/comparison_with_sql.rst
  docs/manual/f-expressions.rst
  docs/manual/fread_examples.rst
  docs/manual/ftrl.rst
  docs/manual/groupby_examples.rst
  docs/manual/row_functions.rst
  docs/start/install.rst
  docs/start/quick-start.rst
Labels: documentation

#2816 Directives x-version-changed and x-version-deprecated
  docs/_ext/xfunction.py
  docs/_static/xfunction.css
  docs/_static/xversion.css
  docs/api/dt/build_info.rst
  docs/api/fexpr/len.rst
  docs/develop/documentation.rst
  docs/develop/test.rst
  docs/manual/f-expressions.rst
  src/core/datatablemodule.cc
  src/core/expr/fexpr.cc
  src/core/expr/fexpr_astype.cc
  src/core/expr/fexpr_cut.cc
  src/core/expr/fexpr_ifelse.cc
  src/core/expr/fexpr_qcut.cc
  src/core/expr/fexpr_round.cc
  src/core/frame/py_frame.cc
  src/core/read/py_fread.cc
  src/datatable/__init__.py
Labels: documentation, new feature

#2818 Documentation cleanup
  docs/_ext/dtframe_directive.py
  docs/_ext/xcode.py
  docs/_ext/xfunction.py
  docs/_static/code.css
  docs/_static/wren.css
  docs/api/dt/dt.rst
  docs/api/fexpr/__and__.rst
  docs/api/fexpr/__invert__.rst
  docs/api/fexpr/__or__.rst
  docs/api/fexpr/__repr__.rst
  docs/api/fexpr/__xor__.rst
  docs/api/frame/__iter__.rst
  docs/api/frame/__repr__.rst
  docs/api/frame/__reversed__.rst
  docs/api/index-api.rst
  docs/api/internal.rst
  docs/api/stype/__call__.rst
  docs/conf.py
  docs/develop/documentation.rst
  docs/develop/test.rst
  docs/releases/v0.10.0.rst
  docs/releases/v0.10.1.rst
  docs/releases/v0.11.0.rst
  docs/releases/v0.7.0.rst
  docs/releases/v0.8.0.rst
  docs/releases/v1.0.0.rst
  src/core/datatablemodule.cc
  src/core/expr/fexpr_astype.cc
  src/core/expr/fexpr_ifelse.cc
  src/core/expr/fexpr_round.cc
  src/core/expr/funary/floating.cc
  src/core/expr/funary/special.cc
  src/core/expr/head_reduce_binary.cc
  src/core/expr/head_reduce_unary.cc
  src/core/expr/py_by.cc
  src/core/expr/py_join.cc
  src/core/expr/py_sort.cc
  src/core/expr/py_update.cc
  src/core/frame/__repr__.cc
  src/core/frame/cbind.cc
  src/core/frame/key.cc
  src/core/frame/py_frame.cc
  src/core/frame/rbind.cc
  src/core/frame/replace.cc
  src/core/set_funcs.cc
  src/core/str/py_str.cc
  tests/test-sphinxext-dtframe.py
Labels: documentation, refactor
