Repository h2oai/datatable, pull requests merged in 2020-02, with the labels that each got.

#2339 Add python3.8 MacOS build and tests to Jenkinsfile
  ci/Jenkinsfile.groovy
  tests/test_parallel.py
Labels: ITA

#2341 Remove dt::array class
  ci/xbuild/extension.py
  src/core/buffer.cc
  src/core/buffer.h
  src/core/expr/eval_context.cc
  src/core/expr/head_func_shift.cc
  src/core/expr/head_list.cc
  src/core/expr/head_literal_int.cc
  src/core/expr/head_literal_sliceint.cc
  src/core/frame/join.cc
  src/core/groupby.cc
  src/core/groupby.h
  src/core/models/aggregator.cc
  src/core/models/dt_ftrl.cc
  src/core/read/parallel_reader.h
  src/core/read/thread_context.h
  src/core/rowindex.cc
  src/core/rowindex.h
  src/core/rowindex_array.cc
  src/core/rowindex_impl.h
  src/core/rowindex_slice.cc
  src/core/set_funcs.cc
  src/core/sort.cc
  src/core/utils/array.h
  src/core/wstringcol.cc
  src/core/wstringcol.h
Labels: refactor

#2342 Add .readthedocs.yml config file
  docs/_static/changelog.css
  src/core/.readthedocs.yml
  src/datatable/sphinxext/xcontributors.py
Labels: documentation

#2343 Fix to_int64() functions to take into account size of long
  ci/ext.py
  src/core/python/int.cc
  src/core/python/list.cc
  src/core/python/obj.cc
  src/core/utils/macros.h
Labels: refactor, test

#2344 Fix frame to string conversion on Windows
  src/core/frame/repr/repr_options.cc
  src/core/utils/terminal/terminal.cc
  src/core/utils/terminal/terminal.h
  tests/frame/test-repr-text.py
Labels: bug, refactor, test

#2345 Do not use Popen.wait() in fread
  src/datatable/fread.py
  src/datatable/utils/terminal.py
  tests/fread/test_fread_issues.py
Labels: bug, refactor, test

#2346 Read Excel date values
  docs/releases/v0.11.0.rst
  src/core/column_from_python.cc
  src/datatable/xls.py
  tests/fread/test_xls.py
  tests/models/test_ftrl.py
  tests/test_dt_create.py
  tests/test_dt_stats.py
Labels: fread, improve

#2347 Fix terminal hangs in a multiprocessing pool
  src/datatable/utils/terminal.py
Labels: bug

#2349 Use `with` when working with the multiprocessing pool
  ci/xbuild/compiler.py
  tests/test_parallel.py
Labels: ITA, bug

#2350 Fix sort-related issues
  src/core/column.cc
  src/core/column.h
  src/core/datatablemodule.cc
  src/core/datatablemodule.h
  src/core/expr/eval_context.cc
  src/core/sort.cc
  src/core/sort.h
  src/core/sort_groups.cc
  tests/test_dt_sort.py
Labels: bug, performance, sort

#2352 Improve performance of groupby operation
  src/core/column/column_impl.cc
  src/core/column/column_impl.h
  src/core/expr/head_reduce_binary.cc
  src/core/expr/head_reduce_unary.cc
Labels: groupby, performance

#2353 Unbless
  Makefile
  appveyor.yml
  ci/ext.py
  docs/releases/v0.11.0.rst
  src/core/datatablemodule.cc
  src/core/frame/__repr__.cc
  src/core/frame/repr/repr_options.cc
  src/core/python/obj.cc
  src/core/python/obj.h
  src/datatable/__init__.py
  src/datatable/fread.py
  src/datatable/lib/__init__.py
  src/datatable/options.py
  src/datatable/utils/terminal.py
  src/datatable/utils/typechecks.py
  src/datatable/widget.py
  tests/random_attack.py
  tests/random_driver.py
  tests/test_dt.py
  tests/test_options.py
Labels: improve, refactor

#2355 Improve naming consistency in online documentation
  docs/f-expressions.rst
  docs/using-datatable.rst
Labels: documentation

#2354 Improve Frame's documentation
  docs/_static/xfunction.css
  docs/api/frame.rst
  docs/api/frame/countna.rst
  docs/api/frame/countna1.rst
  docs/api/frame/export_names.rst
  docs/api/frame/names.rst
  src/core/frame/names.cc
  src/core/frame/py_frame.cc
  src/core/frame/stats.cc
  src/datatable/sphinxext/dt_changelog.py
  src/datatable/sphinxext/xfunction.py
  tests/test_dt.py
Labels: documentation

#2359 Docs2
  docs/api/frame.rst
  docs/api/frame/head.rst
  docs/api/frame/key.rst
  docs/api/frame/names.rst
  docs/api/frame/tail.rst
  docs/releases/v0.11.0.rst
  src/core/frame/key.cc
  src/core/frame/names.cc
  src/core/frame/py_frame.cc
  src/core/frame/stats.cc
  src/datatable/sphinxext/dtframe_directive.py
  src/datatable/sphinxext/xfunction.py
  tests/test_keys.py
Labels: documentation, improve

#2360 Added .git_date and .git_diff to dt.build_version
  ci/ext.py
  docs/releases/v0.11.0.rst
  tests/test_dt.py
Labels: ITA, improve

#2361 Exceptions reorganized
  Makefile
  appveyor.yml
  ci/ext.py
  docs/releases/v0.11.0.rst
  src/core/datatablemodule.cc
  src/core/python/args.cc
  src/core/python/obj.cc
  src/core/python/obj.h
  src/core/utils/exceptions.cc
  src/core/utils/exceptions.h
  src/core/utils/terminal/terminal.cc
  src/core/utils/terminal/terminal_style.h
  src/datatable/__init__.py
  src/datatable/exceptions.py
  src/datatable/expr/expr.py
  src/datatable/fread.py
  src/datatable/options.py
  src/datatable/types.py
  src/datatable/utils/misc.py
  src/datatable/utils/typechecks.py
  src/datatable/xls.py
  tests/frame/test-colindex.py
  tests/frame/test-repr-text.py
  tests/fread/test_fread_api.py
  tests/ijby/test-assign-expr.py
  tests/ijby/test-assign-frame.py
  tests/ijby/test-assign.py
  tests/ijby/test-func-unary.py
  tests/ijby/test-math-floating.py
  tests/ijby/test-rowwise.py
  tests/ijby/test-shift.py
  tests/models/test_ftrl.py
  tests/models/test_kfold.py
  tests/munging/test_cast.py
  tests/munging/test_cbind.py
  tests/munging/test_delete.py
  tests/munging/test_dt_cols.py
  tests/munging/test_dt_rows.py
  tests/munging/test_rbind.py
  tests/munging/test_replace.py
  tests/munging/test_str.py
  tests/random_attack.py
  tests/test-import-all.py
  tests/test_dt.py
  tests/test_dt_create.py
  tests/test_f.py
  tests/test_jay.py
  tests/test_join.py
  tests/test_keys.py
  tests/test_options.py
  tests/test_parallel.py
  tests/test_reduce.py
  tests/test_tocsv.py
  tests/test_types.py
Labels: refactor

#2366 Allow `len(DT)` syntax to work
  docs/releases/v0.11.0.rst
  src/core/frame/py_frame.cc
  src/core/frame/py_frame.h
  src/core/python/xobject.cc
  src/core/python/xobject.h
  src/datatable/fread.py
  tests/test_dt.py
Labels: improve

#2364 Adjust complexity calculation for groupby
  src/core/expr/head_reduce_unary.cc
Labels: groupby

#2365 Fix memory mapping on WIndows
  src/core/datatablemodule.cc
  src/core/lib/mman/mman.cc
  src/core/lib/mman/mman.h
  src/core/utils/terminal/terminal.cc
  src/core/utils/terminal/terminal.h
Labels: ITA, improve

#2356 [WIP] work on new sort implementation
  src/core/datatable.h
  src/core/frame/py_frame.cc
  src/core/frame/py_frame.h
  src/core/rowindex.cc
  src/core/rowindex.h
  src/core/rowindex_array.cc
  src/core/rowindex_impl.h
  src/core/rowindex_slice.cc
  src/core/sort/common.h
  src/core/sort/insert-sort.h
  src/core/sort/newsort.cc
  src/core/sort/radix-sort.h
  src/core/sort/sorter.h
  src/core/sort/sorter_bool.h
  src/core/sort/sorter_int.h
  src/core/sort/sorter_multi.h
  src/core/sort/sorter_raw.h
Labels: improve, sort

#2373 Fix typos in xbuild/compiler
  ci/xbuild/compiler.py
Labels: ITA, low priority
