Repository h2oai/datatable, pull requests merged in 2020-05, with the labels that each got.

#2415 Fix warnings issued by msvc for libs, pragmas and some casts
  ci/ext.py
  src/core/buffer.h
  src/core/csv/reader.cc
  src/core/csv/reader_parsers.cc
  src/core/csv/toa.h
  src/core/datatable.cc
  src/core/datatablemodule.cc
  src/core/datatablemodule.h
  src/core/expr/fnary/fnary.cc
  src/core/expr/head_literal_int.cc
  src/core/frame/cast.cc
  src/core/frame/replace.cc
  src/core/frame/repr/html_styles.cc
  src/core/lib/flatbuffers/flatbuffers.h
  src/core/lib/mman/mman.cc
  src/core/lib/parallel_hashmap/phmap.h
  src/core/lib/zlib/deflate.cc
  src/core/lib/zlib/deflate.h
  src/core/lib/zlib/trees.cc
  src/core/lib/zlib/zlib.h
  src/core/lib/zlib/zutil.cc
  src/core/models/dt_ftrl_base.h
  src/core/parallel/thread_pool.cc
  src/core/py_encodings.cc
  src/core/python/args.cc
  src/core/python/pybuffer.cc
  src/core/python/xobject.h
  src/core/rowindex.h
  src/core/rowindex_slice.cc
  src/core/sort.cc
  src/core/sort/sorter.h
  src/core/utils/assert.h
  src/core/utils/exceptions.cc
  src/core/utils/macros.h
  src/core/utils/misc.cc
  src/core/utils/terminal/terminal.cc
  src/core/write/value_writer.cc
  src/core/write/zlib_writer.h
  src/core/wstringcol.cc
Labels: refactor

#2418 Random attack
  .gitignore
  ci/ext.py
  tests/test_dt.py
  tests_random/__init__.py
  tests_random/attacker.py
  tests_random/continuous.py
  tests_random/metaframe.py
  tests_random/utils.py
Labels: refactor

#2419 No pycode in random attacker
  tests_random/attacker.py
  tests_random/metaframe.py
  tests_random/utils.py
Labels: refactor, test

#2424 Implement forks in random attack tests
  tests_random/attacker.py
  tests_random/metaframe.py
  tests_random/utils.py
Labels: test

#2426 Casting a column into its own type is now a no-op
  docs/releases/v0.11.0.rst
  src/core/frame/cast.cc
  tests/munging/test_cast.py
Labels: performance

#2431 Remove workaround of a bug in auditwheel
  ci/Jenkinsfile.groovy
Labels: ITA, refactor

#2430 Switch to C++14 language standard
  ci/ext.py
  docs/install.rst
  src/core/buffer.cc
  src/core/datatablemodule.h
  src/core/frame/repr/terminal_widget.cc
  src/core/models/aggregator.cc
  src/core/models/dt_ftrl.cc
  src/core/python/obj.cc
  src/core/utils/c+++.h
  src/core/utils/misc.h
Labels: ITA, documentation, refactor

#2422 Fix integer related warnings in MSVC, minor refactoring
  .travis.yml
  ci/ext.py
  ci/xbuild/extension.py
  src/core/column/sentinel_fw.cc
  src/core/column/sentinel_str.cc
  src/core/column/view.cc
  src/core/csv/reader.cc
  src/core/csv/reader_parsers.cc
  src/core/expr/head_func_shift.cc
  src/core/frame/join.cc
  src/core/frame/rbind.cc
  src/core/frame/repr/text_column.cc
  src/core/lib/parallel_hashmap/phmap.h
  src/core/py_buffers.cc
  src/core/py_encodings.cc
  src/core/python/args.cc
  src/core/python/pybuffer.cc
  src/core/python/slice.cc
  src/core/rowindex.cc
  src/core/rowindex.h
  src/core/rowindex_array.cc
  src/core/rowindex_slice.cc
  src/core/sort.cc
  src/core/sort/sorter_float.h
  src/core/utils/misc.cc
  src/core/utils/terminal/terminal.cc
  src/core/writebuf.cc
  src/core/wstringcol.cc
Labels: ITA, bug, refactor

#2433 On PPC64 builds prefer installing from wheels
  ci/Jenkinsfile.groovy
Labels: ITA

#2434 Fread encoding= parameter
  docs/install.rst
  docs/releases/v0.11.0.rst
  src/core/csv/reader.cc
  src/core/csv/reader.h
  src/core/csv/reader_fread.cc
  src/core/read/multisource.h
  src/core/read/py_fread.cc
  src/core/read/source.cc
  src/core/read/source.h
  tests/fread/test_fread_api.py
Labels: fread, improve

#2435 Logger class
  src/core/csv/fread.cc
  src/core/csv/reader.cc
  src/core/csv/reader.h
  src/core/csv/reader_arff.cc
  src/core/csv/reader_fread.cc
  src/core/frame/to_csv.cc
  src/core/parallel/monitor_thread.cc
  src/core/parallel/monitor_thread.h
  src/core/parallel/thread_pool.cc
  src/core/parallel/thread_pool.h
  src/core/read/parallel_reader.cc
  src/core/read/preframe.cc
  src/core/read/py_fread.cc
  src/core/read/source.cc
  src/core/utils/logger.cc
  src/core/utils/logger.h
  src/core/write/write_chronicler.cc
  src/core/write/write_chronicler.h
  src/core/write/write_manager.cc
  src/core/write/write_manager.h
  src/datatable/utils/fread.py
  tests/fread/test_fread_issues.py
Labels: improve, refactor

#2437 Create Frame from pandas Categorical
  docs/releases/v0.11.0.rst
  src/core/frame/__init__.cc
  src/core/python/obj.cc
  src/core/python/obj.h
  tests/frame/test-create.py
Labels: improve

#2436 Improve fread EOL detection
  docs/releases/v0.11.0.rst
  src/core/csv/reader_fread.cc
  tests/fread/test_fread_detect.py
Labels: fread, improve

#2439 Support building wheels on Windows
  appveyor.yml
  ci/xbuild/logger.py
  ci/xbuild/wheel.py
Labels: ITA

#2444 Fread download progress
  docs/releases/v0.11.0.rst
  src/core/progress/progress_manager.cc
  src/core/progress/progress_manager.h
  src/core/progress/work.cc
  src/core/progress/work.h
  src/core/python/xobject.cc
  src/core/python/xobject.h
  src/core/read/multisource.cc
  src/core/read/py_read.cc
  src/core/read/source.cc
  src/core/read/source.h
  src/core/utils/exceptions.cc
  src/core/utils/logger.cc
  src/core/utils/temporary_file.cc
  src/core/utils/temporary_file.h
  src/datatable/utils/fread.py
  tests/fread/test_fread_api.py
Labels: fread, improve

#2445 Fread PreColumn refactoring
  src/core/_dt.h
  src/core/csv/reader_arff.h
  src/core/csv/reader_fread.cc
  src/core/csv/reader_fread.h
  src/core/csv/reader_parsers.h
  src/core/read/fread/fread_thread_context.cc
  src/core/read/input_column.cc
  src/core/read/input_column.h
  src/core/read/output_column.cc
  src/core/read/output_column.h
  src/core/read/preframe.cc
  src/core/read/preframe.h
Labels: fread, refactor

#2448 csv-reading refactoring
  src/core/_dt.h
  src/core/csv/fread.cc
  src/core/csv/reader_fread.cc
  src/core/csv/reader_fread.h
  src/core/csv/reader_parsers.cc
  src/core/csv/reader_parsers.h
  src/core/jay/save_jay.cc
  src/core/read/fread/fread_parallel_reader.cc
  src/core/read/fread/fread_parallel_reader.h
  src/core/read/fread/fread_thread_context.cc
  src/core/read/fread/fread_thread_context.h
  src/core/read/fread/fread_tokenizer.h
  src/core/read/parse_context.cc
  src/core/read/parse_context.h
  src/core/read/thread_context.cc
  src/core/read/thread_context.h
  src/core/write/write_manager.cc
  src/core/writebuf.cc
  src/core/writebuf.h
  src/core/wstringcol.cc
  tests/fread/test_fread_issues.py
  tests/fread/test_fread_small.py
Labels: fread, refactor

#2442 Wheel generation adjustments
  appveyor.yml
  ci/Jenkinsfile.groovy
Labels: ITA

#2449 Fix master builds on Jenkins
  ci/Jenkinsfile.groovy
Labels: ITA

#2450 Update docs and release notes wrt Windows support
  README.md
  docs/install.rst
  docs/releases/v0.11.0.rst
Labels: documentation

#2455 Temporarily downgrade sphinx on readthedocs
  requirements_docs.txt
Labels: ITA, documentation

#2459 Fread gather NA counts while reading
  docs/releases/v0.11.0.rst
  src/core/_dt.h
  src/core/column/column_impl.h
  src/core/column/rbound.cc
  src/core/csv/reader_fread.cc
  src/core/csv/reader_parsers.cc
  src/core/csv/reader_parsers.h
  src/core/encodings.cc
  src/core/encodings.h
  src/core/py_encodings.cc
  src/core/py_encodings.h
  src/core/read/fread/fread_parallel_reader.cc
  src/core/read/fread/fread_thread_context.cc
  src/core/read/fread/fread_thread_context.h
  src/core/read/input_column.cc
  src/core/read/input_column.h
  src/core/read/output_column.cc
  src/core/read/output_column.h
  src/core/read/parallel_reader.cc
  src/core/read/parse_context.cc
  src/core/read/parse_context.h
  src/core/read/parsers/parse_string.cc
  src/core/read/preframe.cc
  src/core/read/preframe.h
  src/core/read/thread_context.cc
  src/core/read/thread_context.h
  src/core/stats.cc
  src/core/writebuf.cc
  src/core/writebuf.h
  tests/fread/test_fread_small.py
Labels: fread

#2461 Fix slow reading of string columns by fread
  docs/install.rst
  src/core/csv/fread.cc
  src/core/csv/reader_fread.cc
  src/core/read/fread/fread_parallel_reader.cc
  src/core/read/fread/fread_thread_context.cc
  src/core/read/fread/fread_thread_context.h
  src/core/read/parse_context.cc
  src/core/read/parse_context.h
  src/core/read/parsers/parse_string.cc
  src/core/read/thread_context.cc
  src/core/writebuf.cc
  src/core/writebuf.h
  tests/fread/test_fread_issues.py
Labels: fread
