Repository h2oai/datatable, pull requests merged in 2020-10, with the labels that each got.

#2673 Improve options documentation
  docs/api/exceptions.rst
  docs/api/frame/key.rst
  docs/api/frame/names.rst
  docs/api/index-api.rst
  docs/api/internal.rst
  docs/api/math.rst
  docs/api/models.rst
  docs/api/models/Ftrl/alpha.rst
  docs/api/models/Ftrl/beta.rst
  docs/api/models/Ftrl/interactions.rst
  docs/api/models/Ftrl/lambda1.rst
  docs/api/models/Ftrl/lambda2.rst
  docs/api/models/Ftrl/mantissa_nbits.rst
  docs/api/models/Ftrl/model_type.rst
  docs/api/models/Ftrl/negative_class.rst
  docs/api/models/Ftrl/nepochs.rst
  docs/api/options.rst
  docs/api/options/debug.rst
  docs/api/options/debug/arg_max_size.rst
  docs/api/options/debug/enabled.rst
  docs/api/options/debug/logger.rst
  docs/api/options/debug/report_args.rst
  docs/api/options/display.rst
  docs/api/options/display/allow_unicode.rst
  docs/api/options/display/head_nrows.rst
  docs/api/options/display/interactive.rst
  docs/api/options/display/max_column_width.rst
  docs/api/options/display/max_nrows.rst
  docs/api/options/display/tail_nrows.rst
  docs/api/options/display/use_colors.rst
  docs/api/options/frame.rst
  docs/api/options/frame/names_auto_index.rst
  docs/api/options/frame/names_auto_prefix.rst
  docs/api/options/fread.rst
  docs/api/options/fread/log.rst
  docs/api/options/fread/log/anonymize.rst
  docs/api/options/fread/log/escape_unicode.rst
  docs/api/options/nthreads.rst
  docs/api/options/progress.rst
  docs/api/options/progress/allow_interruption.rst
  docs/api/options/progress/callback.rst
  docs/api/options/progress/clear_on_success.rst
  docs/api/options/progress/enabled.rst
  docs/api/options/progress/min_duration.rst
  docs/api/options/progress/updates_per_second.rst
  docs/develop/documentation.rst
  src/core/call_logger.cc
  src/core/csv/reader.cc
  src/core/expr/py_join.cc
  src/core/frame/__repr__.cc
  src/core/frame/key.cc
  src/core/frame/names.cc
  src/core/frame/repr/repr_options.cc
  src/core/models/py_ftrl.cc
  src/core/parallel/thread_pool.cc
  src/core/progress/_options.cc
  src/datatable/exceptions.py
  src/datatable/utils/fread.py
  tests/fread/test-fread-api.py
Labels: documentation, improve

#2665 Comparison between SQL and datatable
  docs/_static/iris.csv
  docs/manual/comparison_with_sql.rst
  docs/manual/index-manual.rst
Labels: documentation, new feature

#2687 [DOC] update to docs highlighting difference in row selection
  docs/manual/comparison_with_rdatatable.rst
Labels: documentation

#2699 Improve aggregator docs
  src/core/models/aggregate.cc
Labels: documentation, improve

#2698 Improve exception sections in the docs
  docs/api/frame/__getitem__.rst
  src/core/frame/names.cc
  src/core/models/aggregate.cc
  src/core/models/py_ftrl.cc
  src/core/set_funcs.cc
  src/core/str/py_str.cc
Labels: documentation, improve

#2705 Fix a memory leak
  Makefile
  docs/releases/v1.0.0.rst
  src/core/python/args.cc
  src/core/python/xobject.h
Labels: bug

#2659 Na position sort
  docs/releases/v1.0.0.rst
  src/core/expr/eval_context.cc
  src/core/expr/eval_context.h
  src/core/expr/py_sort.cc
  src/core/expr/py_sort.h
  src/core/sort.cc
  src/core/sort.h
  src/core/sort_groups.cc
  src/core/sort_insert.cc
  tests/ijby/test-sort.py
Labels: sort

#2710 Style ReadTheDocs pop-out menu
  docs/_static/wren.css
Labels: documentation

#2716 Nested menu indicators in the documentation
  docs/_static/wren.css
Labels: documentation
