Repository h2oai/datatable, pull requests merged in 2020-01, with the labels that each got.

#2278 Changelogs update
  datatable/sphinxext/dt_changelog.py
  docs/_static/changelog.css
  docs/changelog.rst
  docs/changelog/v0.10.0.rst
  docs/changelog/v0.10.1.rst
  docs/changelog/v0.11.0.rst
  docs/changelog/v0.9.0.rst
  docs/conf.py
Labels: documentation, improve

#2279 Added changelog for version 0.8.0
  CHANGELOG.md
  datatable/sphinxext/dt_changelog.py
  docs/_static/changelog.css
  docs/_static/code.css
  docs/api/frame.rst
  docs/changelog.rst
  docs/changelog/v0.11.0.rst
  docs/changelog/v0.8.0.rst
  docs/changelog/v0.9.0.rst
Labels: documentation, improve

#2276 Use xbuild instead of setup.py
  .travis.yml
  Makefile
  ci/setup_utils.py
  ext.py
  pyproject.toml
  requirements_docs.txt
  requirements_extra.txt
  requirements_optional.txt
  requirements_tests.txt
Labels: ITA, improve

#2284 Fix PPC build
  ext.py
Labels: ITA

#2286 Another PPC build fix
  ext.py
Labels: ITA

#2288 Added Sphinx directive ..ref-context
  datatable/sphinxext/ref_context.py
  docs/changelog/v0.10.1.rst
  docs/conf.py
Labels: documentation, new feature

#2290 New Sphinx directive: xfunction
  c/frame/cbind.cc
  c/frame/names.cc
  c/frame/replace.cc
  c/frame/to_csv.cc
  datatable/sphinxext/xfunction.py
  docs/_static/code.css
  docs/_static/xfunction.css
  docs/api/frame.rst
  docs/api/frame/cbind.rst
  docs/api/frame/colindex.rst
  docs/api/frame/replace.rst
  docs/api/frame/to_csv.rst
  docs/conf.py
Labels: documentation, new feature

#2292 Fix a leak in aggregate_exemplars()
  c/models/aggregator.cc
Labels: bug, low priority

#2294 Improve documentation of cbind()
  c/frame/cbind.cc
  datatable/sphinxext/xfunction.py
  docs/_static/code.css
  docs/_static/xfunction.css
  docs/api/frame.rst
  docs/conf.py
  docs/index.rst
  docs/manual/name_mangling.rst
  docs/using-datatable.rst
  requirements_docs.txt
Labels: documentation

#2295 Add exception class InvalidOperationError
  c/datatablemodule.cc
  c/frame/cbind.cc
  c/utils/exceptions.cc
  c/utils/exceptions.h
  datatable/__init__.py
  datatable/utils/typechecks.py
  docs/changelog/v0.11.0.rst
  tests/munging/test_cbind.py
Labels: improve

#2289 Improve progress reporting for FTRL
  c/models/dt_ftrl.cc
  c/models/utils.h
Labels: improve

#2297 Refactor and fix an edge case bug in Aggregator
  c/models/aggregator.cc
  c/models/column_convertor.h
  tests/models/test_aggregate.py
Labels: bug, refactor, test

#2296 Documentation for colindex()
  c/datatable.cc
  c/datatablemodule.cc
  c/frame/names.cc
  c/utils/exceptions.cc
  c/utils/exceptions.h
  datatable/sphinxext/xfunction.py
  datatable/utils/typechecks.py
  docs/_static/xfunction.css
  docs/api/frame/colindex.rst
  docs/changelog/v0.11.0.rst
  docs/conf.py
  docs/f-expressions.rst
  tests/frame/test-colindex.py
  tests/ijby/test-assign-expr.py
  tests/munging/test_delete.py
  tests/munging/test_dt_cols.py
  tests/munging/test_str.py
  tests/test_dt.py
  tests/test_f.py
Labels: documentation, improve

#2299 Improve documentation for copy()
  c/frame/py_frame.cc
  docs/api/frame.rst
  docs/api/frame/copy.rst
  tests/frame/test-copy.py
  tests/test_dt.py
Labels: documentation

#2300 Add dt.options.progress.allow_interruption option
  c/parallel/monitor_thread.cc
  c/progress/_options.cc
  c/progress/_options.h
  tests/test_options.py
Labels: improve

#2291 Compile datatable with MSVC
  Makefile
  c/models/dt_ftrl.cc
  c/types.h
  ci/xbuild/compiler.py
  ci/xbuild/logger.py
  ext.py
Labels: ITA, improve

#2302 Xfunction Examples section
  datatable/sphinxext/dtframe_directive.py
  datatable/sphinxext/xfunction.py
  datatable/utils/typechecks.py
  docs/_static/code.css
  docs/api/math.rst
  docs/using-datatable.rst
Labels: documentation

#2306 AppVeyor integration
  ci/xbuild/compiler.py
Labels: ITA

#2307 Changelog references
  docs/_static/changelog.css
  docs/api/frame/cbind.rst
  docs/api/frame/colindex.rst
  docs/api/frame/copy.rst
  docs/api/frame/replace.rst
  docs/api/frame/to_csv.rst
  src/datatable/sphinxext/dt_changelog.py
  src/datatable/sphinxext/xfunction.py
Labels: documentation, improve

#2310 Changelog 0.7.0
  CHANGELOG.md
  docs/changelog.rst
  docs/index.rst
  docs/release-history.rst
  docs/releases/v0.10.0.rst
  docs/releases/v0.10.1.rst
  docs/releases/v0.11.0.rst
  docs/releases/v0.7.0.rst
  docs/releases/v0.8.0.rst
  docs/releases/v0.9.0.rst
Labels: documentation, refactor

#2311 Converted changelogs 0.6.0, 0.5.0, 0.4.0
  CHANGELOG.md
  docs/release-history.rst
  docs/releases/v0.4.0.rst
  docs/releases/v0.5.0.rst
  docs/releases/v0.6.0.rst
Labels: documentation, refactor

#2313 Added changelogs for versions 0.3.2 and 0.3.1
  CHANGELOG.md
  docs/release-history.rst
  docs/releases/v0.3.1.rst
  docs/releases/v0.3.2.rst
Labels: documentation, refactor

#2309 [WIP] Finishing AppVeyor Integration
  appveyor.yml
  ci/xbuild/compiler.py
Labels: ITA

#2314 Added changelog for version 0.3.0
  CHANGELOG.md
  docs/release-history.rst
  docs/releases/v0.3.0.rst
Labels: documentation, refactor

#2315 Changelogs 0.2.x
  CHANGELOG.md
  MANIFEST.in
  README.md
  ci/Jenkinsfile.groovy
  ci/README.md
  ci/default.groovy
  docs/release-history.rst
  docs/releases/v0.2.1.rst
  docs/releases/v0.2.2.rst
Labels: documentation, refactor

#2316 Wheel links in the changelog
  docs/_static/changelog.css
  docs/releases/v0.10.0.rst
  docs/releases/v0.10.1.rst
  docs/releases/v0.3.0.rst
  docs/releases/v0.3.1.rst
  docs/releases/v0.3.2.rst
  docs/releases/v0.4.0.rst
  docs/releases/v0.5.0.rst
  docs/releases/v0.6.0.rst
  docs/releases/v0.7.0.rst
  docs/releases/v0.8.0.rst
  docs/releases/v0.9.0.rst
  src/datatable/sphinxext/dt_changelog.py
  src/datatable/sphinxext/dtframe_directive.py
  src/datatable/sphinxext/xfunction.py
  src/datatable/sphinxext/xnodes.py
Labels: documentation, improve

#2287 [WIP] Clean up datatable version generation
  .gitignore
  Makefile
  VERSION.txt
  ci/Jenkinsfile-build-docker-images.groovy
  ci/Jenkinsfile.groovy
  ci/README.md
  ci/default.groovy
  ci/xbuild/wheel.py
  docs/conf.py
  ext.py
  src/datatable/__init__.py
  src/datatable/__version__.py
  tests/fread/test_fread_api.py
  tests/random_attack.py
  tests/random_driver.py
  tests/test-import-all.py
  tests/test_dt.py
  tests/test_reduce.py
Labels: ITA

#2319 Pip install datatable from the source tree works again
  Makefile
  ext.py
  pyproject.toml
  tests/test_reduce.py
Labels: ITA

#2320 Remove obsolete/unused CI files
  .gitattributes
  .travis.yml
  MANIFEST.in
  Makefile
  appveyor.yml
  ci/Jenkinsfile.groovy
  ci/__init__.py
  ci/asan-env.sh
  ci/asan-pip.py
  ci/asan-python.c
  ci/default.groovy
  ci/ext.py
  ci/make_fast.py
  ci/setup_utils.py
  pyproject.toml
  setup.py
Labels: ITA, refactor

#2322 Use only official manylinux docker images in tests
  Makefile
  ci/Dockerfile-centos7.in
  ci/Dockerfile-ubuntu.in
  ci/Jenkinsfile-build-docker-images.groovy
  ci/Jenkinsfile.groovy
  ci/generate_expected_shas.sh
Labels: ITA, refactor

#2327 Add Logger2 to xbuild
  ci/xbuild/__init__.py
  ci/xbuild/logger.py
  src/core/column/const.cc
  src/core/column/sentinel_str.cc
  src/core/expr/fnary/rowmean.cc
  src/core/expr/fnary/rowminmax.cc
  src/core/expr/fnary/rowsd.cc
  src/core/expr/fnary/rowsum.cc
  src/core/expr/head_func.cc
  src/core/models/aggregator.cc
Labels: ITA

#2329 Sphinx extension Xcontributors
  ci/gh.py
  docs/_static/changelog.css
  docs/conf.py
  docs/releases/v0.10.0.rst
  docs/releases/v0.10.1.rst
  docs/releases/v0.11.0.rst
  src/datatable/sphinxext/xcontributors.py
Labels: documentation, new feature

#2330 Automatic contributors list generation
  AUTHORS.md
  ci/gh.py
  docs/_static/changelog.css
  docs/_static/code.css
  docs/release-history.rst
  docs/releases/contributors.rst
  docs/releases/v0.10.0.rst
  docs/releases/v0.10.1.rst
  docs/releases/v0.11.0.rst
  docs/releases/v0.2.2.rst
  docs/releases/v0.3.0.rst
  docs/releases/v0.3.1.rst
  docs/releases/v0.3.2.rst
  docs/releases/v0.4.0.rst
  docs/releases/v0.5.0.rst
  docs/releases/v0.6.0.rst
  docs/releases/v0.7.0.rst
  docs/releases/v0.8.0.rst
  docs/releases/v0.9.0.rst
  src/datatable/sphinxext/dt_changelog.py
  src/datatable/sphinxext/xcontributors.py
  src/datatable/sphinxext/xnodes.py
Labels: documentation, new feature

#2331 Use custom pip repo for PPC machines
  ci/Jenkinsfile.groovy
Labels: ITA

#2317 Treat infinite values as missings in Aggregator
  src/core/models/aggregator.cc
  src/core/models/aggregator.h
  src/core/models/column_convertor.h
  src/core/models/utils.h
  tests/models/test_aggregate.py
Labels: improve, test

#2332 Fix some warnings reported by Codacy
  src/datatable/__init__.py
  src/datatable/expr/math.py
  src/datatable/sphinxext/dt_changelog.py
  src/datatable/sphinxext/dtframe_directive.py
  src/datatable/sphinxext/xfunction.py
  src/datatable/types.py
  src/datatable/widget.py
  tests/frame/test-repr-html.py
  tests/fread/test_fread_api.py
  tests/fread/test_fread_issues.py
  tests/ijby/test-assign-frame.py
  tests/ijby/test-assign.py
  tests/ijby/test-func-unary.py
  tests/ijby/test-math-floating.py
  tests/ijby/test-rowwise.py
  tests/ijby/test-shift.py
  tests/models/test_ftrl.py
  tests/test_dt_expr.py
  tests/test_jay.py
  tests/test_reduce.py
Labels: low priority, refactor

#2333 Fix compilation warnings in clang 11.0
  ci/xbuild/extension.py
  src/core/column/sentinel_fw.cc
  src/core/csv/reader_parsers.h
  src/core/expr/py_by.cc
  src/core/expr/py_join.cc
  src/core/expr/py_sort.cc
  src/core/expr/py_update.cc
  src/core/expr/workframe.h
  src/core/python/args.h
  src/core/python/obj.cc
Labels: refactor

#2337 Use -fdebug-macro option for clang only
  ci/ext.py
Labels: ITA

#2340 Fix gcc warnings on linux
  src/core/expr/eval_context.cc
  src/core/frame/integrity_check.cc
  src/core/parallel/monitor_thread.cc
  src/core/utils/terminal/terminal.cc
Labels: refactor
