Repository h2oai/datatable, pull requests merged in 2020-08, with the labels that each got.

#2561 Added a test for rbinding a frame and then saving to Jay
  tests/munging/test_rbind.py
Labels: test

#2560 Encode unsafe characters in URLs passed to fread
  docs/releases/v0.11.0.rst
  src/core/python/dict.cc
  src/core/python/dict.h
  src/core/read/source.cc
  src/datatable/utils/fread.py
Labels: fread

#2558 Do not do rereading step in fread
  Makefile
  src/core/csv/fread.cc
  src/core/csv/reader.cc
  src/core/csv/reader.h
  src/core/csv/reader_fread.cc
  src/core/csv/reader_fread.h
  src/core/csv/reader_parsers.cc
  src/core/csv/reader_parsers.h
  src/core/parallel/api.h
  src/core/parallel/parallel_for_ordered.cc
  src/core/progress/work.cc
  src/core/read/fread/fread_parallel_reader.cc
  src/core/read/fread/fread_thread_context.cc
  src/core/read/fread/fread_thread_context.h
  src/core/read/input_column.cc
  src/core/read/input_column.h
  src/core/read/output_column.cc
  src/core/read/output_column.h
  src/core/read/parallel_reader.cc
  src/core/read/parallel_reader.h
  src/core/read/preframe.cc
  src/core/read/preframe.h
  src/core/read/thread_context.cc
  src/core/read/thread_context.h
  src/core/tests/test_parallel_for.cc
  src/core/tests/test_parallel_for_ordered.cc
  src/core/utils/tests.h
  tests/fread/test_fread_large.py
  tests/fread/test_fread_small.py
Labels: fread, improve

#2559 Implement qcut() function
  docs/api/index-api.rst
  docs/releases/v0.11.0.rst
  src/core/column.cc
  src/core/column.h
  src/core/column/const.cc
  src/core/column/const.h
  src/core/column/qcut.h
  src/core/datatablemodule.cc
  src/core/datatablemodule.h
  src/core/expr/head_func.cc
  src/core/expr/head_func.h
  src/core/expr/head_func_qcut.cc
  src/core/expr/op.h
  src/core/models/aggregator.cc
  src/datatable/__init__.py
  src/datatable/expr/expr.py
  tests/ijby/test-cut.py
  tests/ijby/test-qcut.py
  tests/models/test_aggregate.py
  tests/munging/test_str.py
Labels: new feature, test

#2565 Fix warnings produced by Clang 10
  ci/ext.py
  src/core/column/qcut.h
  src/core/column/rbound.cc
  src/core/column_from_python.cc
  src/core/csv/reader_fread.cc
  src/core/expr/fnary/rowmean.cc
  src/core/expr/fnary/rowsd.cc
  src/core/expr/head_reduce_binary.cc
  src/core/expr/head_reduce_unary.cc
  src/core/lib/zlib/adler32.cc
  src/core/lib/zlib/deflate.cc
  src/core/lib/zlib/deflate.h
  src/core/lib/zlib/trees.cc
  src/core/lib/zlib/zutil.h
  src/core/models/aggregator.cc
  src/core/models/dt_ftrl.cc
  src/core/models/dt_ftrl.h
  src/core/models/utils.h
  src/core/py_buffers.cc
  src/core/read/parallel_reader.cc
  src/core/read/preframe.cc
  src/core/stats.cc
  src/core/utils/misc.cc
  src/core/write/write_manager.cc
Labels: refactor

#2563 Documentation on row functions
  docs/manual/index-manual.rst
  docs/manual/row_functions.rst
Labels: documentation

#2566 FExpr_Column
  src/core/expr/declarations.h
  src/core/expr/eval_context.cc
  src/core/expr/expr.cc
  src/core/expr/expr.h
  src/core/expr/fexpr.cc
  src/core/expr/fexpr.h
  src/core/expr/fexpr_column.h
  src/core/expr/fexpr_column_asarg.cc
  src/core/expr/fexpr_column_asattr.cc
  src/core/expr/fexpr_func.cc
  src/core/expr/fexpr_func.h
  src/core/expr/fnary/pyfn.cc
  src/core/expr/funary/pyfn.cc
  src/core/expr/head.h
  src/core/expr/head_func.cc
  src/core/expr/head_func.h
  src/core/expr/head_func_cut.cc
  src/core/expr/head_func_shift.cc
  src/core/expr/head_literal.h
  src/core/expr/head_literal_string.cc
  src/core/expr/namespace.cc
  src/core/frame/__getitem__.cc
  src/core/frame/names.cc
  src/core/python/obj.cc
  src/core/python/obj.h
  src/datatable/expr/reduce.py
  tests/frame/test-colindex.py
  tests/test_dt.py
  tests/test_f.py
Labels: refactor

#2569 Do not use Sphinx 3.2.0 for doc builds
  docs/api/dt/qcut.rst
  requirements_docs.txt
Labels: documentation

#2567 FExpr literals
  src/core/expr/expr.cc
  src/core/expr/expr.h
  src/core/expr/fexpr.cc
  src/core/expr/fexpr_literal.cc
  src/core/expr/fexpr_literal.h
  src/core/expr/fexpr_literal_bool.cc
  src/core/expr/fexpr_literal_float.cc
  src/core/expr/fexpr_literal_int.cc
  src/core/expr/fexpr_literal_none.cc
  src/core/expr/fexpr_literal_range.cc
  src/core/expr/fexpr_literal_sliceall.cc
  src/core/expr/fexpr_literal_sliceint.cc
  src/core/expr/fexpr_literal_slicestr.cc
  src/core/expr/fexpr_literal_string.cc
  src/core/expr/fexpr_literal_type.cc
  src/core/expr/head.h
  src/core/expr/head_literal.h
  src/core/expr/head_literal_range.cc
  src/core/expr/workframe.cc
  src/core/expr/workframe.h
  src/core/ltype.cc
  tests/models/test_ftrl.py
  tests/munging/test_dt_cols.py
  tests/munging/test_dt_rows.py
  tests/test_dt.py
  tests/test_f.py
Labels: refactor

#2570 Fexpr ifelse
  src/core/expr/fexpr_func.cc
  src/core/expr/fexpr_func.h
  src/core/expr/fexpr_ifelse.cc
  src/core/expr/head_func.cc
  src/core/expr/head_func.h
  src/core/expr/op.h
  src/datatable/expr/expr.py
Labels: refactor

#2571 FExpr for arithmetic binary operators
  docs/api/dt/ifelse.rst
  docs/api/fexpr.rst
  docs/api/fexpr/__add__.rst
  docs/api/index-api.rst
  src/core/datatablemodule.cc
  src/core/expr/fbinary/arithmetic.cc
  src/core/expr/fbinary/bimaker.cc
  src/core/expr/fbinary/bimaker.h
  src/core/expr/fbinary/fexpr__add__.cc
  src/core/expr/fbinary/fexpr__floordiv__.cc
  src/core/expr/fbinary/fexpr__mod__.cc
  src/core/expr/fbinary/fexpr__mul__.cc
  src/core/expr/fbinary/fexpr__pow__.cc
  src/core/expr/fbinary/fexpr__sub__.cc
  src/core/expr/fbinary/fexpr__truediv__.cc
  src/core/expr/fbinary/fexpr_binaryop.cc
  src/core/expr/fbinary/fexpr_binaryop.h
  src/core/expr/fexpr.cc
  src/core/expr/fexpr.h
  src/core/expr/fexpr_ifelse.cc
  src/core/expr/fnary/pyfn.cc
  src/core/expr/funary/pyfn.cc
  src/core/expr/head_func_cut.cc
  src/core/expr/head_func_shift.cc
  src/core/expr/namespace.cc
  src/datatable/__init__.py
  src/datatable/expr/expr.py
  src/datatable/sphinxext/xfunction.py
  tests/test_dt.py
Labels: refactor

#2572 collect tests for arithmetic binary operators
  docs/api/dt/cut.rst
  docs/api/dt/ifelse.rst
  docs/api/dt/qcut.rst
  docs/api/dt/shift.rst
  docs/api/fexpr/__add__.rst
  tests/expr/fbinary/test__add__.py
  tests/expr/fbinary/test__floordiv__.py
  tests/expr/fbinary/test__mod__.py
  tests/expr/fbinary/test__mul__.py
  tests/expr/fbinary/test__pow__.py
  tests/expr/fbinary/test__sub__.py
  tests/expr/fbinary/test__truediv__.py
  tests/expr/test-cut.py
  tests/expr/test-ifelse.py
  tests/expr/test-qcut.py
  tests/expr/test-shift.py
  tests/test-docs.py
  tests/test_dt_expr.py
Labels: documentation

#2574 Relational operators converted into fexprs
  src/core/column/isna.h
  src/core/expr/fbinary/bimaker.cc
  src/core/expr/fbinary/bimaker.h
  src/core/expr/fbinary/fexpr__compare__.cc
  src/core/expr/fbinary/fexpr__compare__.h
  src/core/expr/fbinary/fexpr__eq__.cc
  src/core/expr/fbinary/fexpr__ge__.cc
  src/core/expr/fbinary/fexpr__gt__.cc
  src/core/expr/fbinary/fexpr__le__.cc
  src/core/expr/fbinary/fexpr__lt__.cc
  src/core/expr/fbinary/fexpr__ne__.cc
  src/core/expr/fbinary/relational.cc
  src/core/expr/fexpr.cc
  src/core/expr/funary/floating.cc
  src/core/expr/op.h
  src/datatable/expr/expr.py
  tests/test_dt.py
  tests/test_f.py
Labels: refactor

#2573 qcut() converted into FExpr
  src/core/expr/fexpr_qcut.cc
  src/core/expr/head_func.cc
  src/core/expr/head_func.h
  src/core/expr/head_func_cut.cc
  src/core/expr/head_func_qcut.cc
  src/core/expr/op.h
  src/datatable/expr/expr.py
  tests/expr/test-qcut.py
Labels: refactor

#2575 Attempt to fix an error in test_atomic
  src/core/tests/test_atomic.cc
Labels: test

#2576 cut() converted into FExpr
  docs/api/dt/cut.rst
  src/core/column/qcut.h
  src/core/expr/fexpr_cut.cc
  src/core/expr/fexpr_qcut.cc
  src/core/expr/head_func.cc
  src/core/expr/head_func.h
  src/core/expr/head_func_cut.cc
  src/core/expr/op.h
  src/datatable/expr/expr.py
  tests/expr/test-cut.py
Labels: documentation, refactor, test

#2577 Added documentation for creating new FExprs
  docs/develop/create-fexpr.rst
  docs/develop/index-develop.rst
  src/core/expr/!readme.md
  src/datatable/sphinxext/xcode.py
Labels: documentation

#2578 Add checks to allow compilation on FreeBSD
  src/core/buffer.cc
  src/core/parallel/semaphore.h
  src/core/utils/macros.h
  src/core/utils/misc.h
Labels: ITA

#2579 FExprs_Frame, FExpr_List and FExpr_Dict
  src/core/expr/declarations.h
  src/core/expr/eval_context.cc
  src/core/expr/expr.cc
  src/core/expr/expr.h
  src/core/expr/fexpr.cc
  src/core/expr/fexpr_dict.cc
  src/core/expr/fexpr_dict.h
  src/core/expr/fexpr_frame.cc
  src/core/expr/fexpr_frame.h
  src/core/expr/fexpr_list.cc
  src/core/expr/fexpr_list.h
  src/core/expr/head.h
Labels: refactor

#2580 Allow ND aggregations with a fixed radius
  src/core/models/aggregator.cc
  src/core/models/aggregator.h
  tests/models/test_aggregate.py
Labels: new feature, test

#2581 py::XArgs class
  docs/develop/create-fexpr.rst
  src/core/_dt.h
  src/core/call_logger.cc
  src/core/call_logger.h
  src/core/datatablemodule.cc
  src/core/datatablemodule.h
  src/core/expr/fexpr_cut.cc
  src/core/expr/fexpr_ifelse.cc
  src/core/expr/fexpr_qcut.cc
  src/core/python/arg.cc
  src/core/python/arg.h
  src/core/python/args.cc
  src/core/python/args.h
  src/core/python/dict.h
  src/core/python/xargs.cc
  src/core/python/xargs.h
  tests/expr/test-cut.py
  tests/expr/test-ifelse.py
  tests/expr/test-qcut.py
Labels: improve, refactor

#2582 Unify test file names
  docs/api/dt/rbind.rst
  docs/api/fexpr/__add__.rst
  docs/api/frame/key.rst
  docs/develop/documentation.rst
  tests/expr/fbinary/test-add.py
  tests/expr/fbinary/test-floordiv.py
  tests/expr/fbinary/test-mod.py
  tests/expr/fbinary/test-mul.py
  tests/expr/fbinary/test-pow.py
  tests/expr/fbinary/test-sub.py
  tests/expr/fbinary/test-truediv.py
  tests/fread/test-fread-api.py
  tests/fread/test-fread-detect.py
  tests/fread/test-fread-issues.py
  tests/fread/test-fread-large.py
  tests/fread/test-fread-random.py
  tests/fread/test-fread-small.py
  tests/fread/test-xls.py
  tests/models/test-aggregate.py
  tests/models/test-ftrl.py
  tests/models/test-kfold.py
  tests/munging/test-cast.py
  tests/munging/test-cbind.py
  tests/munging/test-delete.py
  tests/munging/test-dt-cols.py
  tests/munging/test-dt-combo.py
  tests/munging/test-dt-rows.py
  tests/munging/test-rbind.py
  tests/munging/test-replace.py
  tests/munging/test-str.py
  tests/test-dt-expr.py
  tests/test-dt-stats.py
  tests/test-dt.py
  tests/test-f.py
  tests/test-jay.py
  tests/test-join.py
  tests/test-keys.py
  tests/test-options.py
  tests/test-parallel.py
  tests/test-reduce.py
  tests/test-sets.py
  tests/test-sphinxext-dtframe.py
  tests/test-tocsv.py
  tests/test-types.py
  tests/test-utils-misc.py
Labels: test

#2584 Implement function round()
  docs/api/math.rst
  docs/api/math/round.rst
  docs/releases/v0.11.0.rst
  src/core/expr/fexpr_func_unary.cc
  src/core/expr/fexpr_func_unary.h
  src/core/expr/fexpr_round.cc
  src/datatable/math.py
  tests/expr/math/test-round.py
Labels: new feature

#2585 ..xclass directive
  docs/_static/code.css
  docs/_static/xfunction.css
  docs/api/frame.rst
  src/core/frame/py_frame.cc
  src/datatable/sphinxext/xfunction.py
Labels: documentation

#2588 Updated documentation for Frame
  docs/_static/xfunction.css
  docs/api/dt/fread.rst
  docs/api/dt/iread.rst
  docs/api/dt/repeat.rst
  docs/api/frame.rst
  docs/api/frame/__copy__.rst
  docs/api/frame/__getstate__.rst
  docs/api/frame/__len__.rst
  docs/api/frame/__repr__.rst
  docs/api/frame/__sizeof__.rst
  docs/api/frame/__str__.rst
  docs/api/frame/cbind.rst
  docs/api/frame/colindex.rst
  docs/api/frame/copy.rst
  docs/api/frame/export_names.rst
  docs/api/frame/head.rst
  docs/api/frame/keys.rst
  docs/api/frame/ltypes.rst
  docs/api/frame/materialize.rst
  docs/api/frame/ncols.rst
  docs/api/frame/nrows.rst
  docs/api/frame/replace.rst
  docs/api/frame/shape.rst
  docs/api/frame/source.rst
  docs/api/frame/stype.rst
  docs/api/frame/stypes.rst
  docs/api/frame/tail.rst
  docs/api/frame/to_csv.rst
  docs/api/frame/to_dict.rst
  docs/api/frame/to_jay.rst
  docs/api/frame/to_list.rst
  docs/api/frame/to_numpy.rst
  docs/api/frame/to_pandas.rst
  docs/api/frame/to_tuples.rst
  docs/api/frame/view.rst
  src/core/frame/__repr__.cc
  src/core/frame/__sizeof__.cc
  src/core/frame/py_frame.cc
  src/datatable/sphinxext/xfunction.py
Labels: documentation

#2590 Expand tests for binary operations
  tests/expr/fbinary/test-add.py
  tests/expr/fbinary/test-floordiv.py
  tests/expr/fbinary/test-mod.py
  tests/expr/fbinary/test-mul.py
  tests/expr/fbinary/test-pow.py
  tests/expr/fbinary/test-sub.py
  tests/expr/fbinary/test-truediv.py
Labels: test

#2591 Sphinx: auto-rebuild pages when their sources are modified
  src/datatable/sphinxext/xfunction.py
Labels: documentation
