Repository h2oai/datatable, pull requests merged in 2021-05, with the labels that each got.

#2951 Add linear model documentation
  docs/api/models.rst
  docs/api/models/Ftrl/params.rst
  docs/api/models/LinearModel/__init__.rst
  docs/api/models/LinearModel/double_precision.rst
  docs/api/models/LinearModel/eta0.rst
  docs/api/models/LinearModel/eta_decay.rst
  docs/api/models/LinearModel/eta_drop_rate.rst
  docs/api/models/LinearModel/eta_schedule.rst
  docs/api/models/LinearModel/fit.rst
  docs/api/models/LinearModel/is_fitted.rst
  docs/api/models/LinearModel/labels.rst
  docs/api/models/LinearModel/lambda1.rst
  docs/api/models/LinearModel/lambda2.rst
  docs/api/models/LinearModel/model.rst
  docs/api/models/LinearModel/model_type.rst
  docs/api/models/LinearModel/negative_class.rst
  docs/api/models/LinearModel/nepochs.rst
  docs/api/models/LinearModel/params.rst
  docs/api/models/LinearModel/predict.rst
  docs/api/models/LinearModel/reset.rst
  docs/api/models/LinearModel/seed.rst
  docs/api/models/ftrl.rst
  docs/api/models/linear_model.rst
  src/core/models/py_ftrl.cc
  src/core/models/py_linearmodel.cc
  src/core/models/py_linearmodel.h
Labels: documentation

#2953 Add background for literal text in docs
  docs/_static/wren.css
Labels: documentation

#2952 Ensure linear model doesn't crash in the presence of the progress bar
  docs/api/models/linear_model.rst
  src/core/models/dt_linearmodel.cc
  src/core/models/py_linearmodel.cc
Labels: documentation, segfault

#2954 Fix code.literal style spillovers
  docs/_ext/xfunction.py
  docs/_ext/xnodes.py
  docs/_static/wren.css
  docs/_static/xfunction.css
Labels: documentation

#2955 Minor correction to LinearModel docs
  src/core/models/py_linearmodel.cc
Labels: documentation

#2967 Add fread option to prevent parsing date columns
  src/core/csv/reader.cc
  src/core/csv/reader.h
  src/core/read/parsers/ptype_iterator.cc
  tests/test-options.py
  tests/types/test-date32.py
Labels: fread
