Repository h2oai/datatable, pull requests merged in 2021-04, with the labels that each got.

#2919 Convert keyed frame to pandas
  docs/releases/v1.0.0.rst
  src/core/frame/to_pandas.cc
  src/core/python/tuple.cc
  tests/frame/test-to-pandas.py
Labels: improve

#2934 Fix archiving columns of void type
  src/core/read/output_column.cc
Labels: fread

#2933 Implement learning rate schedules for linear model
  src/core/models/dt_linearmodel.cc
  src/core/models/dt_linearmodel.h
  src/core/models/dt_linearmodel_types.h
  src/core/models/py_linearmodel.cc
  src/core/models/py_linearmodel.h
  tests/models/test-linearmodel.py
Labels: improve, test

#2942 Documentation directive x-comparison-table
  docs/_ext/xcomparisontable.py
  docs/_static/x-comparison-table.css
  docs/conf.py
  docs/develop/documentation.rst
  docs/manual/comparison_with_pandas.rst
Labels: documentation

#2941 [DOC] Select/filter Data in datatable
  docs/manual/index-manual.rst
  docs/manual/select_and_filter_data.rst
Labels: documentation

#2948 py::XArgs can now be used to declare methods
  src/core/_dt.h
  src/core/call_logger.cc
  src/core/call_logger.h
  src/core/datatablemodule.cc
  src/core/datatablemodule.h
  src/core/frame/cbind.cc
  src/core/frame/py_frame.cc
  src/core/frame/py_frame.h
  src/core/frame/to_arrow.cc
  src/core/frame/to_csv.cc
  src/core/frame/to_pandas.cc
  src/core/python/xargs.cc
  src/core/python/xargs.h
  src/core/python/xobject.cc
  src/core/python/xobject.h
  src/core/utils/macros.h
  tests/test-dt.py
  tests/test-options.py
  tests/test-tocsv.py
Labels: refactor
