Repository h2oai/datatable, pull requests merged in 2021-07, with the labels that each got.

#3043 Post-release documentation update
  docs/_ext/changelog.py
  docs/releases/index-releases.rst
  docs/releases/v1.0.0.rst
  docs/releases/v1.1.0.rst
Labels: documentation

#3036 Updated documentation on creating FExprs,
  docs/_ext/xcode.py
  docs/develop/create-fexpr.rst
Labels: documentation

#3047 Move documentation, part 2
  docs/api/dt/fread.rst
  docs/api/dt/iread.rst
  docs/api/models/LinearModel/params.rst
  docs/api/models/linear_model.rst
  docs/api/type.rst
  docs/api/type/max.rst
  docs/api/type/min.rst
  docs/api/type/name.rst
  src/core/datatablemodule.cc
  src/core/datatablemodule.h
  src/core/documentation.h
  src/core/models/py_linearmodel.cc
  src/core/read/multisource.cc
  src/core/read/multisource.h
  src/core/read/py_fread.cc
  src/core/types/py_type.cc
  tests/fread/test-fread-api.py
Labels: refactor

#3042 Bring Linux and macOS builds to AppVeyor
  .travis.yml
  appveyor.yml
  ci/appveyor.yml
Labels: ITA

#3049 fix for expected behavior of min max operations
  src/core/expr/head_reduce_unary.cc
  src/datatable/expr/reduce.py
  tests/dt/test-minmax.py
Labels: Beginner task, FIX, improve

#3059 Refactor creating column from list
  docs/api/type/bool8.rst
  src/core/column/cast_to_bool.cc
  src/core/column_from_python.cc
  src/core/python/int.cc
  src/core/python/obj.cc
  src/core/python/obj.h
  tests/dt/test-cut.py
  tests/frame/test-create.py
  tests/munging/test-cast.py
  tests/test-dt-expr.py
  tests/test-dt-stats.py
  tests/types/test-bool8.py
  tests/types/test-float.py
  tests/types/test-int.py
Labels: refactor

#3068 Forbid sep='-'|'+'|'.' in fread
  docs/releases/v1.1.0.rst
  src/core/csv/reader.cc
  src/datatable/xls.py
  tests/fread/test-fread-api.py
  tests/fread/test-xls.py
Labels: fread

#3078 Move some of the documentation into the docs/ folder
  docs/api/dt/by.rst
  docs/api/dt/count.rst
  docs/api/dt/first.rst
  docs/api/dt/init_styles.rst
  docs/api/dt/intersect.rst
  docs/api/dt/join.rst
  docs/api/dt/last.rst
  docs/api/dt/max.rst
  docs/api/dt/mean.rst
  docs/api/dt/median.rst
  docs/api/dt/min.rst
  docs/api/dt/repeat.rst
  docs/api/dt/sd.rst
  docs/api/dt/setdiff.rst
  docs/api/dt/sort.rst
  docs/api/dt/sum.rst
  docs/api/dt/symdiff.rst
  docs/api/dt/union.rst
  docs/api/dt/unique.rst
  docs/api/dt/update.rst
  docs/api/math/atan2.rst
  docs/api/math/copysign.rst
  docs/api/math/fmod.rst
  docs/api/math/hypot.rst
  docs/api/math/ldexp.rst
  docs/api/math/logaddexp.rst
  docs/api/math/logaddexp2.rst
  docs/api/math/pow.rst
  docs/api/models/aggregate.rst
  docs/api/namespace.rst
  docs/api/time/day.rst
  docs/api/time/day_of_week.rst
  docs/api/time/hour.rst
  docs/api/time/minute.rst
  docs/api/time/month.rst
  docs/api/time/nanosecond.rst
  docs/api/time/second.rst
  docs/api/time/year.rst
  docs/api/time/ymd.rst
  docs/api/time/ymdt.rst
  src/core/datatablemodule.cc
  src/core/datatablemodule.h
  src/core/documentation.h
  src/core/expr/fbinary/math.cc
  src/core/expr/head_reduce_unary.cc
  src/core/expr/namespace.cc
  src/core/expr/py_by.cc
  src/core/expr/py_join.cc
  src/core/expr/py_sort.cc
  src/core/expr/py_update.cc
  src/core/expr/time/fexpr_day_of_week.cc
  src/core/expr/time/fexpr_hour_min_sec.cc
  src/core/expr/time/fexpr_year_month_day.cc
  src/core/expr/time/fexpr_ymd.cc
  src/core/expr/time/fexpr_ymdt.cc
  src/core/frame/repeat.cc
  src/core/frame/repr/html_styles.cc
  src/core/models/aggregate.cc
  src/core/set_funcs.cc
Labels: documentation, refactor

#3076 fread almost empty file
  docs/releases/v1.1.0.rst
  src/core/read/fread/fread_parallel_reader.cc
  tests/fread/test-fread-issues.py
Labels: fread

#3077 Rename type list32->arr32 and list64->arr64
  docs/api/type/arr32.rst
  docs/api/type/arr64.rst
  docs/api/type/list32.rst
  docs/api/type/list64.rst
  src/core/documentation.h
  src/core/stype.cc
  src/core/stype.h
  src/core/types/py_type.cc
  src/core/types/py_type.h
  src/core/types/type.cc
  src/core/types/type.h
  src/core/types/type_array.cc
  src/core/types/type_array.h
  src/core/types/typeimpl.cc
  src/core/types/typeimpl.h
  tests/types/test-array.py
  tests/types/test-list.py
Labels: refactor

#3079 Move `Ftrl` documentation to `/docs` folder
  docs/api/models/Ftrl/__init__.rst
  docs/api/models/Ftrl/alpha.rst
  docs/api/models/Ftrl/beta.rst
  docs/api/models/Ftrl/colname_hashes.rst
  docs/api/models/Ftrl/colnames.rst
  docs/api/models/Ftrl/double_precision.rst
  docs/api/models/Ftrl/feature_importances.rst
  docs/api/models/Ftrl/fit.rst
  docs/api/models/Ftrl/interactions.rst
  docs/api/models/Ftrl/labels.rst
  docs/api/models/Ftrl/lambda1.rst
  docs/api/models/Ftrl/lambda2.rst
  docs/api/models/Ftrl/mantissa_nbits.rst
  docs/api/models/Ftrl/model.rst
  docs/api/models/Ftrl/model_type.rst
  docs/api/models/Ftrl/model_type_trained.rst
  docs/api/models/Ftrl/nbins.rst
  docs/api/models/Ftrl/negative_class.rst
  docs/api/models/Ftrl/nepochs.rst
  docs/api/models/Ftrl/params.rst
  docs/api/models/Ftrl/predict.rst
  docs/api/models/Ftrl/reset.rst
  docs/api/models/LinearModel/params.rst
  docs/api/models/ftrl.rst
  docs/api/models/linear_model.rst
  src/core/documentation.h
  src/core/models/py_ftrl.cc
  src/core/models/py_linearmodel.cc
Labels: documentation, refactor

#3084 Move `LinearModel` documentation to `/docs` folder
  docs/api/models/LinearModel/__init__.rst
  docs/api/models/LinearModel/double_precision.rst
  docs/api/models/LinearModel/eta0.rst
  docs/api/models/LinearModel/eta_decay.rst
  docs/api/models/LinearModel/eta_drop_rate.rst
  docs/api/models/LinearModel/eta_schedule.rst
  docs/api/models/LinearModel/fit.rst
  docs/api/models/LinearModel/is_fitted.rst
  docs/api/models/LinearModel/labels.rst
  docs/api/models/LinearModel/lambda1.rst
  docs/api/models/LinearModel/lambda2.rst
  docs/api/models/LinearModel/model.rst
  docs/api/models/LinearModel/model_type.rst
  docs/api/models/LinearModel/negative_class.rst
  docs/api/models/LinearModel/nepochs.rst
  docs/api/models/LinearModel/predict.rst
  docs/api/models/LinearModel/reset.rst
  docs/api/models/LinearModel/seed.rst
  src/core/documentation.h
  src/core/models/py_linearmodel.cc
Labels: documentation, refactor

#3085 fix conversion of nans to/from datatable Frame
  docs/releases/v1.1.0.rst
  src/core/column_from_python.cc
  src/core/frame/to_numpy.cc
  tests/frame/test-create.py
  tests/frame/test-to-numpy.py
  tests/frame/test-to-pandas.py
  tests/ijby/test-rowwise.py
  tests/test-reduce.py
Labels: API change

#3086 Added config file for readthedocs
  .readthedocs.yaml
  docs/_ext/xpython.py
Labels: documentation

#3089 Sort void column
  docs/releases/v1.1.0.rst
  src/core/sort.cc
  tests/ijby/test-sort.py
Labels: sort

#3098 Fix fread bug with quoteRule becoming too large
  src/core/csv/reader_fread.cc
  src/core/read/fread/fread_thread_context.cc
  src/core/read/parsers/parse_string.cc
  src/core/read/parsers/ptype_iterator.cc
  tests/fread/test-fread-issues.py
  tests/fread/test-fread-small.py
Labels: fread

#3102 Fix latent column materialization routine
  docs/releases/v1.1.0.rst
  src/core/column/latent.cc
  tests/dt/test-qcut.py
Labels: segfault

#3105 Fix multi-sort with void columns
  docs/releases/v1.1.0.rst
  src/core/sort.cc
  tests/types/test-void.py
Labels: sort

#3111 Fix group by operation on void columns
  docs/releases/v1.1.0.rst
  src/core/column.cc
  src/core/sort.cc
  tests/types/test-void.py
Labels: bug, groupby

#3127 Fix using set functions with void columns
  src/core/rowindex.cc
  src/core/set_funcs.cc
  tests/types/test-void.py
Labels: bug

#3125 [DOCS] Update docs with `Type`
  docs/manual/select_and_filter_data.rst
Labels: documentation
