Repository h2oai/datatable, pull requests merged in 2021-01, with the labels that each got.

#2820 Improve cut() to support binning based on the interval edges
  docs/releases/v1.0.0.rst
  src/core/column/cut.h
  src/core/expr/fexpr_cut.cc
  src/core/ltype.cc
  src/core/ltype.h
  src/core/stype.cc
  tests/expr/test-cut.py
Labels: improve, test

#2827 Allow reusing cut FExpr's
  src/core/column/cut.h
  src/core/expr/fexpr_cut.cc
  tests/expr/test-cut.py
Labels: bug

#2831 Tests for pandas/numpy conversion moved to separate files
  docs/api/frame/to_numpy.rst
  docs/api/frame/to_pandas.rst
  tests/frame/test-to-numpy.py
  tests/frame/test-to-pandas.py
  tests/test-dt.py
Labels: refactor, test

#2830 Fix segfault when renaming untouched columns
  src/core/frame/names.cc
  tests/test-dt.py
Labels: segfault

#2840 Prevent overflow in FTRL predictions
  src/core/models/dt_ftrl.cc
  src/core/models/dt_ftrl.h
Labels: bug, improve

#2835 [DOC] Examples for dt.rbind()
  src/core/frame/rbind.cc
Labels: documentation

#2836 [DOC] Examples for sd()
  src/core/expr/head_reduce_unary.cc
Labels: documentation

#2832 [DOC] Examples for symdiff()
  src/core/set_funcs.cc
Labels: documentation

#2837 [DOC] Examples for dt.shift()
  src/core/expr/head_func_shift.cc
Labels: documentation

#2834 [DOC] Examples for setdiff()
  src/core/set_funcs.cc
Labels: documentation

#2833 [DOC] Examples for intersect()
  src/core/set_funcs.cc
Labels: documentation
