Repository h2oai/datatable, pull requests merged in 2021-02, with the labels that each got.

#2826 [ENH] f-expression with list/tuple accepted in `j` selector
  docs/api/namespace/__getitem__.rst
  docs/releases/v1.0.0.rst
  src/core/expr/fexpr_list.cc
  src/core/expr/namespace.cc
  tests/munging/test-dt-cols.py
  tests/test-dt-expr.py
  tests/test-f.py
Labels: Beginner task, DT[i，j，...]

#2851 Change required version of xlrd package
  requirements_extra.txt
Labels: test

#2866 [DOC] Example for `dt.rowcount`
  src/core/expr/fnary/rowcount.cc
Labels: documentation

#2870 [DOC] for `dt.rowmin()`
  src/core/expr/fnary/rowminmax.cc
Labels: documentation

#2864 [DOC] Example for `dt.rowall`
  src/core/expr/fnary/rowall.cc
Labels: documentation

#2865 [DOC] Example for `dt.rowany`
  src/core/expr/fnary/rowany.cc
Labels: documentation

#2869 [DOC] Rowmax
  src/core/expr/fnary/rowfirstlast.cc
  src/core/expr/fnary/rowminmax.cc
Labels: documentation

#2868 [DOC] Example for `dt.rowlast`
  src/core/expr/fnary/rowfirstlast.cc
Labels: documentation

#2867 Dt rowfirst
  src/core/expr/fnary/rowfirstlast.cc
Labels: documentation

#2861 [DOC] Example for `dt.repeat`
  src/core/frame/repeat.cc
Labels: documentation

#2859 Implement creating a date32 column from a numpy datetime64 array
  src/core/column/date_from_months.cc
  src/core/column/date_from_months.h
  src/core/column/date_from_weeks.cc
  src/core/column/date_from_weeks.h
  src/core/column/date_from_years.cc
  src/core/column/date_from_years.h
  src/core/py_buffers.cc
  tests/types/test-date32.py
Labels: new feature
