Repository h2oai/datatable, pull requests merged in 2021-10, with the labels that each got.

#3038 make .nunique callable from inside the square brackets
  docs/api/dt/nunique.rst
  docs/api/index-api.rst
  docs/releases/v1.1.0.rst
  src/core/cstring.cc
  src/core/cstring.h
  src/core/documentation.h
  src/core/expr/head_reduce_unary.cc
  src/core/expr/op.h
  src/datatable/__init__.py
  src/datatable/expr/__init__.py
  src/datatable/expr/expr.py
  src/datatable/expr/reduce.py
  tests/dt/test-nunique.py
  tests/test-reduce.py
Labels: improve

#3058 Add `FExpr.as_type()` method equivalent to `dt.as_type()`
  docs/api/fexpr.rst
  docs/api/fexpr/as_type.rst
  docs/releases/v1.1.0.rst
  src/core/documentation.h
  src/core/expr/fexpr.cc
  src/core/expr/fexpr.h
  tests/test-f.py
Labels: improve, documentation

#3174 Fix wheel generation on macOS Big Sur, switch to `macos-bigsur` image on AppVeyor
  ci/appveyor.yml
  ci/xbuild/wheel.py
  src/core/column/categorical.cc
Labels: ITA

#3193 Fix some issues caused by #3192
  src/core/write/write_manager.cc
Labels: segfault
