Repository h2oai/datatable, pull requests merged in 2021-09, with the labels that each got.

#3157 Implement casting array columns into obj type
  src/core/column/cast.h
  src/core/column/cast_to_obj.cc
  src/core/frame/to_numpy.cc
  src/core/types/type_object.cc
  tests/types/test-array.py
Labels: improve

#3158 Implement `CategoricalColumn_Impl` and support for basic operations
  src/core/column.cc
  src/core/column/categorical.cc
  src/core/column/categorical.h
  src/core/column/column_impl.h
  src/core/column/range.h
  src/core/frame/repr/text_column.cc
  src/core/models/dt_ftrl.cc
  src/core/stype.cc
  src/core/stype.h
  src/core/types/type_categorical.cc
  src/core/types/type_categorical.h
  src/datatable/types.py
  tests/test-dt.py
  tests/types/test-categorical.py
  tests/types/test-type.py
Labels: test, new feature

#3161 Fix support for `.max_column_width` in Jupyter notebooks
  docs/releases/v1.1.0.rst
  src/core/frame/__repr__.cc
  src/core/frame/repr/html_widget.h
Labels: bug

#3167 Support numpy scalars in `Frame.replace()`
  docs/releases/v1.1.0.rst
  src/core/frame/replace.cc
  tests/munging/test-replace.py
Labels: improve

#3170 Miscellaneous improvements to tests
  tests/conftest.py
  tests/frame/test-create.py
  tests/fread/test-fread-large.py
Labels: test

#3171 [DOCS] Transforming Data
  docs/manual/index-manual.rst
  docs/manual/transform_data.rst
Labels: documentation
