Repository h2oai/datatable, pull requests merged in 2021-03, with the labels that each got.

#2872 Refactor row* functions to use FExprs
  docs/_ext/xfunction.py
  docs/api/dt/rowall.rst
  docs/api/dt/rowany.rst
  docs/api/dt/rowcount.rst
  docs/api/dt/rowfirst.rst
  docs/api/dt/rowlast.rst
  docs/api/dt/rowmax.rst
  docs/api/dt/rowmean.rst
  docs/api/dt/rowmin.rst
  docs/api/dt/rowsd.rst
  docs/api/dt/rowsum.rst
  src/core/datatablemodule.cc
  src/core/datatablemodule.h
  src/core/expr/fexpr_list.cc
  src/core/expr/fexpr_list.h
  src/core/expr/fnary/fnary.cc
  src/core/expr/fnary/fnary.h
  src/core/expr/fnary/pyfn.cc
  src/core/expr/fnary/rowall.cc
  src/core/expr/fnary/rowany.cc
  src/core/expr/fnary/rowcount.cc
  src/core/expr/fnary/rowfirstlast.cc
  src/core/expr/fnary/rowmean.cc
  src/core/expr/fnary/rowminmax.cc
  src/core/expr/fnary/rowsd.cc
  src/core/expr/fnary/rowsum.cc
  src/core/expr/head_func.cc
  src/core/expr/head_func.h
  src/core/expr/head_func_nary.cc
  src/core/expr/op.h
  src/core/python/xargs.cc
  src/core/python/xargs.h
  src/datatable/expr/expr.py
  tests/ijby/test-rowwise.py
Labels: refactor

#2882 [DOC] Link to Fread Manual for usage examples
  docs/manual/fread_examples.rst
  src/core/read/py_fread.cc
Labels: documentation

#2881 [DOC] Examples for dt.rowsum()
  src/core/expr/fnary/rowsum.cc
Labels: documentation

#2878 FTRL refactoring, fix debug builds
  docs/develop/create-fexpr.rst
  src/core/column.h
  src/core/column/cast_to_bool.cc
  src/core/column/date_from_months.cc
  src/core/column/date_from_weeks.cc
  src/core/column/date_from_years.cc
  src/core/column/func_binary.h
  src/core/column/isclose.h
  src/core/column/isna.h
  src/core/column/npmasked.cc
  src/core/expr/fbinary/fexpr__truediv__.cc
  src/core/expr/fbinary/math.cc
  src/core/expr/fexpr_round.cc
  src/core/frame/join.cc
  src/core/models/dt_ftrl.cc
  src/core/models/dt_ftrl.h
  src/core/models/label_encode.cc
  src/core/models/label_encode.h
  src/core/models/py_ftrl.cc
  src/core/models/py_ftrl.h
  src/core/py_buffers.cc
  src/core/sort/sorter_float.h
  src/core/sort/sorter_int.h
  src/core/utils/macros.h
  tests/models/test-ftrl.py
Labels: ITA, improve, refactor

#2880 [DOC] Examples for dt.rowmean()
  src/core/expr/fnary/rowmean.cc
Labels: documentation

#2879 [DOC] Examples for rowsd
  src/core/expr/fnary/rowsd.cc
Labels: documentation

#2839 [DOC] Examples for dt.sort()
  src/core/expr/py_sort.cc
Labels: documentation

#2887 Fix installation from source
  ci/ext.py
  ci/xbuild/wheel.py
  docs/releases/v1.0.0.rst
Labels: ITA

#2896 Fix Ftrl segfault when trained on one binomial class only
  ci/ext.py
  src/core/models/dt_ftrl.cc
  tests/__init__.py
  tests/models/test-ftrl.py
Labels: improve, segfault, test

#2908 Make integrity check to use both abs and rel tolerances on statistics
  src/core/stats.cc
  tests/test-dt-stats.py
Labels: bug, test

#2914 Do data shuffling when fitting a linear model
  src/core/models/aggregate.cc
  src/core/models/dt_linearmodel.cc
  src/core/models/dt_linearmodel.h
  src/core/models/dt_linearmodel_types.h
  src/core/models/py_linearmodel.cc
  src/core/models/py_linearmodel.h
  src/core/models/utils.cc
  src/core/models/utils.h
  tests/models/test-linearmodel.py
Labels: improve, test

#2918 Move Frame::to_pandas() into a separate file
  docs/api/frame/to_pandas.rst
  src/core/frame/py_frame.cc
  src/core/frame/py_frame.h
  src/core/frame/to_numpy.cc
  src/core/frame/to_pandas.cc
Labels: refactor
