Repository h2oai/datatable, pull requests merged in 2022-12, with the labels that each got.

#3387 Add support for Python `3.11`
  ci/Jenkinsfile.groovy
  ci/appveyor.yml
  ci/ext.py
  docs/releases/v1.1.0.rst
  src/core/_dt.h
  src/core/buffer.cc
  src/core/call_logger.h
  src/core/column/const_na.cc
  src/core/lib/pythoncapi/pythoncapi_compat.h
  src/core/ltype.cc
  src/core/ltype.h
  src/core/python/namedtuple.cc
  src/core/python/obj.cc
  src/core/python/obj.h
  src/core/python/python.h
  src/core/python/tuple.cc
  src/core/python/xobject.cc
  src/core/utils/exceptions.h
Labels: improve, ITA

#3395 Enable macOS on AppVeyor for Python `3.11`
  ci/appveyor.yml
Labels: improve, ITA

#3396 Add `dt.prod()` test for a grouped column, `by()` docs adjustment
  docs/api/dt/by.rst
  docs/api/dt/f.rst
  tests/test-groups.py
Labels: test, documentation

#3393 Refactor `.extend()` and `.remove()` to use `FExpr`
  src/core/column/sumprod.h
  src/core/expr/fexpr.cc
  src/core/expr/fexpr_extend_remove.cc
  src/core/expr/fexpr_extend_remove.h
  tests/test-f.py
Labels: improve, refactor
