Repository h2oai/datatable, pull requests merged in 2022-09, with the labels that each got.

#3347 `FExpr`/`Expr` adjustments in the docs
  docs/api/dt/corr.rst
  docs/api/dt/count.rst
  docs/api/dt/countna.rst
  docs/api/dt/cov.rst
  docs/api/dt/first.rst
  docs/api/dt/last.rst
  docs/api/dt/max.rst
  docs/api/dt/mean.rst
  docs/api/dt/median.rst
  docs/api/dt/min.rst
  docs/api/dt/nunique.rst
  docs/api/dt/prod.rst
  docs/api/dt/rowlast.rst
  docs/api/dt/sd.rst
  docs/api/dt/sum.rst
Labels: documentation

#3349 Minor docs adjustments to `cumcount()` and `ngroup()`
  docs/api/fexpr.rst
  docs/api/index-api.rst
Labels: documentation

#3348 Fix cumulative functions when invoked on the latent columns
  src/core/column/cumminmax.h
  src/core/column/cumsumprod.h
  src/core/column/latent.cc
  src/core/column/latent.h
  src/core/expr/eval_context.cc
  src/core/expr/fexpr_fillna.cc
  tests/dt/test-cumminmax.py
  tests/dt/test-cumprod.py
  tests/dt/test-cumsum.py
  tests/dt/test-fillna.py
Labels: FIX

#3351 Fix status badge in documentation
  docs/index.rst
Labels: documentation

#3333 [ENH] Column aliasing
  docs/api/fexpr.rst
  docs/api/fexpr/alias.rst
  docs/releases/v1.1.0.rst
  src/core/documentation.h
  src/core/expr/fexpr.cc
  src/core/expr/fexpr.h
  src/core/expr/fexpr_alias.cc
  src/core/expr/fexpr_alias.h
  tests/dt/test-alias.py
  tests/test-f.py
Labels: test, documentation, new feature

#3357 Build and test Python `3.7` wheels on Windows
  ci/appveyor.yml
Labels: ITA

#3361 Adjustments to fread documenation
  docs/api/dt/fread.rst
Labels: documentation

#3362 Fix casting `void` columns to categoricals
  src/core/column.cc
  src/core/column.h
  src/core/column/latent.h
  src/core/frame/repr/text_column.cc
  src/core/types/type_categorical.cc
  tests/types/test-categorical.py
Labels: test, refactor, FIX
