Repository h2oai/datatable, pull requests merged in 2022-04, with the labels that each got.

#3254 Fix selection of `time64` columns
  docs/releases/v1.1.0.rst
  src/core/expr/fexpr_literal_type.cc
  tests/types/test-date32.py
  tests/types/test-time64.py
Labels: bug, test

#3250 Make `tempdir` parameter be honored for memory limited `fread()` operation
  docs/releases/v1.1.0.rst
  src/core/csv/reader.cc
  src/core/csv/reader.h
  src/core/read/preframe.cc
  src/core/utils/temporary_file.cc
  src/core/utils/temporary_file.h
Labels: bug

#3256 Rearrange items in changelog
  docs/releases/v1.1.0.rst
Labels: documentation

#3261 Predict missing on missing values in linear model
  src/core/models/dt_linearmodel.cc
  tests/models/test-linearmodel.py
Labels: bug

#3263 Simplify `models.LinearModel` test
  tests/models/test-linearmodel.py
Labels: test

#3266 Minor corrections to documentation
  docs/develop/create-fexpr.rst
  docs/releases/v1.1.0.rst
  docs/start/install.rst
Labels: documentation

#3265 Add `.nunique()` and `.countna()` methods to `FExpr`
  docs/api/fexpr.rst
  docs/api/fexpr/countna.rst
  docs/api/fexpr/nunique.rst
  docs/releases/v1.1.0.rst
  src/core/documentation.h
  src/core/expr/fexpr.cc
  src/core/expr/fexpr.h
  tests/test-f.py
  tests/test-reduce.py
Labels: documentation

#3270 Fix shifting grouped columns when `n=0`
  docs/releases/v1.0.0.rst
  docs/releases/v1.1.0.rst
  src/core/expr/head_func_shift.cc
  tests/dt/test-shift.py
Labels: bug
