Repository h2oai/datatable, pull requests merged in 2022-07, with the labels that each got.

#3306 Add `DT_DISABLE` to control thread pool dependencies
  src/core/column/column_impl.cc
  src/core/column/sentinel_str.cc
  src/core/frame/replace.cc
  src/core/parallel/api.h
  src/core/parallel/job_idle.cc
  src/core/parallel/job_shutdown.cc
  src/core/parallel/parallel_for_ordered.cc
  src/core/parallel/parallel_for_static.h
  src/core/parallel/thread_pool.cc
  src/core/parallel/thread_pool.h
  src/core/parallel/thread_team.cc
  src/core/parallel/thread_worker.cc
  src/core/str/utils.cc
  src/core/str/utils.h
  src/core/utils/assert.h
Labels: refactor, new feature

#3312 Improve documentation for `first()` and `last()`
  docs/api/dt/first.rst
  docs/api/dt/last.rst
  src/core/expr/fexpr_frame.cc
Labels: documentation

#3314 Add support for `date32` and `time64` types in `cummin()` and `cummax()`
  src/core/expr/fexpr_cumminmax.cc
  tests/dt/test-cumminmax.py
Labels: improve

#3316 Fix search functionality for sphinx `4.*`
  docs/_theme/search.html
  requirements_docs.txt
Labels: documentation, FIX

#3317 Clean-up `dt.nunique()` internals
  src/core/expr/head_reduce_unary.cc
Labels: refactor

#3318 Support void grouped columns in `dt.nunique()`
  src/core/expr/head_reduce_unary.cc
  tests/dt/test-nunique.py
Labels: improve, test

#3310 [ENH] Add `cumcount()` and `ngroup()` functions
  docs/api/dt/cumcount.rst
  docs/api/dt/ngroup.rst
  docs/api/index-api.rst
  docs/releases/v1.1.0.rst
  src/core/column/cumcountngroup.h
  src/core/documentation.h
  src/core/expr/fexpr_cumcountngroup.cc
  src/datatable/__init__.py
  tests/dt/test-cumcountngroup.py
Labels: new feature

#3319 Make Frame's method `.sum()` and `dt.sum()` reducer to return consistent column types
  docs/api/dt/count.rst
  docs/api/dt/sum.rst
  docs/api/frame/sum.rst
  docs/api/type.rst
  docs/releases/v1.1.0.rst
  src/core/column/rbound.cc
  src/core/expr/head_reduce_unary.cc
  src/core/rowindex_array.cc
  src/core/stats.cc
  src/core/stats.h
  tests/ijby/test-sort.py
  tests/test-dt-stats.py
  tests/test-reduce.py
Labels: improve, consistency

#3320 Improve docs for `cumcount()` and `ngroups()`
  docs/api/dt/cumcount.rst
  docs/api/dt/ngroup.rst
Labels: improve, documentation

#3323 Improve documentation on "Using datatable"
  docs/api/frame.rst
  docs/start/using-datatable.rst
Labels: documentation

#3324 Change `RowIndex` from `ARR64` to `ARR32` when creating new labels for classification
  src/core/models/label_encode.cc
  src/core/rowindex.h
Labels: refactor

#3321 Switch to macOS Monterey on AppVeyor and remove dependency on `distutils`
  ci/appveyor.yml
  ci/xbuild/wheel.py
Labels: improve, ITA
