Repository h2oai/datatable, pull requests merged in 2022-08, with the labels that each got.

#3325 Support freading from public S3 buckets
  docs/api/dt/fread.rst
  docs/releases/v1.1.0.rst
  src/core/read/multisource.cc
  src/core/read/source.cc
  tests/fread/test-fread-api.py
  tests/fread/test-fread-large.py
Labels: improve

#3327 Switch to `manylinux2014` image on `x86_64` and to py38 for debug wheels
  ci/Jenkinsfile.groovy
  docs/start/install.rst
Labels: improve, ITA

#3328 Improve test coverage on AppVeyor
  ci/appveyor.yml
  ci/ext.py
  src/core/frame/names.cc
  src/core/python/obj.h
  src/core/read/parsers/parse_bool.cc
  src/core/read/parsers/parse_date.cc
  src/core/read/parsers/parse_time.cc
  src/core/tests/test_atomic.cc
  src/core/tests/test_barrier.cc
  src/core/tests/test_parallel_for.cc
  src/core/tests/test_parallel_for_ordered.cc
  src/core/tests/test_progress.cc
  src/core/tests/test_shared_mutex.cc
  src/core/types/type.h
  src/core/utils/terminal/terminal_stream.cc
  src/core/utils/terminal/terminal_stream.h
  src/core/utils/tests.cc
  src/core/utils/tests.h
  tests/test-parallel.py
Labels: test, refactor, ITA

#3332 Fix signatures of the `dt` functions referenced in the `FExpr` API
  docs/api/fexpr/count.rst
  docs/api/fexpr/countna.rst
  docs/api/fexpr/cummax.rst
  docs/api/fexpr/cummin.rst
  docs/api/fexpr/cumprod.rst
  docs/api/fexpr/cumsum.rst
  docs/api/fexpr/first.rst
  docs/api/fexpr/last.rst
  docs/api/fexpr/max.rst
  docs/api/fexpr/mean.rst
  docs/api/fexpr/median.rst
  docs/api/fexpr/min.rst
  docs/api/fexpr/nunique.rst
  docs/api/fexpr/prod.rst
  docs/api/fexpr/rowall.rst
  docs/api/fexpr/rowany.rst
  docs/api/fexpr/rowargmax.rst
  docs/api/fexpr/rowargmin.rst
  docs/api/fexpr/rowcount.rst
  docs/api/fexpr/rowfirst.rst
  docs/api/fexpr/rowlast.rst
  docs/api/fexpr/rowmax.rst
  docs/api/fexpr/rowmean.rst
  docs/api/fexpr/rowmin.rst
  docs/api/fexpr/rowsd.rst
  docs/api/fexpr/rowsum.rst
  docs/api/fexpr/sd.rst
  docs/api/fexpr/shift.rst
  docs/api/fexpr/sum.rst
Labels: bug, documentation

#3311 [ENH] Add `dt.fillna()` function to impute missing values
  docs/api/dt/fillna.rst
  docs/api/fexpr.rst
  docs/api/fexpr/fillna.rst
  docs/api/index-api.rst
  docs/manual/comparison_with_rdatatable.rst
  docs/releases/v1.1.0.rst
  src/core/documentation.h
  src/core/expr/fexpr.cc
  src/core/expr/fexpr.h
  src/core/expr/fexpr_fillna.cc
  src/datatable/__init__.py
  tests/dt/test-fillna.py
  tests/test-f.py
Labels: new feature

#3334 Add shortcuts for grouped columns in `cummin()` and `cummax()`
  src/core/expr/fexpr_cumminmax.cc
  src/core/expr/fexpr_cumsumprod.cc
  src/core/expr/fexpr_fillna.cc
Labels: improve, refactor

#3338 Support custom separators in `Frame.to_csv()`
  docs/api/frame/to_csv.rst
  docs/releases/v1.1.0.rst
  src/core/frame/to_csv.cc
  src/core/write/csv_writer.cc
  src/core/write/output_options.h
  src/core/write/value_writer.cc
  src/core/write/write_manager.cc
  src/core/write/write_manager.h
  src/core/write/writing_context.cc
  src/core/write/writing_context.h
  src/core/writebuf.h
  tests/frame/test-tocsv.py
Labels: improve

#3343 Quote missing values in `.to_csv()` when `quoting="all"`
  docs/api/frame/to_csv.rst
  docs/releases/v1.1.0.rst
  src/core/write/value_writer.cc
  tests/frame/test-tocsv.py
Labels: bug
