Repository h2oai/datatable, pull requests merged in 2022-02, with the labels that each got.

#3234 Fix a bug in the gradient calculation for the linear model
  docs/releases/v1.1.0.rst
  src/core/models/dt_linearmodel.cc
Labels: bug

#3235 Add a multicolumn test for linear model
  tests/models/test-linearmodel.py
Labels: test

#3236 Fix compiler warnings on Py_SET_REFCNT()
  src/core/buffer.cc
  src/core/column/const_na.cc
Labels: refactor

#3238 Move `pythoncapi_compat.h` to pythoncapi folder
  src/core/buffer.cc
  src/core/column/const_na.cc
  src/core/lib/pythoncapi/pythoncapi_compat.h
  src/core/python/namedtuple.cc
  src/core/python/tuple.cc
Labels: refactor

#3239 Internals for validity buffer for categorical columns
  src/core/column/categorical.cc
  src/core/column/categorical.h
  src/core/types/type_categorical.cc
Labels: refactor

#3240 Allow using column selector on categorical columns
  src/core/expr/eval_context.cc
  tests/types/test-categorical.py
Labels: improve

#3241 Allow using column selector on array columns
  src/core/expr/eval_context.cc
  tests/types/test-array.py
Labels: improve

#3242 Adjust `max_column_width` docs
  docs/api/options/display/max_column_width.rst
Labels: documentation

#3214 Switch to Python `3.10` for linux/macOS on AppVeyor
  ci/appveyor.yml
Labels: ITA
