Repository h2oai/datatable, pull requests merged in 2022-10, with the labels that each got.

#3364 Improve header detection heuristics in `fread()`
  docs/releases/v1.1.0.rst
  src/core/csv/reader_fread.cc
  src/core/types/type.cc
  src/core/types/type.h
  tests/fread/test-fread-detect.py
  tests/fread/test-fread-issues.py
  tests/fread/test-fread-small.py
Labels: improve

#3366 Parameter names and docs improvements
  docs/api/dt/shift.rst
  docs/api/str/slice.rst
  src/core/expr/fexpr_cumsumprod.cc
  src/core/expr/fexpr_fillna.cc
  src/core/expr/fexpr_slice.cc
  src/core/expr/head_func_shift.cc
  src/core/expr/re/fexpr_match.cc
  src/core/expr/str/fexpr_len.cc
  src/core/types/type_categorical.cc
  src/core/types/type_categorical.h
Labels: improve, documentation

#3367 Implement `dt.categories()`
  docs/api/dt/categories.rst
  docs/api/fexpr.rst
  docs/api/fexpr/categories.rst
  docs/api/index-api.rst
  src/core/documentation.h
  src/core/expr/fexpr.cc
  src/core/expr/fexpr.h
  src/core/expr/fexpr_categories.cc
  src/core/types/type_categorical.cc
  src/datatable/__init__.py
  tests/types/test-categorical.py
Labels: new feature

#3368 Fix "See also" sections for `cat*` types and `cbind()`/`rbind()` docs
  docs/api/dt/cbind.rst
  docs/api/dt/rbind.rst
  docs/api/frame/cbind.rst
  docs/api/type/cat16.rst
  docs/api/type/cat32.rst
  docs/api/type/cat8.rst
Labels: documentation

#3370 Add basic support for `Grouping::GtoFEW`
  src/core/expr/declarations.h
  src/core/expr/fexpr_alias.cc
  src/core/expr/fexpr_categories.cc
  src/core/expr/fexpr_dict.cc
  src/core/expr/fexpr_list.cc
  src/core/expr/fexpr_slice.cc
  src/core/expr/workframe.cc
  src/core/expr/workframe.h
  tests/types/test-categorical.py
Labels: improve

#3372 Implement casts from categorical columns to other types
  src/core/types/type_array.cc
  src/core/types/type_bool.cc
  src/core/types/type_date.cc
  src/core/types/type_object.cc
  src/core/types/type_string.cc
  src/core/types/type_time.cc
  src/core/types/typeimpl_numeric.cc
  tests/frame/test-tocsv.py
  tests/types/test-categorical.py
Labels: test, new feature

#3373 Implement statistics for categorical columns
  src/core/column.cc
  src/core/column/column_impl.cc
  src/core/column/column_impl.h
  src/core/stats.cc
  tests/types/test-categorical.py
Labels: new feature

#3344 [ENH] Enhance `dt.fillna()` to support filling with a particular value
  docs/api/dt/fillna.rst
  src/core/expr/fexpr.cc
  src/core/expr/fexpr_fillna.cc
  tests/dt/test-fillna.py
  tests/test-f.py
Labels: new feature

#3377 Update documentation regarding removal of python 3.6
  docs/api/frame/to_dict.rst
  docs/releases/v1.1.0.rst
  docs/start/install.rst
Labels: documentation
