Repository h2oai/datatable, pull requests merged in 2023-05, with the labels that each got.

#3461 Fortify fix #3412 for `dt.median()` when called in a groupby context
  src/core/sort.cc
Labels: bug, FIX

#3464 Remove obsolete reducer ops
  src/core/expr/op.h
  src/datatable/expr/expr.py
Labels: refactor

#3433 Replace spin-lock with conditional variable for `SleepTask`
  src/core/parallel/job_idle.cc
  src/core/parallel/job_idle.h
  src/core/parallel/thread_pool.cc
  src/core/parallel/thread_pool.h
Labels: improve

#3467 Fix target column type detection in `LinearModel`
  docs/releases/v1.1.0.rst
  src/core/models/py_linearmodel.cc
  tests/models/test-linearmodel.py
Labels: bug, test, FIX

#3469 Do not use unsupported `-m64` linker flag on `arm64`
  ci/ext.py
Labels: ITA

#3471 Fix builds on `aarch64`
  ci/ext.py
Labels: improve, ITA
