Repository h2oai/datatable, pull requests merged in 2023-03, with the labels that each got.

#3432 Minor improvements to thread pool
  src/core/parallel/job_idle.cc
  src/core/parallel/thread_team.cc
Labels: improve

#3435 Drop python `3.7` support
  ci/Jenkinsfile.groovy
  ci/appveyor.yml
  ci/ext.py
  ci/xbuild/extension.py
  docs/releases/v1.1.0.rst
  docs/start/install.rst
Labels: documentation, ITA

#3401 Refactor `min()` and `max()` reducers to use `FExpr`
  docs/api/dt/max.rst
  docs/api/dt/min.rst
  src/core/column/minmax.h
  src/core/expr/fexpr_minmax.cc
  src/core/expr/head_reduce_unary.cc
  src/datatable/expr/expr.py
  src/datatable/expr/reduce.py
  tests/test-reduce.py
Labels: improve

#3439 Add `DT_SEMAPHORE_SPIN_COUNT` to control spin count in thread pool
  src/core/parallel/api_primitives.h
  src/core/parallel/semaphore.h
Labels: improve, performance

#3443 Fix broken link to source in `dt.str.len()` documentation
  docs/api/str/len.rst
Labels: documentation, FIX

#3447 Improve ARM64 compatibility
  docs/releases/v1.1.0.rst
  src/core/column/cast_date32.cc
  src/core/column/cast_string.cc
  src/core/read/constants.cc
  src/core/read/constants.h
  src/core/read/parsers/parse_float.cc
  tests/conftest.py
  tests/fread/test-fread-small.py
  tests/munging/test-cast.py
Labels: improve, test, fread
