Repository h2oai/datatable, pull requests merged in 2023-02, with the labels that each got.

#3422 Fix crash when creating frames from numpy arrays of unicode strings
  docs/releases/v1.1.0.rst
  src/core/py_buffers.cc
  tests/frame/test-create.py
Labels: test, segfault, FIX

#3425 Fix rendering documentation for functions with optional parameters
  docs/_ext/xfunction.py
  docs/api/frame/__getitem__.rst
Labels: documentation, FIX

#3426 Add variables to control thread pool defaults
  src/core/parallel/api_primitives.h
Labels: refactor

#3429 Make `.to_numpy()` to honor number of rows for zero-column frames
  docs/releases/v1.1.0.rst
  src/core/frame/to_numpy.cc
  tests/frame/test-to-numpy.py
Labels: bug, FIX

#3423 [DevOps] Snyk Integration
  .github/workflows/snyk-scan.yml
Labels: ITA
