Repository h2oai/datatable, pull requests merged in 2023-01, with the labels that each got.

#3407 Fix datatable functions that shadow python built-ins
  docs/api/dt/sort.rst
  docs/releases/v0.11.0.rst
  docs/releases/v1.1.0.rst
  src/datatable/expr/reduce.py
  tests/munging/test-replace.py
  tests/test-dt-stats.py
  tests/test-groups.py
  tests/test-reduce.py
Labels: bug, test, FIX

#3410 Improve `cbind` documentation
  docs/api/dt/cbind.rst
  docs/api/frame/cbind.rst
  docs/api/frame/export_names.rst
  docs/releases/v0.10.0.rst
Labels: improve, documentation, FIX

#3412 Fix `dt.median()` when used on a groupby context for void columns
  docs/api/dt/median.rst
  docs/releases/v1.1.0.rst
  src/core/expr/head_reduce_unary.cc
  src/core/sort.cc
  tests/test-reduce.py
Labels: bug, documentation, FIX

#3402 Refactor `mean()` reducer to use `FExpr`
  docs/api/dt/mean.rst
  src/core/column/mean.h
  src/core/expr/fexpr_mean.cc
  src/core/expr/head_reduce_unary.cc
  src/datatable/__init__.py
  src/datatable/expr/__init__.py
  src/datatable/expr/expr.py
  src/datatable/expr/reduce.py
  tests/test-reduce.py
  tests/types/test-date32.py
Labels: improve, refactor
